### ISSUE TITLE
New update to >2.4.0

### ISSUE THREAD

**Issue by tech348712013870132** [bitnami/bitnami-docker-discourse#104]
When will this bitnami image contain discourse at version >2.4.0?

**Comment by carrodher** [comment]
According to the [release page](https://meta.discourse.org/t/discourse-version-2-4/108194), the planned release date is not set, it's TBD (To Be Defined). In the same way, we track the code from GitHub (https://github.com/discourse/discourse/releases), version 2.4.0 is a beta version, when it appears as stable we'll build the bitnami image using it
