### ISSUE TITLE
Discourse installation fails for connection to geolite database

### ISSUE THREAD

**Issue by pallavipawar521** [bitnami/bitnami-docker-discourse#122]
I am trying to install discourse using latest docker image on kubernetes. The installation fails with error "SocketError: Failed to open TCP connection to geolite.maxmind.com:443 (getaddrinfo: No address associated with hostname)" . Does bitnami support the solution provided here ? https://meta.discourse.org/t/upgrade-rebuilds-fail-due-to-maxmind-db-eol/137387/4

**Comment by rafariossaa** [comment]
Hi @pallavipawar521 ,
  We are trying to find a fix for this issue. 
  We will come back to you as soon as possible.

**Comment by mmacfadden** [comment]
This is a duplicate of #110

**Comment by juan131** [comment]
Closing as it's a duplicate

**Comment by nurchulis** [comment]
Check This if you use bitnami discourse without yml setting
Its Work
https://community.bitnami.com/t/receiving-500-error-after-trying-to-install-a-plugin/72570
