### ISSUE TITLE
How to install plugins in container because the entry point in Dockerfile does not allow me to execute anything after that

### ISSUE THREAD

**Issue by pallavipawar521** [bitnami/bitnami-docker-discourse#123]
Is there any good way to install plugins during discourse installation itself. I tried writing wrapper docker images but entrypoint script fails for some reason or the other.

**Comment by andresbono** [comment]
Hi @pallavipawar521, what's the error that you get?

**Comment by pallavipawar521** [comment]
> Hi @pallavipawar521, what's the error that you get?

When I try to install plugins in discourse-sidekiq container, I get error as "rake aborted!
SocketError: Failed to open TCP connection to geolite.maxmind.com:443 (getaddrinfo: Name or service not known)"

I followed below steps to install plugin
cd /opt/bitnami/discourse-sidekiq/plugins/
RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL
RAILS_ENV=production bundle exec rake assets:precompile (above error reported at this stage)

how can I get the plugin it in /opt/bitnami/discourse/plugins directory?

**Comment by andresbono** [comment]
The command `RAILS_ENV=production bundle exec rake assets:precompile` is already executed automatically. If you set the log level to `debug` (by specifying the env var NAMI_LOG_LEVEL=debug), you will see the following message in the logs:

```
discour INFO  Creating the Discourse admin user...
discour INFO  Configuring your Discourse installation...
discour DEBUG Precompiling assets...
...
```

**Comment by pallavipawar521** [comment]
> The command `RAILS_ENV=production bundle exec rake assets:precompile` is already executed automatically. If you set the log level to `debug` (by specifying the env var NAMI_LOG_LEVEL=debug), you will see the following message in the logs:
> 
> ```
> discour INFO  Creating the Discourse admin user...
> discour INFO  Configuring your Discourse installation...
> discour DEBUG Precompiling assets...
> ...
> ```

ok. Thats great. Is there any way to do so some admin related settings like configure openid connects, login and theme related settings apart from UI ?

**Comment by andresbono** [comment]
In this section of the README.md https://github.com/bitnami/bitnami-docker-discourse#user-content-configuration, you can find more information about the topic. Hope it helps!

**Comment by pallavipawar521** [comment]
> In this section of the README.md https://github.com/bitnami/bitnami-docker-discourse#user-content-configuration, you can find more information about the topic. Hope it helps!

Thanks... but what I need is to update site_settings on discourse installation itself.

**Comment by andresbono** [comment]
@pallavipawar521, you can find the `site_settings.yml` file in `/opt/bitnami/discourse/conf/site_settings.yml`. You should be able to mount that file as a volume so you can add your custom settings there.
