### ISSUE TITLE
Best Know method - How we can do debugging of entire Discourse Docker Image or code -

### ISSUE THREAD

**Issue by gauthamshettykaup** [bitnami/bitnami-docker-discourse#128]
Hello Team,

I'm not raising any issue here I would like to know "BKM: how we can do debugging of **Bitnami docker Discourse image **. Please guide us with related material/ video tutorial.

Regards,
Gautham

**Comment by jotamartos** [comment]
Hi @gauthamshettykaup ,

You can use the "NAMI_LOG_LEVEL=trace8" environment variable to obtain all the debug information during the deployment of the container. 

If you are more interested in knowing the different actions the module runs during the deployment, you have all the code under the /root/.nami folder of the container. 

Is this what you were looking for?

Thanks
