### ISSUE TITLE
How to connect to external postgres server ? Do we need to create database and user manually ?

### ISSUE THREAD

**Issue by pallavipawar521** [bitnami/bitnami-docker-discourse#129]
I am trying to connect to external postgres database on azure. I get error as 
postgre ERROR [canConnect] Connection with 'bn_discourse@<server_name>' user is unsuccessful
Error executing 'postInstallation': User bn_discourse@<server_name> already exists

**Comment by jotamartos** [comment]
Hi @pallavipawar521,

Could you please share the docker-compose.yml file/the docker command you used to start the container? Please hide the IP, user and password values. Did  you create the database and the user/password before starting the container?

Thanks

**Comment by pallavipawar521** [comment]
> Hi @pallavipawar521,
> 
> Could you please share the docker-compose.yml file/the docker command you used to start the container? Please hide the IP, user and password values. Did you create the database and the user/password before starting the container?
> 
> Thanks

No I did not create any user before hand ... I just specified all the database and user details in the yaml file itself.  Seems like there is some conflict in username .. whether to specify only username or username@<host>

**Comment by jotamartos** [comment]
Hi @pallavipawar521 ,

>I just specified all the database and user details in the yaml file itself. Seems like there is some conflict in username .. whether to specify only username or username@<host_name>.

Can you share the .yaml file you are using? Please substitute the database values when posting the information here.
