### ISSUE TITLE
Any plans to upgrade to 2.5 version ?

### ISSUE THREAD

**Issue by pallavipawar521** [bitnami/bitnami-docker-discourse#133]
Hi,
Since we have discourse 2.5.0 out, do we have any plans for upgrade and any expected time for it ?

**Comment by carrodher** [comment]
Hi,

We are tracking new releases from [Discourse GitHub Release page](https://github.com/discourse/discourse/releases), according to that page, Discourse 2.5.0 is a beta version and we only release stable versions of our components.
At this moment we are working on the release of the latest stable version (2.4.1).

**Comment by pallavipawar521** [comment]
> Hi,
> 
> We are tracking new releases from [Discourse GitHub Release page](https://github.com/discourse/discourse/releases), according to that page, Discourse 2.5.0 is a beta version and we only release stable versions of our components.
> At this moment we are working on the release of the latest stable version (2.4.1).

Ok. Is there any ETA for 2.4.1 ?

**Comment by carrodher** [comment]
I can't give you an exact ETA, but it should be ready during the following week.

**Comment by pallavipawar521** [comment]
> I can't give you an exact ETA, but it should be ready during the following week.

Great. Thanks for the quick reply.

**Comment by beltran-rubo** [comment]
The version 2.4.1 has been released yesterday.
