### ISSUE TITLE
force_https setting

### ISSUE THREAD

**Issue by cdupont** [bitnami/bitnami-docker-discourse#136]
Hi!
I am deploying bitnami discourse behind a proxy, which is handling the SSL termination.
However, it seems that I need to set "force_https" in the discourse settings file.
It would be nice if this setting is accessible via an environment variable.

**Comment by dani8art** [comment]
Hi @cdupont, thanks for opening this issue. Could you share with us more details of your deployment? do you have a docker-compose?

**Comment by cdupont** [comment]
I deployed in Amazon ECS, so I used the information in the docker-compose provided in this repository to re-create the same in Amazon.
I have a nginx proxy in front of this deployment, that is doing the SSL termination, i.e. the proxy receives requests in HTTPS and forwards them to the discourse container in HTTP only. The proxy takes care of adding the SSL and handling all the certificates (for discourse and many other HTTP services).
It work well, expect that Discourse include the images as HTTP in the webpages:
```
<link rel="icon" type="image/png" href="http://myforum.com/uploads/default/optimized/1X/_129430568242d1b7f853bb13ebea28b3f6af4e7_2_32x32.png">
```
I figured out the option "force_https" in the config file "site_settings.yml" in discourse could solve this.
But I don't know how to activate it using bitnami image...
Thanks a lot!

**Comment by dani8art** [comment]
Ok, now I understood, I was thinking exactly that you shouldn't have a problem with SSL since it was managed by your proxy and I was missing discourse force an absolute path to the images. 

- Have you try this [1]?

1. https://meta.discourse.org/t/advanced-setup-only-allowing-ssl-https-for-your-discourse-docker-setup/13847/222

**Comment by cdupont** [comment]
Thanks a lot! I didn't know this setting was in the UI!
