### ISSUE TITLE
how to restart nginx in the image . 

### ISSUE THREAD

**Issue by harshsingh1002** [bitnami/bitnami-docker-discourse#138]
Hi 
i am creating discourse setup on kubernetes using https://hub.docker.com/r/bitnami/discourse image . 
however when i exec into the pod there is no /etc/nginx directory . i wish to restart nginx . how do i do that

**Comment by javsalgar** [comment]
Hi,

Note that this image is not using nginx but Phusion Passenger. Normally in containers, the process would be to restart the container, as they usually have only one process. Could you detail your use case a bit more?

**Comment by harshsingh1002** [comment]
hi @javsalgar thanks for your reply 
the thing is i want to place my ssl certificates inside the pod . 
i found a nginx.conf and created a new server block but to bring that thing into action i wanted to restart the web server ( which i believed was nginx ) . but couldn't perform any nginx commands . 
can you tell me how do i restart the web server

**Comment by javsalgar** [comment]
Hi,

Normally, in a Kubernetes installation you would expect to set the certificate configuration in the ingress rule. Did you deploy it with ingress enabled?

**Comment by harshsingh1002** [comment]
@javsalgar i resolved it with putting tls termination on ingress . but still is there a way we can restart server

**Comment by javsalgar** [comment]
The only thing that comes to mind is to execute an nginx reload operation inside the container. Would that work? Otherwise, the container would stop.

**Comment by harshsingh1002** [comment]
hi @javsalgar nginx reload wont work . 
nginx: command not found

**Comment by javsalgar** [comment]
Hi, 

Where did you execute that command? It seems that `nginx` is not in the PATH. Could you try with `/opt/bitnami/nginx/sbin/nginx reload`?

**Comment by harshsingh1002** [comment]
so this path does not exists in the pod 
![Capture](https://user-images.githubusercontent.com/48350442/80953080-761a0f00-8e18-11ea-9c63-e880ee690a66.PNG)

**Comment by javsalgar** [comment]
Hi,

Sorry, I got confused with another ticket that was about nginx. As we said before, it is using Phusion Passenger so do not expect to see nginx in the image. An alternative for reloading could be this command

```
/opt/bitnami/discourse/bin/passenger-config restart-app
```

Please let us know if this solves the issue.

**Comment by harshsingh1002** [comment]
hi @javsalgar this worked . thanks a lot . 
however i saw a nginx-module binary there and i installed it . is there any way i can change my primary web server to nginx now

**Comment by javsalgar** [comment]
Hi,

That's not something that we directly support in the image. I presume that you can use another nginx container as a reverse proxy, if you want to use nginx (for example, in Kubernetes, you would have Nginx Ingress Controller in front of the Discourse instance)
