### ISSUE TITLE
Connecting to postgres via managed DB service 

### ISSUE THREAD

**Issue by harshsingh1002** [bitnami/bitnami-docker-discourse#139]
Hi 
i'm trying to use a cloud based database service for my setup  . i have changed the values of the env vars but when i run my deployment it says that it found postgres on so n so sever but  connection to the user is unsuccessful . Earlier i provided a env var ALLOW_EMPTY_PASSWORD = yes . how do i do it 
is there any variable that i have to pass

**Comment by juan131** [comment]
Hi @harshsingh1002 

As you can see in the link below, you need to set the environment variables: `POSTGRESQL_ROOT_USER`, `POSTGRESQL_ROOT_PASSWORD`, `POSTGRESQL_HOST` and `POSTGRESQL_PORT_NUMBER`.

- https://github.com/bitnami/bitnami-docker-discourse#environment-variables

**Comment by harshsingh1002** [comment]
hi @juan131  hi i have used these vars in my deployment but the discourse is not able to make connection with the database .
can you tell me whats exactly is the purpose of DISCOURSE_SKIP_INSTALL and how to use this

**Comment by juan131** [comment]
Hi @harshsingh1002 

You can find the description of every environment variable in the link below:

- https://github.com/bitnami/bitnami-docker-discourse#environment-variables

This environment variable skips running the Discourse installation Wizard for you based on the parameters you set. Instead, the 1st time Discourse is launched will show you the Wizard so you manually complete the process.

> hi i have used these vars in my deployment but the discourse is not able to make connection with the database

Could you share the **docker-compose.yaml** or command you're using to launch the Discourse container?

**Comment by harshsingh1002** [comment]
hi @juan131 i'm deploying my setup on kubernetes . now i wish to use a separate my database from my deployment file to Azure Database Service (PostgreSQL) . 
i manually created the user (bn_discourse) and database ( bitnami_application) and when i run the deployment i am able to connect to the DB but im stuck at " Migrating database" 

the thing is i already have a DB backup and i wish to start my discourse from that backup

**Comment by juan131** [comment]
> The thing is i already have a DB backup and i wish to start my discourse from that backup

In that case you must set the **DISCOURSE_SKIP_INSTALL** environment variable to "yes"

However, it's still necessary that Discourse has access to your database, that's why you're facing the issue when migrating it. Could you share the environment variable (all of them) that you're setting in the deployment you're using to deploy Discourse on K8s?

**Comment by harshsingh1002** [comment]
env: 
    - name: DISCOURSE_SKIP_INSTALL
      value: "yes"
    - name: POSTGRESQL_HOST
      value: postgresql-discourse.postgres.database.azure.com
    - name: POSTGRESQL_ROOT_USER
      value: postgres@postgresql-discourse
    - name: POSTGRESQL_ROOT_PASSWORD
      value: ******
#    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
#      value: bitnami_application
#    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
#      value: bn_discourse
#    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
#      value: bitnami1
    - name: DISCOURSE_POSTGRESQL_NAME
      value: bitnami_application
    - name: DISCOURSE_POSTGRESQL_USERNAME
      value: bn_discourse@postgresql-discourse
    - name: DISCOURSE_POSTGRESQL_PASSWORD
      value: bitnami1
    - name: DISCOURSE_HOST
      value: test-discourse
    - name: DISCOURSE_PORT
      value: "443"
    - name: DISCOURSE_HOSTNAME
      value: ******
    - name: REDIS_HOST
      value: test-redis
    - name: REDIS_PORT_NUMBER
      value: "6379"
    - name: SMTP_HOST
      value: ******
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_TLS
      value: "yes"
    - name: SMTP_USER
      value: *******
    - name: SMTP_PASSWORD
      value: ******
    - name: SMTP_AUTH
      value: login
    - name: DISCOURSE_USERNAME
      value: user
    - name: DISCOURSE_PASSWORD
      value: bitnami123
    - name: DISCOURSE_EMAIL
      value: *******

these are the env vars im using also im attaching the logs along with it 
[log.txt](https://github.com/bitnami/bitnami-docker-discourse/files/4591176/log.txt)

**Comment by harshsingh1002** [comment]
hi @juan131 im attaching my deployment file and the log file along with it 
[log.txt](https://github.com/bitnami/bitnami-docker-discourse/files/4591188/log.txt)
[deployment.txt](https://github.com/bitnami/bitnami-docker-discourse/files/4591203/deployment.txt)

i have commented few env vars in the deployment file because i have already created those manually

**Comment by juan131** [comment]
Hi @juan131 

Some comments:

- Don't specify the hostname for the username:

```diff
         - name: DISCOURSE_POSTGRESQL_USERNAME
-          value: bn_discourse@postgresql-discourse
+          value: bn_discourse
```

- The same comment applies to `POSTGRESQL_ROOT_PASSWORD`
- Test the connectivity, launch a container on your cluster with a `psql` client and try to access your Azure database using the same credentials you're setting on Discourse. Does it work?

**Comment by kevinhwang** [comment]
Hey @juan131 I'm having a similar issue.

I want to run this image simply passing in the env vars to connect to an AWS RDS database that's managed outside of the Discourse instance. I don't want Discourse needing root access to the RDS to create the database.

How do I accomplish this? Even skipping install, it still tries to connect using a root user and failing.

**Comment by juan131** [comment]
Hi @kevinhwang 

Could you share the environment variable you're using? Please do not paste credentials (e.g. substitute passwords with "*****".

**Comment by kevinhwang** [comment]
Hi @juan131, sure. I'm attempting to run it as an AWS ECS task, but here's the manual, equivalent:

```shell
docker run \
  -it \
  -e DISCOURSE_HOSTNAME=******** \
  -e DISCOURSE_SKIP_INSTALL=yes \
  -e POSTGRESQL_HOST=********.us-east-1.rds.amazonaws.com \
  -e POSTGRESQL_PORT_NUMBER=5432 \
  -e DISCOURSE_POSTGRESQL_USERNAME=******** \
  -e 'DISCOURSE_POSTGRESQL_PASSWORD=********' \
  -e DISCOURSE_POSTGRESQL_NAME=discourse \
  -e REDIS_HOST=********.ng.0001.use1.cache.amazonaws.com \
  -e REDIS_PORT_NUMBER=6379 \
  -e SMTP_HOST=smtp.mailgun.org \
  -e SMTP_PORT=587 \
  -e SMTP_USER=******** \
  -e SMTP_PASSWORD=******** \
  bitnami/discourse

```

When running this, I get:

```console
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at ********.us-east-1.rds.amazonaws.com:5432
postgre INFO  PostgreSQL server listening and working at ********.us-east-1.rds.amazonaws.com:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
Password for user postgres:
```

It appears to be attempting to connect to the DB using the default root user `postgres`.

If I attempt to simply supply the regular username / password (the ones referenced by `DISCOURSE_POSTGRESQL_USERNAME` and `DISCOURSE_POSTGRESQL_PASSWORD`) as the root username and password, I get:

```console
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Detected user custom configuration...
discour INFO  Custom configuration succesfully copied!
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at ********us-east-1.rds.amazonaws.com:5432
postgre INFO  PostgreSQL server listening and working at ********.us-east-1.rds.amazonaws.com:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
discour INFO  Migrating database...
Error executing 'postInstallation': rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "********"
```

**Comment by harshsingh1002** [comment]
hi @kevinhwang i have resolved this issue . you DONT have to actually create a new database use only exsisting user and databse

**Comment by kevinhwang** [comment]
@harshsingh1002 How do you prevent the container from trying to create a new database with a root user at start up?

**Comment by harshsingh1002** [comment]
@kevinhwang you manually create the database but make sure you use default user which is postgres i guess

**Comment by kevinhwang** [comment]
I see.

@juan131 is there any way to get it to not use the root user and just use the user we give it?

**Comment by harshsingh1002** [comment]
@kevinhwang yes you can use a custom user however if youll ever want to restore a backup it will give you postgre permission error

**Comment by harshsingh1002** [comment]
@kevinhwang i initially tried with custom user and i was facing issue with restoring so used default user but yes i created the database manually

**Comment by juan131** [comment]
Hi @harshsingh1002 

As @kevinhwang mentioned, if you don't want to provide the root credentials to the Discourse container (for security reasons) the backup restore functionality will be affected.

Discourse expects a database to exist in the PostgreSQL server. Therefore, when you don't provide the root credentials, you need to manually created it since the container won't be able to do it for you.
