### ISSUE TITLE
Discourse Performance question

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#141]
Hi there, 
thanks you for enabling the custom discourse.conf. With this I was able to have a look with the mini profiler because my hosted forum (with very low activity) has often performance issues in form of requests taking 3 to 10 seconds. 

It is not a hosting issue. I am running these docker container on a 2 CPU host with nothing else running. (TOP show CPU idle on 2-5%) and the volumes are mounted on fast SSDs.

Especially the creates (new forum post and new private message) take a long time.

![image](https://user-images.githubusercontent.com/1607849/81507656-24352580-92ff-11ea-9473-efb0fb9a0d56.png)

3435.30 ms | Executing action: create — 3435.30 ms
-- | --
Executing action: createT+3456.3 msReader0.7 ms | lib/new_post_manager.rb:207:in `perform' app/controllers/posts_controller.rb:179:in `create' lib/middleware/omniauth_bypass_middleware.rb:68:in `call' lib/content_security_policy/middleware.rb:12:in `call' lib/middleware/anonymous_cache.rb:318:in `call' config/initializers/100-quiet_logger.rb:18:in `call' config/initializers/100-silence_logger.rb:31:in `call' lib/middleware/enforce_hostname.rb:17:in `call' lib/middleware/request_tracker.rb:181:in `call' SELECT 1 AS one FROM "topics" WHERE ("topics"."deleted_at" IS NULL) AND "topics"."id" = 206 AND "topics"."archetype" = 'private_message' LIMIT 1;

Is this a normal behaviour? 

Thank you

Sebastian

**Comment by joancafom** [comment]
Hello Sebastian,

Glad to hear that the changes made a great deal of good! What was the approach you followed in order to profile your Discourse instance?

Regarding your host platform, and if I did understand it well, if your CPU is idle 2%~5% that means that its usage is around **98%~95%**. That could certainly be a bottleneck. Nevertheless, could you provide us with the output of the following commands?

- `docker info`
- `docker version`

**Comment by sbetzin** [comment]
1. I am sorry! I meant idle with 99%

![image](https://user-images.githubusercontent.com/1607849/81579253-3d47e000-93ac-11ea-829d-69f432f3225c.png)


2. docker version
`Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
`
3. docker info
`Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1036-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.767GiB
 Name: gutes-gemuese
 ID: A2LW:NCZ7:5XQL:P7TL:PQOL:FE2T:66E4:CZDB:RU4Q:NAHK:E6CY:A4O3
 Docker Root Dir: /datadrive/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
`


I have another product running as separate container: its the ghost blogging software. And this is fast as hell.

**Comment by joancafom** [comment]
Hello @sbetzin ,

I have tried to reproduce your request and performed a simple test in my system. It seems that that Discourse performs on that line, as my results turn out to be pretty similar:

![image](https://user-images.githubusercontent.com/24253844/81698632-8eb4a580-9466-11ea-9a50-13ae7de598c1.png)

Nevertheless, there are several aspects involved in the performance of an application. Not only do CPUs and disk matter, but other characteristics such as the type of CPU, the platform/instance in which docker is running, ... even the connection bandwidth.

Regarding the ghost blogging container you mentioned, they cannot be compared in terms of performance. Both instances use complete different technologies and thus it may not be fair to establish such a point.

I am glad I was able to help! Do not hesitate to contact us again if you have any other further questions.

**Comment by sbetzin** [comment]
@joancafom thanks for testing this from a separate project. I am aware of the fact that other factors are impacting performance. I am pretty sure I excluded everything and this is why I used the Mini Profiler to see the application timings.
I was opening this issue because we had the discourse native docker solution installed before. (We decided to use the bitnami one because we dont want to clone and install and create the docker image locally -> the pull and run approach seems much more convenient) With the native docker version we had not had any performance issue at all (was 2.5.0 beta3 version)....

**Comment by joancafom** [comment]
Hi again @sbetzin ,

I set up two brand-new docker instances (one using the `bitnami-docker-discourse` and the other the latest native version). In each of those, I followed the Use Case you provided us with (creating new forum post) and repeated it 3 times so as to get the mean time. Here you can take a look at the results I obtained:

- **Bitnami Container:**
![image](https://user-images.githubusercontent.com/24253844/81806029-29bb8700-951c-11ea-8404-6add4c7cde22.png)

   Average (taking into account my previous [post](https://github.com/bitnami/bitnami-docker-discourse/issues/141#issuecomment-627359167), that is, 4 samples): 1,28s

- **"Native" Discourse Container:**
![image](https://user-images.githubusercontent.com/24253844/81806227-756e3080-951c-11ea-96a7-b5dc44272585.png)

   Average (3 samples): 2,39s

As you can see, I have also experienced some similar times in the "native" Discourse container (including the time spike of 4s). With similar (even better results in my tests) between both containers, I do not think this is an issue directly related with our own solution.

Thanks and kind regards!
