### ISSUE TITLE
Just a blank screen with browser title "My site"

### ISSUE THREAD

**Issue by lonnietc** [bitnami/bitnami-docker-discourse#146]
Hello,

I have a Debian 10 system and wanted to try your discourse via docker-compose:

Docker version 19.03.9, build 9d988398e7
docker-compose version 1.23.1, build b02f1306

After following your base instructions:

$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-discourse/master/docker-compose.yml > docker-compose.yml

$ docker-compose up -d

Everything spins up just as it should and no errors are reported. I tested this by also running it as:

$ docker-compose up 

Not as a daemon for a second trial but still the same results.

All I get is a blank white screen in my chrome browser that has the title of the page as "Mu site!" but nothing else shows in the browser window.

tested at:

http://localhost
http://127.0.0.1

I let it initialize for 20 minutes and still the same result.

I have various other containers working on this system and have even tried to remove all of my images and running containers in a third trial, but still the same result.

Any ideas as to what is happening here?

Thanks in advance

**Comment by dani8art** [comment]
Hi @lonnietc, thanks for reporting your issue, I've try to reproduce it but I couldn't I tried the same as you but changing a few things. Could you try this, please?

```diff
--- docker-compose.yml  2020-06-08 08:17:17.103759126 +0000
+++ docker-compose.yml.new      2020-06-08 08:09:37.174558047 +0000
@@ -15,7 +15,7 @@
   discourse:
     image: 'docker.io/bitnami/discourse:2-debian-10'
     ports:
-      - '80:3000'
+      - '8080:3000'
     depends_on:
       - postgresql
       - redis
@@ -30,7 +30,7 @@
       - DISCOURSE_POSTGRESQL_NAME=bitnami_application
       - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
       - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
-      - DISCOURSE_HOSTNAME=www.example.com
+      - DISCOURSE_HOSTNAME=localhost:8080
   sidekiq:
     image: 'docker.io/bitnami/discourse:2-debian-10'
     depends_on:
@@ -44,7 +44,7 @@
       - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
       - DISCOURSE_HOST=discourse
       - DISCOURSE_PORT=3000
-      - DISCOURSE_HOSTNAME=www.example.com
+      - DISCOURSE_HOSTNAME=localhost:8080
 volumes:
   postgresql_data:
     driver: local
```

**Comment by ethancedwards8** [comment]
I had the same issue, oddly enough, changing the ports to 8080 worked

**Comment by dani8art** [comment]
Hi @ethancedwards8, actually is not that oddly. Discourse itself uses the hostname to make some redirections/routing so it needs to know where the site is going to be exposed so that it can do this successfully otherwise the redirections/routing will be done in a wrong way causing this kind of issues.

**Comment by frakman1** [comment]
I have this problem too. I am deploying on Portainer.
I get an error when using the default 80:3000 mapping (already in use) so I had to change it to something else
```
  discourse:
    image: 'docker.io/bitnami/discourse:2-debian-10'
    ports:
      - '8877:3000'
```
