### ISSUE TITLE
sidekiq on k8s: Cannot find pid file '/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid'

### ISSUE THREAD

**Issue by m0xx** [bitnami/bitnami-docker-discourse#147]
Hi,

I'm trying to run Discourse on Kubernetes. I have setup (2) Deployment, one for the Discourse server and one for the sidekiq that share a common volume. The Discourse server is running fine and but the boot sequence of the sidekiq always fails because it cannot find the `sidekiq.pid` file. 

Here is the logs of the container:
```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing discourse-sidekiq
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgres:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgres:5432
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Sidekiq...
discour INFO  Waiting for Discourse service to be ready...
nami    INFO  discourse-sidekiq successfully initialized
Starting discourse-sidekiq...
nami    ERROR Unable to start com.bitnami.discourse-sidekiq: Cannot find pid file '/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid'.
```

I'm not able to find the cause, anyone have an idea of what's going on?

**Comment by marcosbc** [comment]
Could you share your `docker-compose.yml` file, or a sample file where this issue happens?

**Comment by marcosbc** [comment]
Actually, nevermind. I see you are using Kubernetes. In that case, could you share a deployment where this issue happens?

We're currently working with a user on publishing a Bitnami Discourse Helm chart, maybe you find the solution to your issue [here](https://github.com/bitnami/charts/pull/2072/files#diff-cebdfa056bb718a82e2e9f85278f5873). For more info see [PR #2072](https://github.com/bitnami/charts/pull/2072).

**Comment by m0xx** [comment]
Thanks, great idea to have an Helm Chart! We rolled back to a simple installation on an instance, so I can't investigate the issue anymore.
