### ISSUE TITLE
Turn this into a Caprover one-click-app

### ISSUE THREAD

**Issue by ethancedwards8** [bitnami/bitnami-docker-discourse#149]
Hello, I'm currently turning this into a [Caprover](https://caprover.com/), [one-click-app](https://github.com/ethancedwards8/one-click-apps/blob/master/public/v2/apps/discourse.json), and I was asking if I could have some assistance.

**Comment by javsalgar** [comment]
Hi,

We don't have experience with how Caprover works, but you could use the docker-compose.yml configuration as a reference on how to configure this application. Is there an issue in the container startup?

**Comment by ethancedwards8** [comment]
No, the containers are fine, I have a lot of the file already made theirs just some bugs I need to work out

**Comment by ethancedwards8** [comment]
For example, when I'm running the postgresql file, I get the error `2020-06-29T12:52:55.483311657Z 2020-06-29 12:52:55.483 GMT [115] FATAL: role "discourse_user" does not exist`

**Comment by ethancedwards8** [comment]
discourse_user is the name of the user for the database, even if I set it to the default value I get the same error

**Comment by javsalgar** [comment]
Hi,

Does the postgresql database have the user initialized, maybe there's an incorrect PostgreSQL environment variable set. Which env vars did you set for postgres?

**Comment by ethancedwards8** [comment]
I got it figured out
