### ISSUE TITLE
discourse-sidekiq rubby take 4G of RAM 

### ISSUE THREAD

**Issue by lbouquinUniv** [bitnami/bitnami-docker-discourse#150]
we used, your docker-compose file ans we look at an hight level ram occupation. Is it possible to reduce it without restart container ? And why take it as much RAM.

**Comment by marcosbc** [comment]
@lbouquinUniv 

If you need to limit Discourse memory, check out how to limit memory for Docker containers here: https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

Note that a container restart will be required to apply any configuration change to the container (although it should not be a periodic task).
