### ISSUE TITLE
Is this a normal behavior? Restarting discourse container always migrates database

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#151]
Hi There,

I am unsure about this discourse behaviour. When I am stopping and restarting the docker discourse containers it always hangs on "migrating database" for minutes, sometimes for 10 minutes. While this is progressing the CPU is at 100% 

![image](https://user-images.githubusercontent.com/1607849/86287334-4f920d80-bbe8-11ea-951d-f5894b6462f7.png)

So my question: Is this a normal behavior? Am I doing something wrong?

Thanks 
Sebastian

**Comment by juan131** [comment]
Hi @sbetzin 

Are you including persistence in your Discourse containers (check https://github.com/bitnami/bitnami-docker-discourse#persisting-your-application)? The database migration is done everytime the container is restarted and it could take some time but it shouldn't be very long unless you're not persisting data.

**Comment by sbetzin** [comment]
@juan131 Thanks for the response and sorry for the lack of information. I am using a docker compose with a volume for data persistence. What information do you need?

**Comment by juan131** [comment]
Hi @sbetzin 

Here you have a piece of code taken from the script that initialises Magento:

```
  if (!volumeFunctions.isInitialized($app.persistDir)) {
    $app.info('Configuring Discourse database...');
    $app.helpers.enablePostgreSQLPlugins(databaseHandler);
    $app.helpers.migrateDatabase();
    if ($app.skipInstall === 'yes') {
      $app.info('You provided an already initialized Discourse database. '
        + 'The admin user creation and site configuration steps will be skipped. '
        + 'Parameters for configuring the user account and site name will be ignored.');
    } else {
      $app.helpers.createAdminUser($app.username, $app.password, $app.email, databaseHandler);
      $app.helpers.configureSiteSettings($app.username, $app.email, $app.siteName, databaseHandler);
    }
    volumeFunctions.prepareDataToPersist($app.dataToPersist);
  } else {
    volumeFunctions.restorePersistedData($app.dataToPersist);
    $app.helpers.migrateDatabase();
  }
```

As you can see, both when it's initializing Magento for the 1st time and during restarts (with persisted data), it runs the database migration function. That said, it shouldn't take so long on restarts.

Are you using Docker for Mac, or Docker for Windows? Could you please provide a little more information about your Docker Engine, your OS, etc? Thanks in advance

**Comment by sbetzin** [comment]
@juan131 

I posted all helpul info in this thread:
https://github.com/bitnami/bitnami-docker-discourse/issues/142

there are some docker environment and docker compose infos.

HtH

Sebastian

**Comment by juan131** [comment]
Thanks so much Sebastian!!!

**Comment by frakman1** [comment]
@sbetzin I am also seeing this migration on every restart despite using the same folder  for discourse and sidekiq in the `volume` section of the docker-compose file. Using the latest version of the file as of today.

**Comment by juan131** [comment]
Hi @frakman1 

It's expected, the `migrateDatabase` is executed every time the container is initialised (regardless it's a restart or not) as I mentioned on [this previous answer](https://github.com/bitnami/bitnami-docker-discourse/issues/151#issuecomment-653374527). However, it shouldn't take long on restarts to run this migration job.

Are you experiencing very slow initialisation processes?

**Comment by frakman1** [comment]
The link to the other issue by Sebastian suggested that the issue was due to the discourse and sidekiq containers not sharing the same volume. 

Yes, I saw your comment and code too, so this is expected.

> Are you experiencing very slow initialisation processes?

Well, it's not TOO slow, but it is slower than I would like. Is it possible to modify this logic or is it strictly required for normal operation? I am using the docker-compose logic so I'm not sure how to make such a change persistent.

**Comment by juan131** [comment]
Hi @frakman1 

Using the Docker Compose below:

- https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/docker-compose.yml

You'll find that both the `discourse` and `sidekiq` container share the same `discourse_data` volume. Could you give it a try?

**Comment by frakman1** [comment]
I'm already using the same folder for discourse and sidekiq.(as mentioned in my comment [above](https://github.com/bitnami/bitnami-docker-discourse/issues/151#issuecomment-770874735)

You're pointing to the same docker-compose file that is being used. It's nothing new and the file hasn't changed since July 24th 2020.

**Comment by juan131** [comment]
> I'm already using the same folder for discourse and sidekiq (as mentioned in my comment above)

Ops sorry, I missed that @frakman1 

> Well, it's not TOO slow, but it is slower than I would like. Is it possible to modify this logic or is it strictly required for normal operation? 

I'm afraid there's now way to skip that logic at this very moment.
