### ISSUE TITLE
Support new Discourse version 2.5.0

### ISSUE THREAD

**Issue by LucaPrete** [bitnami/bitnami-docker-discourse#152]
Discourse v2.5.0 is out and I think it would be good to support it.

I'll send a PR today.

**Comment by LucaPrete** [comment]
I'm trying to track down the dependencies as I see them in the Bitnami OVA (for example, Discourse 2.5.0 now wants postgresql-client 12.3).

What I don't understand is how to search for these files on your servers.

The Docker image uses the command `bitnami-pkg`, for example `bitnami-pkg unpack postgresql-client-11.8.0-3 --checksum 884f83caf091522e2ea8d03d69e5dcec5d7a309a6e3f9f434d9ee5acc14f4ce0`, which seems to download files using a curl against the address download.bitnami.com/files/....

Anyway, the bitnami-pkg seem to do not have any search functionality and I'm not even able to list files connecting with a browser to download.bitnami.com/files/...
So, how do I see what's the right package and what's the right checksum?

Once I know this the work should be pretty easy and quick and I'll get back very soon with a PR

**Comment by joancafom** [comment]
Hi @LucaPrete ,

Thanks for your issue and your willing to contribute! We are currently working in order to release an image with this new version of Discourse, so it should be out very soon. Regarding `bitnami-pkg`, there is no current way of listing the components and checksums 🤔  but, we will take into account your thoughts and evaluate them. 

Thanks again and hold on tight, Discourse 2.5.0 is coming 🚀

**Comment by LucaPrete** [comment]
Good to know, thanks!

Do you guys already have a timeline in mind?

Il giorno gio 9 lug 2020 alle 13:35 Jose Antonio Carmona <
notifications@github.com> ha scritto:

**Comment by joancafom** [comment]
Hi @LucaPrete 

I am currently working on this and it should be released by next week 😁

**Comment by LucaPrete** [comment]
Nice! Thank you

Il giorno ven 10 lug 2020 alle 11:37 Jose Antonio Carmona <
notifications@github.com> ha scritto:

**Comment by shadowfox87** [comment]
I hope bitnami can release the latest version soon. They are already on version 2.6 beta now. There have been several improvements and certain plugins only work on this. Is there a way we can upgrade the bitnami image to the one used by the official Discourse?

**Comment by ieugen** [comment]
Looking forward to this. 
I'm also looking into building an internal image. 
Where is the work for 2.5.0 ? I think I can test it.

**Comment by joancafom** [comment]
Hi @shadowfox87 @ieugen 

Apologies on the delay, we have faced some [external issues](https://github.com/phusion/passenger/issues/2124) related with Passenger. Discourse@2.5.0 should be released during the day.

Regarding building your own image, you can always take a look at the [internals](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/Dockerfile) of this container and extend (or even implement) your own version 😄. 

Best regards.

**Comment by joancafom** [comment]
Discourse version 2.5.0 is [out](https://github.com/bitnami/bitnami-docker-discourse/commit/02f8ce59adda76eb59850a53a71329a8005e117b) now !

**Comment by LucaPrete** [comment]
This is great!

I'll give it a try asap.

Thanks,

-Luca

Il giorno gio 16 lug 2020 alle ore 11:29 Jose Antonio Carmona <
notifications@github.com> ha scritto:
