### ISSUE TITLE
Env variable DISCOURSE_EMAIL not being passed in discourse.conf file

### ISSUE THREAD

**Issue by ggeo1992** [bitnami/bitnami-docker-discourse#153]
**Description**

Trying to run the bitnami discourse image via the bitnami helm charts on a kubernetes cluster.
I am able to start the pod but when I reach the "Congratulations, you installed discourse " page, and click register, I get the message that no administrator email was provided. When I checked the /opt/bitnami/discourse/conf/discourse.conf file, in the container, I noticed that there is no variable developer_emails there, although, the environment variable DISCOURSE_EMAIL was set and I can see it being set in the environment.

**Steps to reproduce the issue:**

1. Setup the values.yaml file for the bitnami/discourse helm charts
2. Install the helm chart on the kubernetes cluster
3. Application deployment get created and the discourse pod comes up along with it's two containers (discourse and sidekiq)
4. Access the discourse application through it's exposed service
5. Click on register
6. Getting the error "No administrator email was provided...."

**Describe the results you received:**

Getting the error "No administrator email was provided....". Variable developer_emails missing from the/opt/bitnami/discourse/conf/discourse.conf file

**Describe the results you expected:**

Variable developer_emails should be set in the /opt/bitnami/discourse/conf/discourse.conf file. Email should be sent tot the provided email for account confirmation.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Installing it in IBM cloud, on an IBM Kuberenetes Cluster, version 1.17

Thank you in advance for your help.
George

**Comment by dani8art** [comment]
Hi @ggeo1992, sorry but I can not reproduce it, did you set your email address as following?

```
--set discourse.email=myemail@example.com
```

**Comment by ggeo1992** [comment]
Hello @dani8art , I tried setting it using --set flag and also by just defining it in the values.yaml file. 
This doesn't seem to be a problem with the charts, as the env variable DISCOURSE_EMAIL gets created on the container with the correct value, but it doesn't seem to be set in the discourse.conf file...

Supplying some more info on the environment:
Worker nodes OS: Ubuntu 18.04.4 LTS
containerd version: v1.3.4 814b7956fafc7a0980ea07e950f983d0837e5578

Is there any log in which this behavior could be checked?

Thank you,

**Comment by joancafom** [comment]
Hi @ggeo1992 !

I have been trying to reproduce your issue in the container itself but was unable to do so. While it is true that `discourse.conf` does not hold the value of the admin email, the database does have it properly registered. These are the steps I have followed:

1. Clone the repo
```console 
$ git clone https://github.com/bitnami/bitnami-docker-discourse.git discourse && cd discourse
```

2. Set a custom email by modifying the provided `docker-compose.yml`, for example:
```yaml
...
discourse:
    image: 'docker.io/bitnami/discourse:2-debian-10'
    ...
    environment:
      - DISCOURSE_EMAIL=caffe@caramel.com
      - DISCOURSE_HOSTNAME=localhost
    ...
```

2. Start discourse using `docker-compose` and wait until it is ready:
```console
$ docker-compose up
```

3. Now, your application should be up and running in http://localhost . 

4. To ensure email was properly configure, you can check out the database

```console
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                  NAMES
5c92f1450eae        bitnami/discourse:2-debian-10     "/app-entrypoint.sh …"   6 minutes ago       Up 6 minutes        3000/tcp               bitnami-docker-discourse_sidekiq_1
045d8f55406b        bitnami/discourse:2-debian-10     "/app-entrypoint.sh …"   6 minutes ago       Up 6 minutes        0.0.0.0:80->3000/tcp   bitnami-docker-discourse_discourse_1
6ab1046c515a        bitnami/redis:5.0-debian-10       "/opt/bitnami/script…"   6 minutes ago       Up 6 minutes        6379/tcp               bitnami-docker-discourse_redis_1
bf35afc1b398        bitnami/postgresql:11-debian-10   "/opt/bitnami/script…"   6 minutes ago       Up 6 minutes        5432/tcp               bitnami-docker-discourse_postgresql_1
```
``` console
$ docker exec -it bitnami-docker-discourse_postgresql_1 psql -U postgres
$ postgres=# \c bitnami_application
You are now connected to database "bitnami_application" as user "postgres".
$ bitnami_application=# select * from site_settings as s where s.name like '%email%';
 id |        name        | data_type |       value       |         created_at         |         updated_at
----+--------------------+-----------+-------------------+----------------------------+----------------------------
  7 | notification_email |        14 | caffe@caramel.com | 2020-07-13 10:28:31.456607 | 2020-07-13 10:28:31.456607
 22 | contact_email      |         1 | caffe@caramel.com | 2020-07-13 10:28:39.61621  | 2020-07-13 10:28:39.61621
(2 rows)
```

Could you check this values are set in the database?

Thanks!

**Comment by ArcticSnowman** [comment]
I'm hitting this same issue.   

```
DISCOURSE_EMAIL=discourse@grantstreet.com
```

```
bitnami_application=> select name, value from site_settings where name like '%email%';
        name        |                 value
--------------------+---------------------------------------
 notification_email | noreply@dev-discourse.grantstreet.com
```

**Comment by ArcticSnowman** [comment]
@joancafom  - can we reopen this ticket? or should it go under the helm chart?

**Comment by ArcticSnowman** [comment]
`docker-compose up`  shows this in the logs
```
discourse_1   | discour INFO  Creating the Discourse admin user...
discourse_1   | discour INFO  Configuring your Discourse installation...
```
however the helm logs do not show that..
