### ISSUE TITLE
Troubleshooting advices don't work with the image - rake admin:create

### ISSUE THREAD

**Issue by ieugen** [bitnami/bitnami-docker-discourse#155]
**Description**

I can't follow the documentation advises from the meta.discourse.org / internet since the image is missing `launcher` . 

**Steps to reproduce the issue:**

I've setup a discourse app using the helm chart and discourse 2.5.0-debian-10-r0. 
The installation failed and that is what made me raise this issue. 

The index page displayed a registration form.
Went to https://discourse.examplec.com/latest to try to login with admin. 

I see the message: 

> Congratulations, you installed Discourse! Unfortunately, no administrator emails were defined during setup, so finalizing the configuration may be difficult. 

I follow the link to  https://meta.discourse.org/t/create-admin-account-from-console/17274 . 

**Describe the results you received:**

I kubectl exec into the discourse container but I can't find the `launcher` so I can fix my login / admin password .  
I also tried to run `rake admin:create` and `bundle exec rake admin:create` without success.

I'm not a ruby user so I don't know what else I can do. 

**Describe the results you expected:**

I would like to be able to run administrative commands and troubleshoot / fix my instance. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

I'm using k3s 1.18 with containerd: docker.io/bitnami/discourse:2.5.0-debian-10-r0

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

`````
rake admin:create 
rake aborted!
Gem::LoadError: You have already activated rake 12.3.3, but your Gemfile requires rake 13.0.1. Prepending `bundle exec` to your command may solve this.
/opt/bitnami/discourse/config/boot.rb:13:in `<top (required)>'
/opt/bitnami/discourse/config/application.rb:16:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
root@discourse-co-7c757bdcd-fzsmz:/opt/bitnami/discourse# bundle exec      
bundler: exec needs a command to run

`````

`````
opt/bitnami/discourse# bundle exec rake admin:create 
rake aborted!
LoadError: cannot load such file -- rb-inotify
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `rescue in require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
/opt/bitnami/discourse/config/application.rb:65:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan: 

````

**Comment by andresbono** [comment]
Hi @ieugen, did you modify the default values to deploy the chart? We would like to reproduce the issue.

**Comment by ieugen** [comment]
Hi @andresbono ,

The issue is not that it failed to install (I managed to do that eventually, I believe there is a bug when using an existing database without a password for the default `postgres` user ).

The purpose of this issue is to debug those cases where I need to run troubleshooting commands inside the image, as described by most help pages like https://meta.discourse.org/t/create-admin-account-from-console/17274 .

**Comment by andresbono** [comment]
Oh ok, @ieugen. Thanks for confirming that you managed to install it successfully.

About the fail with the rake command, you should be able to execute it as follows:
```RAILS_ENV=production bundle exec rake admin:create```

About the [launcher utility](https://github.com/discourse/discourse_docker/blob/master/launcher), this container doesn't ship it, I believe that script is specific for https://github.com/discourse/discourse_docker
