### ISSUE TITLE
container restart. - tries to reinstall the app

### ISSUE THREAD

**Issue by rosscdh** [bitnami/bitnami-docker-discourse#158]
**Description**

Hi there, thanks for providing a proper docker means of installing discourse.

I've installed the app and setup redis and postgres with persistence; the database is configured and running well.

On restart of the discourse container, the startup tries to reinstall the system 

```
nami    INFO  Initializing postgresql-client
    nami    INFO  postgresql-client successfully initialized
    nami    INFO  Initializing discourse
    discour INFO  Patching Discourse...
    postgre INFO  Trying to connect to PostgreSQL server
    postgre INFO  Found PostgreSQL server listening at postgres:5432
    postgre INFO  PostgreSQL server listening and working at postgres:5432
    discour INFO  Preparing Discourse environment...
    discour INFO  Configuring the Discourse database files...
    discour INFO  Configuring Redis...
    discour INFO  Setting up SMTP in Discourse...
    discour INFO  Configuring Discourse database...
    discour INFO  Enabling PostgreSQL plugins for Discourse...
    discour INFO  Migrating database...
    discour INFO  Creating the Discourse admin user...
    discour INFO  Configuring your Discourse installation...
    Error executing 'postInstallation': ERROR:  duplicate key value violates unique constraint "index_site_settings_on_name"
    DETAIL:  Key (name)=(site_contact_username) already exists.
```

**Steps to reproduce the issue:**

1. use image in a container
2. persiste thigns to databse
3. configure the app via the ui
4. restart the container

**Describe the results you received:**

container starts but tries to reinstall the app and dies on 

```
    Error executing 'postInstallation': ERROR:  duplicate key value violates unique constraint "index_site_settings_on_name"
    DETAIL:  Key (name)=(site_contact_username) already exists.
```

**Describe the results you expected:**

on restart app works with exsiting database

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Just to confirm, you are not adding persistence to the Discourse installation, right? That would explain that it tries to reconfigure itself again. If that's the case, you could set the env vars `DISCOURSE_SKIP_INSTALL` to `yes`. That should avoid the re-installation.

**Comment by rosscdh** [comment]
Hi there thanks! Yep set it to yes.. but then the system cant connect using the users.. and i get the "emtpy list" error mentioned in other tickets..

very werid.

**Comment by javsalgar** [comment]
Hi,

About the "empty list" error, could you let us know which error you are referring to? Also, what error appears in the log when trying to login? Are the users in the PostgreSQL database?

**Comment by rosscdh** [comment]
All good thanks, iv built a new version based on the official launcher and reworked its internals so that its more dockerised
so have moved away from bitnami (in this case) unfortunately but thanks for your support

https://github.com/rosscdh/discourse-compose
which uses an image based on
https://github.com/rosscdh/discourse_docker/blob/feature/kube-version/samples/kube_web.yml

```
cat samples/kube_web.yml > containers/my_kube.yaml
./launcher rebuild my_kube.yml

retag the image to something useful push and thanks for coming then use the docker compose
```
