### ISSUE TITLE
Can't create Discourse backup: PostgreSQL version mismatch

### ISSUE THREAD

**Issue by shadowfox87** [bitnami/bitnami-docker-discourse#159]
**Description**

I cannot create a backup because it seems I have two different versions of PostgreSQL. The default one being used is version 11.8 and 12.3 is the new one. The pg_dump hence fails to create a backup as 12.3 isn't being used. I tried uninstalling 12 but it still gives the same error message.

**Steps to reproduce the issue:**

1. Go into the admin panel -> backup.
2. Try to create a backup.
3. Fails to create backup

**Describe the results you received:**

Output of the backup log in the admin panel:

```
[2020-07-30 04:32:37] pg_dump: server version: 12.3 (Debian 12.3-1.pgdg100+1); pg_dump version: 11.8 (Debian 11.8-1.pgdg100+1)
[2020-07-30 04:32:37] EXCEPTION: pg_dump failed
```

Output of when going into the container to create a backup manually:
![image](https://user-images.githubusercontent.com/12994748/88924225-f2b66100-d240-11ea-986b-ed4013febd1b.png)

**Describe the results you expected:**

I expect for the backup to be created.

**Additional information you deem important (e.g. issue happens only occasionally):**

![image](https://user-images.githubusercontent.com/12994748/88924484-59d41580-d241-11ea-8547-193b82483419.png)
These are the versions of PostgreSQL that show to be installed.

The version 11.8 comes installed with bitnami: bitnami/bitnami-docker-discourse/blob/2.5.0-debian-10-r8/2/debian-10/Dockerfile#L12

I have only 1 docker container. The output from `pg_slclusters`:

![image](https://user-images.githubusercontent.com/12994748/88925075-0d3d0a00-d242-11ea-85a9-78a35f496fe9.png)

I already tried using `sudo apt purge postgresql-12* and `apt purge postgresql-client-12*`.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.941GiB
 Name: duelistsunite
 ID: 2OHO:VRDL:YIKJ:GAO3:B5ZQ:G5EW:SP3H:XNFW:GHXK:VJB2:ZEAJ:EA7A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by shadowfox87** [comment]
Nevermind solved it using these 2 commands:

`sudo apt purge postgresql-11 postgresql-client-11` (get rid of 11 first)
`sudo ln -s /usr/lib/postgresql/12/bin/pg_dump /usr/bin/pg_dump --force` (Recreate the symbolic link in /usr/bin so that the pg_dump version matches server version)

**Comment by noplanman** [comment]
For anybody else coming here, I did the following in the container:
```
nami uninstall postgresql-client
bitnami-pkg unpack postgresql-client-13.2.0-0
```

Best to use a custom image extending this one though, to keep such changes persistent.
