### ISSUE TITLE
problems sending email

### ISSUE THREAD

**Issue by JanMrlth** [bitnami/bitnami-docker-discourse#160]
**Description**

I can not send Emails with this Docker setup 

**Steps to reproduce the issue:**

I added these Labels to the discourse container
DISCOURSE_EMAIL
SMTP_HOST=mail.[mymailserver.de]
SMTP_PORT=587
SMTP_USER=[USERNAME]
SMTP_PASSWORD=[PASSWORD]
SMTP_AUTH=plain
SMTP_TLS=yes

And those to the sidekiq
SMTP_HOST=mail.[mymailserver.de]
SMTP_PORT=587
SMTP_USER=[USERNAME]
SMTP_PASSWORD=[PASSWORD]
SMTP_AUTH=plain
SMTP_TLS=yes

**Describe the results you received:**

the log of the discourse container says: 

Processing by Admin::EmailController#test as */*
  Parameters: {"email_address"=>"[mytestmail@mail.com]"}
  Rendering layouts/email_template.html.erb
  Rendered layouts/email_template.html.erb (Duration: 0.7ms | Allocations: 284)
Delivered mail b82e3cd6-25ff-4a73-93e4-c372829d0007@[mydomain.de] (30003.2ms)

The web-frontend gives me: 
There was a problem sending the test email. Please double-check your mail settings, verify that your host is not blocking mail connections, and try again.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried several servers. 
My email-settings work e.g. for gitlab with no issues. 

**Version**
Docker version 19.03.12, build 48a66213fe

- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 52
  Running: 49
  Paused: 0
  Stopped: 3
 Images: 40
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.67GiB
 Name: v2202007125425123704
 ID: YEJC:55L5:D7IY:JA2E:JOP3:SQZ7:S4LH:VK45:ZA5P:DEZK:DAKA:UQW4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- Output of `docker-compose version` (if applicable):

docker-compose version 1.26.2, build eefe0d31

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
 Could you try to send it manually from the console by following this guideline ?  https://www.stevenrombauts.be/2018/12/test-smtp-with-telnet-or-openssl/ 
  I would like first to discern if it is container related or discourse related.

**Comment by JanMrlth** [comment]
ui - cert error on my side of things. Sorry to bother you. Thanks for the tipp! Cheers
