### ISSUE TITLE
I install bitnami discourse, it stop at "Trying to connect to PostgreSQL server"

### ISSUE THREAD

**Issue by cmdntd** [bitnami/bitnami-docker-discourse#162]
I install Bitnami Discourse in Plesk, Docker extension
It just stop "Trying to connect to PostgreSQL server", with default VARIABLES

I don't know why?

![Plesk-Obsidian-18-0-29](https://user-images.githubusercontent.com/1112881/91203511-53946480-e72d-11ea-80e7-d28de8c9d538.png)

**Comment by cmdntd** [comment]
Error executing 'postInstallation': Failed to connect to localhost:5432 after 36 tries

**Comment by carrodher** [comment]
Discourse needs a PostgreSQL database running, by default it is trying to find it in the same host using the `5432` port. When it is deployed using the docker-compose, it is already configured. If you are deploying Discourse on a different way, you need to provide this PostgreSQL database and "connect" it to the Discourse container by using the environment variables, see https://github.com/bitnami/bitnami-docker-discourse#environment-variables

Something similar is going to happen with other required services like redis. [Here](https://github.com/bitnami/bitnami-docker-discourse#run-the-application-manually) you can find the instructions about how to deploy all the required services manually; the other way is using docker-compose where everything is pre-configured, see https://github.com/bitnami/bitnami-docker-discourse#run-the-application-using-docker-compose

**Comment by cmdntd** [comment]
I tried to use default variables of bitnami for docker compose, but it still failed like that (Trying to connect to PostgreSQL)
Like below image...
Is there any thing with firewall? (google compute, plesk, docker)
![Plesk-Obsidian-18-0-29](https://user-images.githubusercontent.com/1112881/91340802-ca4f6180-e802-11ea-962f-659eba962b57.png)

**Comment by carrodher** [comment]
With those environment variables, your Discourse container is looking for a PostgreSQL database in `postgresql` (POSTGRESQL_HOST) and a Redis container in `redis` (`REDIS_HOST`). Do you have those containers running in that network? Setting the environment variables is a way to set the parameters to be used, but you need to deploy the services.

This is done automatically with docker-compose, but AFAIK is not done by Plesk so if you are using Plesk you need to manually deploy Discourse container, PostgreSQL container, Sidekiq container, and Redis container, then configure the networking to be reachable and then via env. variables set the proper parameters to connect some containers with others
