### ISSUE TITLE
Feature: AzureAD Authentication

### ISSUE THREAD

**Issue by iwilltry42** [bitnami/bitnami-docker-discourse#169]
Hi there,

thanks for this nice project, the Docker Image and the Helm Chart!

I'm currently trying to use https://github.com/discourse/discourse-azure-ad for authentication.
While I can install the plugin into the mounted volume without a problem, I cannot configure it persistently, as the `discourse.conf` is not persisted across re-deployments.
Since it's a nami package, I also can't seem to find an easy way to add some things to the config.
What I tried so far:
- mount a custom config to `/opt/bitnami/discourse/mounted-conf`
  - This works to override the configuration, but also skips the setup, so I end up without e.g. the admin user created
- follow the approach from #164 and modify the stuff in `.nami/components/com.bitnami.discourse` (and the sidekiq)
  - this is definitely not easy to maintain, if I cannot push this upstream to your internal nami package, right?
I'd love to have an easy/reproducible way to have such a config as code just like the other settings :)

**Comment by iwilltry42** [comment]
Nevermind.. I screwed up the configuration and figured everything out while digging through the configuration stuff in nami :roll_eyes: :grimacing:

**Comment by juan131** [comment]
We're glad you were able to solve the issue by your own means @iwilltry42 ! Please do not hesitate to let us know if you require further help.
