### ISSUE TITLE
Request extremely slow sometimes

### ISSUE THREAD

**Issue by dzvon** [bitnami/bitnami-docker-discourse#172]
**Description**

Following the instruction:

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-discourse/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

I launched my local discourse server, it's so weird that some request is extremely slow (see the image below) as I refresh the page every several seconds, but I cannot figure out why.

![image](https://user-images.githubusercontent.com/3402811/103981125-274d2200-51bc-11eb-87e6-65b476b352b6.png)

I enable `load_mini_profiler`, it seems like not discourse's problem. So I came here for help.

Thank you.

**Comment by juan131** [comment]
Hi @persevereVon 

What specific requests are very slow?
What machine are you using to deploy the containers? Has it enough RAM/CPU?
Is the Discourse container consuming too much CPU or memory? You can check it by:

- Obtain the Discourse container name:

```
$ docker-compose ps
             Name                            Command               State          Ports
-----------------------------------------------------------------------------------------------
bitnami-docker-                   /app-entrypoint.sh nami st ...   Up      0.0.0.0:80->3000/tcp
discourse_discourse_1
bitnami-docker-                   /opt/bitnami/scripts/postg ...   Up      5432/tcp
discourse_postgresql_1
bitnami-docker-                   /opt/bitnami/scripts/redis ...   Up      6379/tcp
discourse_redis_1
bitnami-docker-                   /app-entrypoint.sh nami st ...   Up      3000/tcp
discourse_sidekiq_1
```

- Run `docker stats`:

```
$ docker stats bitnami-docker-discourse_discourse_1
CONTAINER ID   NAME                                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
aa6ce44d437b   bitnami-docker-discourse_discourse_1   0.01%     726.2MiB / 1.941GiB   36.53%    4.71MB / 10.8MB   466MB / 38.8MB   80
```

**Comment by persevereVon** [comment]
> What specific requests are very slow?

Index page, my request URL is `discourse.local/`. But I'm not sure if the other page has the same circumstance.

> What machine are you using to deploy the containers? Has it enough RAM/CPU?

I think I have enough RAM/CPU resource for it.
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
RAM: 16G

> Is the Discourse container consuming too much CPU or memory?

```bash
❯ docker-compose ps
             Name                           Command               State          Ports
----------------------------------------------------------------------------------------------
bitnami-discourse_discourse_1    /app-entrypoint.sh nami st ...   Up      0.0.0.0:80->3000/tcp
bitnami-discourse_postgresql_1   /opt/bitnami/scripts/postg ...   Up      5432/tcp
bitnami-discourse_redis_1        /opt/bitnami/scripts/redis ...   Up      6379/tcp
bitnami-discourse_sidekiq_1      /app-entrypoint.sh nami st ...   Up      3000/tcp

❯ docker stats
CONTAINER ID   NAME                             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
742cf3697724   bitnami-discourse_sidekiq_1      0.15%     382.4MiB / 15.58GiB   2.40%     14.2MB / 23.6MB   53MB / 6.2MB      26
0a5808488b63   bitnami-discourse_discourse_1    0.00%     551MiB / 15.58GiB     3.45%     27MB / 281MB      154MB / 49MB      64
c866733d687b   bitnami-discourse_postgresql_1   0.00%     30.96MiB / 15.58GiB   0.19%     5.97MB / 13.2MB   9.98MB / 38.6MB   9
da8482f0def9   bitnami-discourse_redis_1        0.13%     13.41MiB / 15.58GiB   0.08%     43.8MB / 24.7MB   1.69MB / 75.2MB   6
```

**Comment by persevereVon** [comment]
BTW, my colleague has the same circumstance as mine.

**Comment by juan131** [comment]
Hi @persevereVon 

It doesn't look like an issue related with not having enough cpu/ram resources... 

I just installed Discourse using the same docker-compose.yaml (I only changed the env. variable `DISCOURSE_HOSTNAME=foo.bar.com` on Discourse and Sidekiq containers) on my Mac, and I obtained a "decent" time response when accessing to http://foo.bar.com, see:

![Screenshot 2021-01-11 at 11 44 41](https://user-images.githubusercontent.com/6740773/104171251-a59b0580-5402-11eb-86de-f1b23f0bc456.png)

Are you able to reproduce the same issue on a different computer? What do you obtain when running the command below:

```
$ docker version
```

**Comment by persevereVon** [comment]
Hi @juan131 

Thanks for your reply.

Maybe you can refresh a few more times, it occurs once in a while. 

This is `docker version` output on my computer:

```
❯ docker version
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        2291f610ae
 Built:             Tue Jan  5 19:56:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       8891c58a43
  Built:            Tue Jan  5 19:55:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

> Are you able to reproduce the same issue on a different computer? What do you obtain when running the command below?

yes, this is my colleague's screenshot:

![lALPDg7mPTSmrtvNBh_NCkw_2636_1567](https://user-images.githubusercontent.com/3402811/104283697-e3278d80-54eb-11eb-936f-c50baf95fa55.png)

`www.example.com` is a discourse server using docker-compose.yaml running on his computer, his docker version is `19.03.13`.

**Comment by juan131** [comment]
Hi @persevereVon 

I run the [Lighthouse](https://developers.google.com/web/tools/lighthouse) to detect problems and I did not find a poor performance:

![Screenshot 2021-01-12 at 12 26 13](https://user-images.githubusercontent.com/6740773/104308717-638cc500-54d1-11eb-8a7d-6f03e6ecd2ac.png)

Could you do the same on your side?

**Comment by persevereVon** [comment]
![image](https://user-images.githubusercontent.com/3402811/104394148-f3d61300-5580-11eb-8eaf-53118c068515.png)

This is not inevitable, it happens on a regular basis.

**Comment by juan131** [comment]
Hi @persevereVon 

I did another test refreshing several times the website:

![Screenshot_2021-01-13_at_09_53_53](https://user-images.githubusercontent.com/6740773/104429760-45cd6780-5586-11eb-9f78-1ac92cd89035.png)

As you can see, some of the requests were much slower than the rest. Then, I inspected one of these slow requests:

![Screenshot 2021-01-13 at 09 54 34](https://user-images.githubusercontent.com/6740773/104429849-58e03780-5586-11eb-892d-83fb474541c0.png)

We can see the TTFB (Time To First Byte) is 5.1 seconds. For some reason, the server is taking too long to respond. However, if we take a look to the container logs:

```console
$ docker-compose logs discourse | grep "Completed 200 OK in"
discourse_1   | Completed 200 OK in 5ms (Views: 1.9ms | ActiveRecord: 0.0ms | Allocations: 1566)
discourse_1   | Completed 200 OK in 13ms (Views: 1.7ms | ActiveRecord: 0.0ms | Allocations: 1567)
discourse_1   | Completed 200 OK in 28ms (Views: 3.3ms | ActiveRecord: 0.0ms | Allocations: 1027)
discourse_1   | Completed 200 OK in 4ms (Views: 1.6ms | ActiveRecord: 0.0ms | Allocations: 1027)
discourse_1   | Completed 200 OK in 2ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 1027)
discourse_1   | Completed 200 OK in 2ms (Views: 0.6ms | ActiveRecord: 0.0ms | Allocations: 1027)
```

We can see that none of the requests took longer than a few ms to be responded. So, it makes me suspect that it's related with a bad host to container network performance as it's described in the link below:

- https://github.com/docker/for-mac/issues/3497

To confirm that's related to the host-container network. I decided to do benchmarking inside the discourse container:

```console
$ docker-compose exec discourse bash
$  install_packages apache2-utils
$ ab -n 100 -c 10 http://127.0.0.1:3000/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient).....done


Server Software:        nginx/1.18.0
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        6003 bytes

Concurrency Level:      10
Time taken for tests:   0.514 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      719201 bytes
HTML transferred:       600300 bytes
Requests per second:    194.57 [#/sec] (mean)
Time per request:       51.395 [ms] (mean)
Time per request:       5.139 [ms] (mean, across all concurrent requests)
Transfer rate:          1366.58 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    26   45   6.8     43      65
Waiting:       26   45   6.7     43      63
Total:         27   45   6.8     43      65

Percentage of the requests served within a certain time (ms)
  50%     43
  66%     45
  75%     47
  80%     51
  90%     59
  95%     59
  98%     60
  99%     65
 100%     65 (longest request)
```

As you can see, very good results were obtained, so I suspect the issue might be related with the Docker networking.

**Comment by haozige90** [comment]
Same issue +1! My OS is Ubuntu 18.04.5 LTS.

My discourse container logs are same as yours, however if you take a look at logs in real time, you can find some strange stuck.
```
discourse_1   | Completed 200 OK in 5ms (Views: 1.9ms | ActiveRecord: 0.0ms | Allocations: 1566)
discourse_1   | Completed 200 OK in 13ms (Views: 1.7ms | ActiveRecord: 0.0ms | Allocations: 1567)
discourse_1   | Completed 200 OK in 28ms (Views: 3.3ms | ActiveRecord: 0.0ms | Allocations: 1027)
discourse_1   | Completed 200 OK in 4ms (Views: 1.6ms | ActiveRecord: 0.0ms | Allocations: 1027)

[STUCK POINT]Stuck Here for a while and output below logs at once!!!

discourse_1   | Completed 200 OK in 2ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 1027)
discourse_1   | Completed 200 OK in 2ms (Views: 0.6ms | ActiveRecord: 0.0ms | Allocations: 1027)
```

**Comment by persevereVon** [comment]
Hi @juan131 

Thanks for your inspection.

My OS is Linux, and this is a benchmarking outside the discourse container:

```
❯ ab -n 100 -c 10 http://discourse.local/
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking discourse.local (be patient).....done


Server Software:        nginx/1.18.0
Server Hostname:        discourse.local
Server Port:            80

Document Path:          /
Document Length:        6074 bytes

Concurrency Level:      10
Time taken for tests:   0.316 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      732301 bytes
HTML transferred:       607400 bytes
Requests per second:    316.23 [#/sec] (mean)
Time per request:       31.622 [ms] (mean)
Time per request:       3.162 [ms] (mean, across all concurrent requests)
Transfer rate:          2261.50 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    17   21   9.5     19     106
Waiting:       17   21   9.5     19     106
Total:         17   21   9.5     19     106

Percentage of the requests served within a certain time (ms)
  50%     19
  66%     20
  75%     20
  80%     21
  90%     24
  95%     34
  98%     40
  99%    106
 100%    106 (longest request)
```

It does not seem like a Docker networking issue.

**Comment by juan131** [comment]
Hi @persevereVon 

I did the benchmarking from the host (as you did) and you're right, no issues find on my side neither:

```console
$ ab -n 100 -c 10 http://foo.bar.com/
...

Concurrency Level:      10
Time taken for tests:   0.497 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      718801 bytes
HTML transferred:       599900 bytes
Requests per second:    201.17 [#/sec] (mean)
Time per request:       49.709 [ms] (mean)
Time per request:       4.971 [ms] (mean, across all concurrent requests)
Transfer rate:          1412.12 [Kbytes/sec] received
...
```

Also as @haozige90 suggested, I also reloaded the page (disabling browse cache) while inspecting the logs in real time. And... I could reproduce that sometimes (like 1 of each 8 requests more or less) the logs are frozen and they appeared at once provoking the TTFB to be slow.

I also inspected in real time the use of cpu/memory and it's not a problem of resources. 

It could be related to some internal "cron" Discourse is using that blocks attending the server requests for a few seconds, or probably sth we're misconfiguring in Passenger. In any case, this requires further investigation so I'll open a task to investigate what's going on.

**Comment by persevereVon** [comment]
Thanks for your reply. @juan131

**Comment by haozige90** [comment]
![image](https://user-images.githubusercontent.com/18454029/104581997-4d7e3080-569a-11eb-90dd-ebc00ed341bb.png)

@juan131 
As picture show above, request stuck in Passenger's requests queue.

**Comment by juan131** [comment]
Thanks so much @haozige90 !!! I'll add that info the task so it's analyzed.

**Comment by haozige90** [comment]
@juan131 
Thanks Juan.
By the way, may I know your next operation plan for this issue?

**Comment by juan131** [comment]
@haozige90 I created the task, with all the information on this issue, and added it to our backlog. I can't provide you any ETA, but now our eng. manager team will prioritise it and, depending on this, it will be assigned to one of our engineers during the following weeks.

**Comment by dscataglini** [comment]
Have you guys tried to disable long polling? We discovered the setup doesn't do well with it enabled (default is on).
I created an issue explaining it https://github.com/bitnami/bitnami-docker-discourse/issues/177

**Comment by juan131** [comment]
Thanks for bringing this up @dscataglini 
My colleague @andresbono just responded you in the issue you created. As he said, we'll have to properly investiga this in the task we created.

**Comment by LM1LC3N7** [comment]
Hello all, 

I have the same issue, even with adding a new environment parameter: UNICORN_WORKERS=16 (two per core as I can read). 

Still same issue, some requests are very very slow, sometimes when I add a new answer to a topic, sometimes when I reload, etc. 

I just disabled the long pooling option, and will update here if it changes anything.

**Comment by LM1LC3N7** [comment]
Ok, thank you @dscataglini, there is a huuuuge difference, now it is blazing fast ⚡

**Comment by juan131** [comment]
Thanks for sharing your experience @LM1LC3N7 

It seems that most users that disabled long polling got a better performance. We have an internal task to investigate this properly in our backlog, but we didn't have the chance to work on that yet.

We'll keep you updated about anything we discovered.

**Comment by lukechilds** [comment]
Just checking in, we also hit this issue. Site was fine with ~3 active users, went up to ~10 active users and performance nose dived. TTFB would randomly go to ~20s and then back to normal speeds.

Disabling long polling didn't seem to immediately resolve the issue, but after about 10 minutes I restarted all the contianers and it's been much better since.

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

Unfortunately we have not made progress for this specific issue, but now it will be a lot easier if you decide to use another Rails server like Puma with the Bitnami Discourse image. Any contributions in that direction are welcome and we'll be glad to help with the release.

**Comment by geniusshiun** [comment]
> Hello all,
> 
> I have the same issue, even with adding a new environment parameter: UNICORN_WORKERS=16 (two per core as I can read).
> 
> Still same issue, some requests are very very slow, sometimes when I add a new answer to a topic, sometimes when I reload, etc.
> 
> I just disabled the long pooling option, and will update here if it changes anything.

How to disable the long pooling?

**Comment by juan131** [comment]
Hi @geniusshiun 

Simply go to the Discourse site settings and disable the long polling option:

![Screenshot 2021-09-20 at 08 49 32](https://user-images.githubusercontent.com/6740773/133965247-9a4eada4-a8ee-4e27-bca7-32d478c93e11.png)

**Comment by Mist-Hunter** [comment]
I'm noticing intermittent lag that seems to correlate with these log events:
https://github.com/bitnami/bitnami-docker-discourse/issues/59#issuecomment-880945259

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by belmeopmenieuwesim** [comment]
Still an issue. Only experiencing this with the bitnami discourse image. When I use the official `discourse/base:release` docker image I do not have any performance issues.
