### ISSUE TITLE
No Sidekiq?

### ISSUE THREAD

**Issue by lejeczek** [bitnami/bitnami-docker-discourse#174]
I'm about to have my first foray into Discourse with Bitnami so I look at Bitnami's docs which talk of Sidekiq but that Sidekiq by Bitnami is nowhere to be found in Docker Hub or I have gone blind. Which one is it?

regards, L.

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Sidekiq is included in the Discourse image, there is not a separate image for that, see https://github.com/bitnami/bitnami-docker-discourse/blob/de6181645885c98f9222796ed0e7b80525cd9aeb/2/debian-10/Dockerfile#L14

When deploying Discourse using docker-compose, there is deployed a sidekiq container using the bitnami/discourse image with a custom command, see https://github.com/bitnami/bitnami-docker-discourse/blob/de6181645885c98f9222796ed0e7b80525cd9aeb/docker-compose.yml#L34

In the same way, you can deploy it manually (without docker-compose orchestrating the containers), you can find the instructions in this section of the README: https://github.com/bitnami/bitnami-docker-discourse#run-the-application-manually
