### ISSUE TITLE
[feature] Preserve `public/assets`  in /bitnami volume to speed up the assets:precompile step

### ISSUE THREAD

**Issue by ArcticSnowman** [bitnami/bitnami-docker-discourse#175]
**Description**
Deploying discourse using the Bitnami helm chart.  The startup time for the pod is a long time spent precompiling the assets.  

I was wondering if there would be a time saving preserving the `public/assets` directory on the `/bitnami` volume between POD starts?   

And when we come to patch the cluster nodes, not sure having the POD take 20+ minutes to start is acceptable.

**Comment by miguelaeh** [comment]
Hi @ArcticSnowman ,
Discourse takes some time the first time it is installed. Once it is installed and persisted it should not take so long. What happens in pod restarts? Does it take the same amount of time?

**Comment by ArcticSnowman** [comment]
currently with the bitnami docker/helm setup that directory is not being persisted, so on restart (say by kubectl delete of the pod) the directory `public/assets` is empty.

Here is a screen shot of the directory inside a pod after a pod is restarted.

![image](https://user-images.githubusercontent.com/13837922/108519789-fae6f400-7297-11eb-9334-51d75170cafc.png)

**Comment by ArcticSnowman** [comment]
I wonder if my issue are that I can a PostgreSQL 12 running...

**Comment by miguelaeh** [comment]
Hi @ArcticSnowman ,
I was referring to the default volume that is persisted, which stores the configuration after thee installation.
As you said, `public/assets` is not stored by default, you can give a try to you suggestion by mounting an `extraVolume` https://github.com/bitnami/charts/blob/91dbd11bcdd9284029e5857235b0b7b0ddade1b5/bitnami/discourse/values.yaml#L166
