### ISSUE TITLE
Connection with 'bn_discourse' user is unsuccessful

### ISSUE THREAD

**Issue by lejeczek** [bitnami/bitnami-docker-discourse#176]
Hi. A novice here, to all this, so go easy.
I follow Bitnami's guide for Discourse and all seems fine except that last bits. I get these errors from Discourse container.
...
postgre INFO  Found PostgreSQL server listening at localhost:5432
postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful

I do not want to guess and thought I better ask - is this something that the guide does not mention, does not cover and us 'first graders' should just figure out (ways to setup discourse <=> postgresql) or there is an issue in fact?

many thanks, L.

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @lejeczek ,
I guess you are using docker-compose, just copying the docker-compose from the repo it should start. Could you share your docker-compose?

**Comment by lejeczek** [comment]
Hi.
I do all this with 'podman' and the setup seems to work okey, except that bit.
When I inspect Bitnami container I see this:
...
                "TERM=xterm",
                "container=podman",
                "SMTP_HOST=",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=",
                "DISCOURSE_POSTGRESQL_NAME=bitnami_application",
                "DISCOURSE_SKIP_INSTALL=no",
                "BITNAMI_IMAGE_VERSION=2.6.1-debian-10-r17",
                "DISCOURSE_PORT=3000",
                "DISCOURSE_EMAIL=user@example.com",
                "DISCOURSE_PASSENGER_SPAWN_METHOD=direct",
                "OS_FLAVOUR=debian-10",
                "REDIS_HOST=localhost",
                "OS_ARCH=amd64",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=",
                "DISCOURSE_PORT_NUMBER=3000",
                "DISCOURSE_POSTGRESQL_PASSWORD=bitnami1",
                "POSTGRESQL_ROOT_USER=postgres",
                "SMTP_TLS=yes",
                "DISCOURSE_HOST=discourse",
                "POSTGRESQL_PORT_NUMBER=5432",
                "POSTGRESQL_ROOT_PASSWORD=",
                "DISCOURSE_POSTGRESQL_USERNAME=bn_discourse",
                "REDIS_PORT_NUMBER=6379",
                "DISCOURSE_HOSTNAME=127.0.0.1",
                "OS_NAME=linux",
                "SMTP_PASSWORD=",
                "BITNAMI_APP_NAME=discourse",
                "SMTP_PORT=",
                "DISCOURSE_USERNAME=user",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=",
                "REDIS_PASSWORD=",
                "SMTP_USER=",
                "DISCOURSE_SITENAME=My site!",
                "SMTP_AUTH=login",
                "POSTGRESQL_HOST=localhost",
                "DISCOURSE_PASSWORD=bitnami123",
                "HOME=/root",
                "HOSTNAME=8kubernode1"

My guess is, and guessing is all I can do at this point, that PostgreSQL was not setup up in a way that it's ready for Discourse?
thanks, L.

**Comment by lejeczek** [comment]
I just found that docker compose you mention of and can see that some env vars were not passed, set up.
I wonder if it's something that got lost in translation as a one-off or something between podman and docker which will always "malfunction" like that...
ps. I could not find forum on Bitnami's website for Discourse. When I choose containers I get pointed here. Is here a forum somewhere for stuff like I asked about?

**Comment by miguelaeh** [comment]
Hi @lejeczek ,
>I wonder if it's something that got lost in translation as a one-off or something between podman and docker which will always "malfunction" like that.

I am not sure about what you mean with this could you clarify?

> ps. I could not find forum on Bitnami's website for Discourse. When I choose containers I get pointed here. Is here a forum somewhere for stuff like I asked about?

For containers and helm charts we provide the support and accept PRs on GitHub and we provide the documentation on the READMEs repos
