### ISSUE TITLE
Enabling Long polling causes requests to queue

### ISSUE THREAD

**Issue by dscataglini** [bitnami/bitnami-docker-discourse#177]
**Synopsis**
Enabling long polling causes stuttering performance in discourse especially with multiple users on the site. 
This happens for many reasons:

- you can't multithread in the free passenger
-  all the passenger processes are kept occupied by the requests to the MessageBus. You can support as many users as passenger processes, because each client will have a long poll request that will keep the passenger process unavailable 25 seconds at the time. This causes all other requests to be queued and to have to wait for the 25 seconds poll to expire.
- There might be a misconfiguration in the nginx passenger setup for the `/message-bus/` path. 

**Description**
We've deployed the bitnami discourse docker to a staging environment using rancher.
We seem to be unable to use the long polling feature.
We're using a container with 4 GB of ram and we scaled up to 16 passenger processes.
When testing for load, we discovered that even 8 or so users would overwhelm the 16 passengers.
Discourse uses long polling to the `/message-bus/<someid>/poll` path. By default the poll expires every 25 seconds and a new poll is instantiated for each browser client.
When running passenger-status we could observe all the processes being taken and occupied for the length of the 25 seconds and any other request will be queued (0-20 queued requests)
These queued requests would clear and be processed only when 1 or more long poll would expire and a new one would be instantiated.

Do you have any idea on how to resolve this issue?
The idea would be to allow long polling with chunked encoding for the message-bus component.

The recommended setting in nginx is the following:

```
location /message-bus/ {
  ...
  proxy_http_version 1.1;
  proxy_buffering off;
  ...
}
```

I'm not sure what this correspond in passenger settings lingo or if this is part of the problem. What I know is the bitnami docker image is not usable for production purposes as is.

Btw, for reference the discourse nginx.conf sample file reads as follow:
```
# we need buffering off for message bus
    location /message-bus/ {
      proxy_set_header X-Request-Start "t=${msec}";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $thescheme;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_pass http://discourse;
      break;
    }
```

**Steps to reproduce the issue:**
Visit the discourse site with as a couple more browsers/users/tabs than passenger processes. 
The default image has a 5 processes, so open 7 tabs. You then can just click around on tab/windows #6 and #7 to experience the site coming to a crawl. Anything you click will get a loading spinner that will go away only when the poll requests expire on a different tab.

We wrote a capybara/selenium script that would visit the a page per second. ie: visit latest, sleep 1 second, visit a topic, sleep, visit a different page, sleep, etc. Unfortunately I can't share the full script because it's it's not a standalone thing.
Manually you can loop through all the tabs and hit refresh and you'll see the spinning loading icons goes away after a long while. Even though the logs are saying that all the requests are super fast

```
root@9b0688e63cf7:/opt/bitnami/discourse# tail -f log/production.log | grep 'Completed'
Completed 200 OK in 21ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 1915)
Completed 200 OK in 21ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 1943)
Completed 200 OK in 18ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 2005)
Completed 200 OK in 190ms (Views: 73.7ms | ActiveRecord: 0.0ms | Allocations: 21992)
...
```

On a terminal you ssh into the discourse container and run `while true; do sleep 1; bundle exec passenger-status; done` You'll see the queue growing and the `last used` value of the processes increase until they hit 25 seconds, at which time a new poll is started, the queue empties, and it starts all over again.

This means that with the default setup (long polling is enabled by default) you can have only as many concurrent users as many passengers processes enabled. A typical process is about 220Mb which means a 2GB ram machine can handle only about 9 concurrent users with long polling enabled.

We haven't tested using puma as it provides multi threading out of the box, something that passenger doesn't provide without an enterprise license. 
Is there a particular reason why this image uses passenger rather than thin/puma/etc?

**Version**

- Output of `docker version`:

```
```
docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
``````

- Output of `docker info`:

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 27
  Running: 20
  Paused: 0
  Stopped: 7
 Images: 46
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.846GiB
 Name: docker-desktop
 ID: DR2D:V774:7Q4M:MER2:RDOT:BOAQ:KTEF:OW4B:JZJ5:ZLR5:SYZ5:VFPN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by andresbono** [comment]
Hi @dscataglini, thanks for opening this issue. We can partially reproduce your issue, I'd say it is the same than #172. We will need to continue investigating it to get a better understanding of any possible optimizations that we can do on the container.

I will add the valuable information of this issue into our internal task.

Please, let us know if you have any news on your side.

**Comment by dscataglini** [comment]
Do you know why the image uses passenger rather than puma? or something else?

**Comment by andresbono** [comment]
Hi @dscataglini, in Bitnami, we standarized on Passenger for Ruby applications. But as part of our internal task, we are going to evaluate other options.

**Comment by opensorceror** [comment]
@dscataglini @andresbono Just wondering, what are the implications of disabling long-polling to a production Discourse instance?

**Comment by Mauraza** [comment]
Hi @opensorceror,

could you check this https://www.rubydoc.info/gems/message_bus?

**Comment by opensorceror** [comment]
@Mauraza Thanks. I do know the differences between long polling and short polling in general, but my question was about specifically how disabling long polling affects a _production Discourse instance_. I'm not too familiar with the details of Discourse internals, so I was hoping to maybe get an answer here.

I do notice something interesting on the page you linked though:

> MessageBus uses long polling which needs to be configured in Passenger  
For passenger version < 5.0.21, add the following to `application.rb`:

```ruby
PhusionPassenger.advertised_concurrency_level = 0
```

> For passenger version > 5.0.21, add the following to `nginx.conf`:
```nginx
location /message-bus {
  passenger_app_group_name foo_websocket;
  passenger_force_max_concurrent_requests_per_process 0;
}
```

Could you confirm which version of Passenger is used by the Bitnami Discourse image version `2.6.3-debian-10-r20`, so that I can try this change? (Surprisingly, I couldn't find this by looking at Bitnami repositories.)

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). This version uses initialization scripts located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

Unfortunately we have not made progress for this specific issue, but now it will be a lot easier if you decide to use another Rails server like Puma with the Bitnami Discourse image. Any contributions in that direction are welcome and we'll be glad to help with the release.

**Comment by denysvitali** [comment]
We had the same issue. Disabling long-polling was definitely the fix, thanks!

**Comment by Mauraza** [comment]
Hi @denysvitali,

Thanks for the information. Could you tell us what version are you using?

**Comment by denysvitali** [comment]
The latest one: `2.7.0-debian-10-r4`

**Comment by geniusshiun** [comment]
> We had the same issue. Disabling long-polling was definitely the fix, thanks!

Please tell me how to disable long-polling, thank you.

**Comment by denysvitali** [comment]
Hey @geniusshiun , if I'm not mistaken you can find the option in the admin settings

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
