### ISSUE TITLE
Readme: Sidekiq volume is never used

### ISSUE THREAD

**Issue by r0l1** [bitnami/bitnami-docker-discourse#179]
Quote from the Readme:

> The above examples define docker volumes namely postgresql_data, redis_data, sidekiq_data and discourse_data. The Discourse application state will persist as long as these volumes are not removed.

However the docker compose file shares the discourse_data volume with the sidekiq container. Is that correct?

**Comment by alvneiayu** [comment]
hi @r0l1 

This is correct, sidekiq needs several files (configuration files, etc) from discourse. So, discourse_data volume must be shared with sidekiq container.

I hope that I have helped you. Let me know if I can help you with something else.

Thanks

Álvaro

**Comment by r0l1** [comment]
Thank you for the information. So the Readme is incorrect...

**Comment by alvneiayu** [comment]
hi @r0l1 

Yes, I already created an internal PR to fix the TIPO.

thanks a lot for reporting the issue.

Álvaro

**Comment by r0l1** [comment]
Great! Thanks for the fast support. Please feel free to close this issue.
