### ISSUE TITLE
Feature Request - Discourse Cluster mode (Running in multiple containers)

### ISSUE THREAD

**Issue by LM1LC3N7** [bitnami/bitnami-docker-discourse#182]
Hello,

Newby help needed :)

I did not find how to deploy Bitnami Discourse in multi container configuration (issue similar to https://github.com/bitnami/bitnami-docker-discourse/issues/93).
I search for existing issues and in the Readme file, and I did not understand how to do it.

* Should I create only another discourse container using the same volume? What about "race conditions" and everything?
* Should Postgresql also be duplicated?

I read that redis should not be duplicated, but nothing about how to configure either containers or discourse to run in multi container mode.

Thanks all in advance for helping me :)

**Comment by juan131** [comment]
Hi @LM1LC3N7 

I saw you also commented in a different thread, did you already solve your issue?

**Comment by LM1LC3N7** [comment]
The issue about plugins not working (https://github.com/bitnami/bitnami-docker-discourse/issues/163#issuecomment-828174095) is solved with a workaround, but not a permanent solution.

About the error I get with sidekiq not working (https://github.com/bitnami/bitnami-docker-discourse/issues/181), yes the issue is solved and closed.

**Comment by juan131** [comment]
Hi @LM1LC3N7 

> The issue about plugins not working (#163 (comment)) is solved with a workaround, but not a permanent solution.
>
> About the error I get with sidekiq not working (#181), yes the issue is solved and closed.

Thanks for the information! I'm glad you could solve the other issues.

---

Regarding your question here: clustering for Discourse it's not something we support out-of-the-box. One thing that you can try is using a NFS server to provide the volumes you mount at `/bitnami` in the Discourse & Discourse Sidekiq container. This way, the data between the different Discourse containers will be synchronised.

This is the approach we suggested in other applications such as WordPress. For instance, in the link below you can consult a guide about how to do so using WP + Helm charts for Kubernetes:

- https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by LM1LC3N7** [comment]
Thank you for your answer. I understand how tricky it can be.

Without high availability consideration but with performance consideration, is it possible to start two "frontend" containers as the official discourse docker installation seems to allows?

**Comment by juan131** [comment]
Hi @LM1LC3N7 

I guess you need to find a way to synchronize data between these frontend containers to avoid race conditions. Could you share the reference to the "official" docs where they talked about multi-containers?

**Comment by LM1LC3N7** [comment]
Source: https://github.com/discourse/discourse_docker#single-container-vs-multiple-container

### Single Container vs. Multiple Container

The samples directory contains a standalone template. This template bundles all of the software required to run Discourse into a single container. The advantage is that it is easy.

The multiple container configuration setup is far more flexible and robust, however it is also more complicated to set up. A multiple container setup allows you to:

- Minimize downtime when upgrading to new versions of Discourse. You can bootstrap new web processes while your site is running and only after it is built, switch the new image in.
- Scale your forum to multiple servers.
- Add servers for redundancy.
- Have some required services (e.g. the database) run on beefier hardware.

If you want a multiple container setup, see the `data.yml` and `web_only.yml` templates in the samples directory. To ease this process, `launcher` will inject an env var called `DISCOURSE_HOST_IP` which will be available inside the image.

WARNING: In a multiple container configuration, *make sure* you setup iptables or some other firewall to protect various ports (for postgres/redis).
On Ubuntu, install the `ufw` or `iptables-persistent` package to manage firewall rules.

**Comment by juan131** [comment]
Hi @LM1LC3N7 

I created a task to investigate what can we do in our side to provide support for this multi-container architecture since I can confirm this is something we do not support right now. We'll keep this thread updated about our progress.

**Comment by LM1LC3N7** [comment]
Thank you for the update ! 
This would be great to have in order to update the forum without downtime and maybe gain performances.

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). This version uses initialization scripts located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

If you want to add support for cluster mode, it should be a lot easier if you want to contribute such changes. Any related PR is welcome and we'll be glad to help with the release.

**Comment by LM1LC3N7** [comment]
Hello @marcosbc 
Thank you for your answer. 
I am quite new to Discourse for now, how this would let me enable a cluster mode?

**Comment by marcosbc** [comment]
Unfortunately cluster mode is not supported yet. However now the initialization scripts are open source and you are free to contribute the necessary changes to support it, via a pull request.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
