### ISSUE TITLE
Redis & pgSQL externally - 'postInstallation': Failed to report error:

### ISSUE THREAD

**Issue by lejeczek** [bitnami/bitnami-docker-discourse#184]
**Description**
It's pretty standard what I'm doing I assume:

_GLOBAL="\
-e NAMI_LOG_LEVEL=trace \
-e DISCOURSE_USERNAME=adm \
-e DISCOURSE_PASSWORD=2020 \
-e DISCOURSE_EMAIL=me@some.tet \
-e DISCOURSE_SITENAME=some.tet \
-e DISCOURSE_HOSTNAME=some.tet \
-e POSTGRESQL_HOST=10.88.2.1 \
-e POSTGRESQL_ROOT_USER=discourse \
-e POSTGRESQL_ROOT_PASSWORD=9897 \
-e POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse \
-e POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=9897 \
-e POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse \
-e DISCOURSE_POSTGRESQL_NAME=discourse \
-e DISCOURSE_POSTGRESQL_USERNAME=discourse \
-e DISCOURSE_POSTGRESQL_PASSWORD=9897 \
-e REDIS_HOST=10.88.2.1 \
-e REDIS_PASSWORD=9897 \
"
That in terms of ENV. 
I find these in logs:
...
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-h10.88.2.1,-ddiscourse,-Udiscourse,-cCREATE EXTENSION IF NOT EXISTS hstore;
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-h10.88.2.1,-ddiscourse,-Udiscourse,-cCREATE EXTENSION IF NOT EXISTS pg_trgm;
discour INFO  Migrating database...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,db:migrate
Error executing 'postInstallation': Failed to report error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? 2 ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? subscribe failed, reconnecting in 1 second. Call stack /opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/redis-4.2.5/lib/redis/client.rb:132:in `call'

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alvneiayu** [comment]
hi all

Closing this issue. This issue will be fixed [here](https://github.com/bitnami/bitnami-docker-discourse/issues/183)

Thanks

Álvaro
