### ISSUE TITLE
Automatic backups not visible - Local Storage - written to /opt in sidekiq

### ISSUE THREAD

**Issue by alanbchristie** [bitnami/bitnami-docker-discourse#185]
**Description**
I'm deploying a `discourse` and `sidekiq` container in Kubernetes and using **Local Storage** for backups. Automatic backups (even through they're successful) are not visible on the Backups page. But manual backups are visible on the Backups page.

...because...

The automatic backups are written to the sidekiq container's local  directory `/opt/bitnami/discourse-sidekiq/public/backups/default` whereas manual backups are written to a common/shared directory `/bitnami/discourse`.

**Steps to reproduce the issue:**

1. Deploy discourse (including separate sidekiq container) to Kubernetes
2. Use 'built-in' Local Storage for backups
3. Trigger a manual backup - it becomes visible in the backups page
4. Setup an automatic backup
5. The backup runs at the desired time but it is not visible in the backups page, instead written to a local directory in the sidekiq container

**Describe the results you received:**

Instead of going into the common volume shared between sidekiq and discourse (`/bitnami/discourse/public/backups/default`) the automatic backups are written to `/opt/bitnami/discourse-sidekiq/public/backups/default` and are therefore not displayed on the backups page in the UI for recovery.

**Describe the results you expected:**

I expect automatic backups (when using Local Storage) to be visible and selectable in the UI.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Deployed to Kubernetes, disourse and sidekiq running as separate containers in the same Pod
- The containers share a volume mounted at `/bitnami/discourse`

**Version**

- Base container image
The Kubernetes Pods are based on the docker image: -

```
bitnami/discourse:2.6.1-debian-10-r10`
```

- Output of `docker info`:

```
(n/a)
```

- Output of `docker-compose version` (if applicable):

```
(n/a)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- Kubernetes v1.17

**Comment by alanbchristie** [comment]
I initially raised this on the Discourse community chat...

- https://meta.discourse.org/t/automatic-backups-local-storage-not-visible-in-ui/189130/3

...but it feels like it's a binami/docker-related installation issue. i.e. "automatic" "local storage" backups don't appear to work as expected - i.e. they aren't visible in the backups page.

**Comment by migruiz4** [comment]
Hi @alanbchristie ,

Thank you for reporting this issue. I was able to reproduce your issue and we are working on a solution.

I will let you know as soon as we fix it.

**Comment by JustinAvaLabs** [comment]
Also seeing this issue, preventing us from migrating our discourse into a new environment

**Comment by alanbchristie** [comment]
@JustinAvaLabs ... If you can access the sidekiq `/opt/bitnami/discourse-sidekiq/public/backups/default` directory, and `/bitnami/discourse/public/backups/default` is mounted in both the sidekiq and discourse containers, you can copy/move the file to the "correct" location inside the sidekiq container (replicating the desired behaviour) and then the backups should be visible and selectable via the main discourse backups page. I'm using this "manual" step to get around the fault for now.

**Comment by JustinAvaLabs** [comment]
@alanbchristie  Thanks for the help!  I ended up using S3 instead and it seems to work fine.  

Cheers

**Comment by migruiz4** [comment]
Hi!

I forgot to mention we implemented a change so discourse-sidekick also stores the backups in `/bitnami/discourse/public/backups/`.

Could you please confirm if when using the latest version of the discourse image your issue persists?

**Comment by alanbchristie** [comment]
So that'll be `2.6.7-debian-10-r2`?

**Comment by migruiz4** [comment]
Yes, indeed the change was applied on May 8th and all releases from `2.6.6-debian-10-r8` should include the fix.

**Comment by alanbchristie** [comment]
OK - we're now using `bitnami/discourse:2.6.7-debian-10-r2` and that's working for us. Thanks - closing the issue.

**Comment by migruiz4** [comment]
Thanks for the feedback!

I'm glad the changes fixed your issue.
