### ISSUE TITLE
Moving domain name

### ISSUE THREAD

**Issue by noplanman** [bitnami/bitnami-docker-discourse#187]
**Description**

I'm looking at moving my Discourse instance to a new domain and wanted to ask what the best method would be, using this image. Thanks!

**Additional information you deem important**

I found this guide on the official Discourse forum, but am not sure how to make it work with this image:
https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098

**Comment by javsalgar** [comment]
Hi,

In order to understand the issue. You want to deploy a new container and migrate all the data there, is that correct? You could deploy a new container with DISCOURSE_HOSTNAME set as the domain you want, and then use the backup and restore procedures from one to the other. Would that work for you?

**Comment by noplanman** [comment]
Thanks for your message @javsalgar 

Does renaming the `DISCOURSE_HOSTNAME` automatically take care of all text replacements and post rebaking as described here?
https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098#replace-all-instances-of-the-old-name-with-the-new-name-in-posts-6

I'll need to give this all a try and play around a bit before doing the proper migration.

**Comment by javsalgar** [comment]
Hi,

Right now, the DISCOURSE_HOSTNAME will be considered in the first run. Probably, any changes in the database will need to be done manually at the moment. However, please try it and let us know anything we can improve in the image.

**Comment by noplanman** [comment]
Thanks @javsalgar, so far it's not as "flowy" as I'd hoped.

I tried exporting the existing site using the Discourse Backup feature and then uploading it to the new one (which is the same base version with a single admin user to get access).
Trying the restore there gives me an error though, saying it can't extract the backup file I think.

What does seem to work though:
1. Make backup using Discourse Backup and download it
2. Set up new instance with the same version
3. Upload the backup to the server and extract it
4. Move uploads folder to it's place
5. Delete the DB and import the `dump.sql` from the backup
6. Works!

As a step 7 is to now update the Discourse container to the latest version and let the migration take care of and steps required.

Need to do more testing, but initially it does seem to update the hostname internally, not sure if it also rebakes all posts or not, haven't had time to properly check yet.

I'll keep you posted and make a more ✨ pretty ✨  list of steps required when I'm finished with the live migration.

**Comment by javsalgar** [comment]
Thank you so much for the detailed report! :D

**Comment by noplanman** [comment]
Ok, so here's what I did and it's worked like a charm 😊 

1. Set Discourse to "Read-Only"
1. Make backup of docker volumes and move them to new server (i didn't use the Discourse backups, as they don't contain everything, like plugins)
1. Set up new instance with latest version of the containers (using new hostname in environment variable)
1. Stop all containers on new instance and replace volume data with the backed up volumes
1. Start containers and let migration go through
1. Rebake all posts (`rake posts:rebake`)
1. Works! 🎉 

I was hoping a simple Discourse export-import would do the trick, but it didn't. Copying the volume data itself worked out perfectly.
