### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by sswing11** [bitnami/bitnami-docker-discourse#189]
Thanks for these containers. Much appreciated.

This isn't so much an issue as it is a request for support. I need a better understanding of where the config files are located because I cannot get SMTP service running via SparkPostmail. I've tested the SMTP connection via SSL from the root_discourse_1 container and confirmed that it the handshake works and I've tested the credentials to Sparkmail and they are accurate but I'm missing a config in either app.yml or discourse.conf.

The problem is that I cannot located either file in your Discourse container. I have tried using the -find command from the root of the container for both files and neither is located.

Please assist with helping me understand what your file structure looks like. In your install guides for the non-container version, you point to the htdocs folder. Does that exist somewhere in the container? Would be doc to know.

**Comment by Mauraza** [comment]
Hi @sswing11,

Did you check this https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration?

**Comment by sswing11** [comment]
Yes. Several times. It gives no indication of answering the question that I posed...

**Comment by Mauraza** [comment]
Hi @sswing11,

the configuration file is `/discourse-inputs.json`. Could you try to send it manually from the container by following this guideline? https://www.stevenrombauts.be/2018/12/test-smtp-with-telnet-or-openssl/

**Comment by marcosbc** [comment]
@sswing11 You can find `discourse.conf` in `/opt/bitnami/discourse/conf/discourse.conf`.  The `app.yml` should be inside the same folder.

Note that those files are created during initialization. You can find the related logic here (*): https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libdiscourse.sh#L228

(*): FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). This version uses initialization scripts located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).
