### ISSUE TITLE
Discourse version 2.7.0

### ISSUE THREAD

**Issue by noplanman** [bitnami/bitnami-docker-discourse#190]
Discourse 2.7.0 was released almost a week ago now and I was wondering when there will be an update to this image.

Is there an easy way to manually upgrade Discourse directly within the container or is it pretty much locked to the version provided by Bitnami?

**Comment by rafariossaa** [comment]
Hi,
  Discourse will be released soon, however I can not provide an ETA for this.

  Upgrading inside the container would be possible but it is not an easy task. It would involve backups, upgrade and creating a new image. I would suggest you to wait until the new container image is released to have a smoother transition, that will also make easier to upgrade to future versions.

**Comment by noplanman** [comment]
I just noticed that `2.7.0-debian-10-r2` is already available, is it safe for production?

**Comment by rafariossaa** [comment]
yes, it must be. I mean that version is not a development or beta release.

**Comment by noplanman** [comment]
Have upgraded without any problems 👍
