### ISSUE TITLE
Allow empty SMTP credentials

### ISSUE THREAD

**Issue by denysvitali** [bitnami/bitnami-docker-discourse#192]
Connecting to an SMTP server shouldn't imply providing any credentials, since an user might want to use no authentication at all. This line should be rewritten to support this use case:

https://github.com/bitnami/bitnami-docker-discourse/blob/6f0941b03385f891687ea500ebfab171d96792c6/2/debian-10/rootfs/opt/bitnami/scripts/libdiscourse.sh#L101-L103

**Comment by marcosbc** [comment]
Hi @denysvitali, thanks for reporting this. You are indeed correct. We are working on a fix and will let you know once the fix is released (hopefully today or tomorrow).

**Comment by denysvitali** [comment]
No problem. I actually already fixed the issue myself by excluding the check for the two empty variables :)

**Comment by marcosbc** [comment]
Hi, just wanted to let you know that we just released `2.7.1-debian-10-r0` which fixes these issues.

**Comment by denysvitali** [comment]
Awesome thanks!
