### ISSUE TITLE
DISCOURSE_SMTP_AUTH default value

### ISSUE THREAD

**Issue by kxesd** [bitnami/bitnami-docker-discourse#195]
**Description**

The default value for `DISCOURSE_SMTP_AUTH` is `yes` as [defined here](https://github.com/bitnami/bitnami-docker-discourse/blob/6f0941b03385f891687ea500ebfab171d96792c6/2/debian-10/rootfs/opt/bitnami/scripts/discourse-env.sh#L138). However in the [README.md](https://github.com/bitnami/bitnami-docker-discourse/blob/master/README.md#L342) it mentions that the default is `*login`.

In my testing `yes` did not work for sending email however when I specified `login` for `DISCOURSE_SMTP_AUTH` it worked.

The [discourse_default.conf](https://github.com/discourse/discourse/blob/master/config/discourse_defaults.conf#L86) in discourse/discourse has a default of `plain`.

Do we need to update the default value from `yes` to `login` or `plain`?

**Comment by migruiz4** [comment]
Hi @kxesd,

Thank you very much for reporting this issue. Indeed there seems to be a typo with the DISCOURSE_SMTP_AUTH definition, and also `*login` is supposed to be **login**.

Allowed values for DISCOURSE_SMTP_AUTH are `plain`, `login` or `cram_md5`.

**Comment by migruiz4** [comment]
I new version fixing the default value will be released soon.

Meanwhile, setting the environment variable `DISCOURSE_SMTP_AUTH` to `plain`,`login` or `cram_md5` should work.

**Comment by migruiz4** [comment]
Hi @kxesd!

I wanted to let you know that Discourse images starting from version `2.7.4-debian-10-r0` have this issue fixed.

 I will now close this issue, if you have any further questions please let me know.
