### ISSUE TITLE
Create admin user with API key

### ISSUE THREAD

**Issue by edwh** [bitnami/bitnami-docker-discourse#196]
Thanks for the work to make this available in Docker Compose.  I would like Discourse to start up with a pre-configured admin, which has an API key, so that the API can then be used by other containers.  Is there any way to achieve this using the available configuration?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but our initialization scripts doesn't support the creation of an API key.

**Comment by edwh** [comment]
Thanks for your reply.  I'll have to see if I can figure it out.

**Comment by rafariossaa** [comment]
If you do, please don't hesitate to share your findings.

**Comment by edwh** [comment]
@rafariossaa and googlers, this is fairly straightforward (if hacky) by adding an API key direct into the database that Discourse is using.  So you can do this without creating your own container.

I use this on CircleCI.  From https://github.com/TheRestartProject/restarters.net/blob/develop/.circleci/config.yml

```
      - run: while ! nc -z restarters_discourse 80; do sleep 1 ; done
      - run: psql -h postgresql -U postgres -c "INSERT INTO api_keys (id, user_id, created_by_id, created_at, updated_at, allowed_ips, hidden, last_used_at, revoked_at, description, key_hash, truncated_key) VALUES (1, NULL, 1, '2021-10-25 13:56:20.033338', '2021-10-25 13:56:20.033338', NULL, false, NULL, NULL, 'Restarters', 'd89e9dfacfb611fbaf004807648187ce7ed474df44dcb0ada230fab5c8dd6a5b', '9fd7');" bitnami_discourse

```

The API key is indeed SHA256 hashed without any salt, and therefore won't differ from one run to the next.  Remember that you need to add the hashed value into the DB, and then use the unhashed value as the API key.
