### ISSUE TITLE
File Upload and Image Paste is forbidden with permission denied..

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#197]
Uploading images in 2.6.4 worked perfectly... since the uprade to 2.7.5 I get the error

![image](https://user-images.githubusercontent.com/1607849/125429460-9ddcbff3-7abf-4f0f-9b1c-6f1bed61afb9.png)

What information do you need?

**Comment by rafariossaa** [comment]
Hi,
  You mentioned you upgraded discourse, does this happen in a fresh install ?.

**Comment by sbetzin** [comment]
I am using a docker-compose.yml

`
discourse:
    image: bitnami/discourse:2.7.5
    container_name: discourse
    hostname: discourse
    depends_on:
      - discourse-postgresql
      - discourse-redis
    volumes:
      - discourse:/bitnami:z
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_USERNAME=*
      - DISCOURSE_PASSWORD=*
      - DISCOURSE_EMAIL=*
      - DISCOURSE_HOSTNAME=*
      - DISCOURSE_SITENAME=*
      - DISCOURSE_REDIS_HOST=discourse-redis
      - POSTGRESQL_HOST=discourse-postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=*
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=*
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=*
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=*
      - DISCOURSE_POSTGRESQL_PASSWORD=*
      - DISCOURSE_SMTP_HOST=*
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=*
      - DISCOURSE_SMTP_PASSWORD=*
      - DISCOURSE_SMTP_PROTOCOL=tls
      - DISCOURSE_SMTP_AUTH=login
      - DISCOURSE_LOAD_MINI_PROFILER=true
      - ENABLE_PERFORMANCE_HTTP_HEADERS=true
      - LOAD_MINI_PROFILER=true
      - DEVELOPER_EMAILS=*
      - DISCOURSE_DEVELOPER_EMAILS=*
    restart: always
`

with volume

`  discourse:
    external:
      name: discourse`

**Comment by rafariossaa** [comment]
Hi,
  I think the issue here is that you need to give permissions to that external volume. Also check that the mount point is usually `/bitnami/discourse`.
  If you use:
```
    volumes:
      - './discourse_data:/bitnami/discourse'
```
  Then you will see that the permissions are:
```
$ ls -ld discourse_data
drwxrwxr-x 4 999 root 4096 Jul 19 10:03 discourse_data

$ ls -l discourse_data/
total 8
drwxrwxr-x 9  999 root 4096 Jul 19 10:03 plugins
drwxr-xr-x 4 root root 4096 Jul 19 10:03 public
```

**Comment by sbetzin** [comment]
Hi @rafariossaa,

1. I tried to map do :/bitnami/discourse but this does not work at all. The container ist not starting. I suppose this is because the container is more than 1,5 years old -> I was migrating from version to version

2. my path in the volume is: (so I think this is the /discourse from the volume mapping)
`
.../discourse/_data/discourse
`
the result of ls -ld is
`
drwxr-xr-x 4 1001 root 4096 Aug 11  2020 .
`

the result of ls -l is
`
drwxr-xr-x 9 1001 1001 4096 Nov 12  2020 plugins
drwxr-xr-x 4 1001 root 4096 Aug 11  2020 public
`

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the versions you are migrate from and to ? 
  I think it would be safe just to update the permissions, but I would like to try it first to give proper indications.
  In any case, I would recommend to make a backup of the volume before trying anything.

**Comment by sbetzin** [comment]
from 2.6.4 to 2.7.5

**Comment by rafariossaa** [comment]
Hi,
  I deployed `2.6.4` and used a volume `./discourse_data_264`, and also deployed `2.7.5` using a volume called ./discourse_data_275` and those where the owners:
```
$ ls -ln discourse_data_275/discourse
total 8
drwxrwxr-x 9 999 0 4096 Jul 21 09:06 plugins
drwxr-xr-x 4   0 0 4096 Jul 21 09:06 public

09:11 $ ls -ln ./discourse_data_264/discourse/
total 8
drwxr-xr-x 9 1001 1001 4096 Jul 21 08:57 plugins
drwxr-xr-x 4    0    0 4096 Jul 21 08:57 public
```
  Could you change the owner of the plugins directory to `999:0` by using the following command ?
```
$ sudo chmod -R 999:0 discourse_data_275/discourse
```
  Just in case, remember to make a backup of the volume before tying this.

**Comment by sbetzin** [comment]
@rafariossaa 
it says:
chmod: invalid mode: ‘999:0’

my version:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

```

**Comment by sbetzin** [comment]
It worked! I changed the discourse folder inside the _data folder to 999 (here omi?) 
```
..../datadrive/docker/volumes/discourse/_data# ls -l
total 16
drwxr-xr-x  3 1001 root 4096 Aug 11  2020 conf
drwx------ 19 1001 root 4096 Jul 21 10:27 data
drwxr-xr-x  4 omi  root 4096 Aug 11  2020 discourse
lrwxrwxrwx  1 1001 root    9 Aug 11  2020 discourse-sidekiq -> discourse
drwxr-xr-x  3 1001 root 4096 Aug 11  2020 redis

```

**Comment by rafariossaa** [comment]
> did you mean chown?
Yes, sorry.

> It worked! I changed the discourse folder inside the _data folder to 999 (here omi?)
I am happy it worked for you. I you want to get the number IDs instead of the names IDs, you can use `ls -ln`.

**Comment by sbetzin** [comment]
Can you explain why this is happening? What ist the 999 and the 1001 user? And why has it changed between the versions?

**Comment by rafariossaa** [comment]
Hi,
  Yes, in previous version the initialization of the container was handled by javascript scripts. Now as part of our standardization process the initialization is performed by bash scripts. https://github.com/bitnami/bitnami-docker-discourse#user-content-notable-changes
