### ISSUE TITLE
Unable to connect to external database

### ISSUE THREAD

**Issue by yehaotong** [bitnami/bitnami-docker-discourse#202]
I have a pgsql and redis on my sql,and I want to use this for database,but when I set the env: 
DISCOURSE_DATABASE_HOST:xxx.cluster.local(it is my pgsql host on k8s), and the database start failed,it failed log include:
Hostname postgresql.xxx.cluster.local could not be resolved, this could lead to connection issues;
ERROR ==> Could not connect to the database;
How can I use discourse to connect my pgsql

**Comment by alemorcuq** [comment]
Looking at the error it seems your container doesn't know how to resolve `postgresql.xxx.cluster.local`. Have you tried manually to reach that endpoint from a container?

**Comment by yehaotong** [comment]
this host is a postgresql pod on k8s with service hostname,and this hostname can be resolvve and connect by other pod,
Therefore, I don't know whether the environment variables are configured incorrectly. The environment variables I configured in deployment are:
DISCOURSE_HOST: discourse.xxx.com
  DISCOURSE_DATABASE_HOST: xxx.staging.svc.cluster.local
  DISCOURSE_DATABASE_PORT_NUMBER: "5432"
  DISCOURSE_DATABASE_USER: postgres
  DISCOURSE_DATABASE_NAME: postgres
  DISCOURSE_DATABASE_PASSWORD: xxx123
  DISCOURSE_REDIS_HOST: redis-xxx.staging.svc.cluster.local
  DISCOURSE_REDIS_PORT_NUMBER: "6379"
  DISCOURSE_SMTP_HOST: smtp.gmail.com
  DISCOURSE_SMTP_PORT: "587"
  DISCOURSE_SMTP_USER: xxx@gmail.com
  DISCOURSE_SMTP_PASSWORD: discourse123
  DISCOURSE_SMTP_PROTOCOL: tls

**Comment by yehaotong** [comment]
Should I use other environment variables to configure the connection information when I choose to connect the existing PostgreSQL and redis instead of the above?

**Comment by alemorcuq** [comment]
The variables are the same, you don't need to use different variables for an existing database.

I understand you are deploying this on Kubernetes as well. Can you get into the Discourse pod and try to ping your database to check there's connectivity? Can you also share the logs of the Discourse initialization?

**Comment by yehaotong** [comment]
discourse 00:41:31.64 Welcome to the Bitnami discourse container
discourse 00:41:31.68 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse 00:41:31.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse 00:41:31.75
discourse 00:41:31.85 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 00:41:31.88 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse 00:41:31.92 INFO  ==> Trying to connect to the database server
discourse 00:42:32.66 ERROR ==> Could not connect to the database server

**Comment by yehaotong** [comment]
I change the  variables name add CLIENT(POSTGRESQL_CLIENT_DATABASE_HOST), but it still hasn't come into force

**Comment by alemorcuq** [comment]
Did you try this? 

> Can you get into the Discourse pod and try to ping your database to check there's connectivity?

I can't reproduce it, so it looks like a connectivity issue on your side.

**Comment by yehaotong** [comment]
oh no,I have some error on my postgresql hostname ,I repair it  and the discourse can run now

**Comment by alemorcuq** [comment]
Nice to hear you found the issue!
