### ISSUE TITLE
Sidekiq error inside Discourse. issue with sending emails

### ISSUE THREAD

**Issue by Enekuda** [bitnami/bitnami-docker-discourse#205]
**Description**

Setup discourse site, got email working and sent test emails to a couple emails. That all worked so I tried to send an invite link to someone and it never arrived. Checked around and noticed the error on the admin panel. When i click on the sidekiq link it says it's just retries over and over and the error message is "Jobs::HandledExceptionWrapper: Wrapped ArgumentError: :arguments expected to be an Array of individual string args" which makes it seem like it's not something I've done? But I'm totally unsure.....

I have Google and checked ALL over and can't find a single thing on this.

**Steps to reproduce the issue:**

1. Install discourse via docker compose file
2. Setup email, send test emails successfully 
3. Try to send invite link or have someone sign up via the webpage

**Describe the results you received:**

Error in admin panel as shown below:
![Screenshot_20210906-200801_Chrome](https://user-images.githubusercontent.com/13653299/132270414-d824768f-4f95-442b-8133-11a220a36166.jpg)

When you click the sidekiq link it gives you this:
![Screenshot_20210906-200826_Chrome](https://user-images.githubusercontent.com/13653299/132270417-c61753b0-4350-4a8f-9945-0553850c0590.jpg)

**Describe the results you expected:**

Successful invite email sent.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version** (best I can get currently as I'm on my phone away from my network)

- Output of `docker version`:

```
20.10.5 (API: 1.41)
```

- Output of `docker info`:

```

```

- Output of `docker-compose version` (if applicable):

```
2
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker compose file inside a portainer stack, inside unraid docker.

**Comment by marcosbc** [comment]
Hi @Enekuda, could you share your docker-compose? Note that you need to set SMTP credentials not only for the `discourse` container, but also for the `discourse-sidekiq` container.

**Comment by Enekuda** [comment]
That might be why! 
I don't think there was an "smtp" area in the compose environment list for sidekiq....at least I didn't see it in the env variables to add to it, just one for the discourse.....let me add it to the sidekiq part and see if that fixes the issue, if not I will post my compose here for critique 🤣

**Comment by Enekuda** [comment]
That seemed to be it!

Maybe it's just me, but I didn't see anywhere that mentioned adding the SMTP information to the sidkiq area in the compose file? I could be totally skimming over something in the install instructions though! Wouldn't be the first time lol

**Comment by Enekuda** [comment]
That seemed to be it!

Maybe it's just me, but I didn't see anywhere that mentioned adding the SMTP information to the sidkiq area in the compose file? I could be totally skimming over something in the install instructions though! Wouldn't be the first time lol

**Comment by Tabascl** [comment]
Please, for the love of god, add this to the installation instructions!
That could have saved me a full day of troubleshooting...

**Comment by marcosbc** [comment]
Hi all, thanks for your feedback. We just updated the README to include improve the SMTP documentation. Now it should be more clearer that SMTP credentials also need to be set for the Sidekiq.

If you find any related issues in the feature, please note that we are open for contributions, and we'd be glad to help with any related process so those improvements can be included in the container images.
