### ISSUE TITLE
How to configure API rate limits?

### ISSUE THREAD

**Issue by danieldietsch** [bitnami/bitnami-docker-discourse#213]
Hi everyone, 
I am wondering how I can configure the various API rate limits of discourse in the bitnami docker container. 
https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612 talks about a `app.yml` file, but I cannot find one in `/opt/bitnami/discourse` (Docker, `bitnami/discourse:2.7.9`). 
A grep for `DISCOURSE_MAX_ADMIN_API_REQS_PER_MINUTE` also comes up empty.

**Comment by juan131** [comment]
Hi @danieldietsch 

If you're enabling configuration persistence (setting `DISCOURSE_ENABLE_CONF_PERSISTENCE` to `yes`), you'll find the Discourse configuration file at `/bitnami/discourse/config/discourse.conf`. However, if you disabled the configuration persistence, it can be located at `/opt/bitnami/discourse/config/discourse.conf`.

**Comment by danieldietsch** [comment]
@juan131 thanks for your help! 

I am somewhat unsure if this is the correct config file, as it contains some options in lower case while these rate limits are upper case (and the file doesnt look like a .`yaml` file). 

Assuming it is the correct file: as we rely heavily on environment variables, we probably want to add  things to this file the same way. I saw that there is this nice option `DISCOURSE_EXTRA_CONF_CONTENT`, and indeed I can add one line to this config file with 
``` yaml
...
      - DISCOURSE_EXTRA_CONF_CONTENT=DISCOURSE_MAX_ADMIN_API_REQS_PER_MINUTE=120
```
But how can I add more than one line? Using `\n` does not help.

**Comment by juan131** [comment]
Hi @danieldietsch 

The `DISCOURSE_EXTRA_CONF_CONTENT` only applies to the `discourse.conf` configuration file. Other customizations will have to be done manually or mounting custom scripts at `/docker-entrypoint-init.d` that will be executed after initializing Discourse during the 1st boot, see:

- https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/post-init.sh 

Regarding the `app.yml`, please note this file is included in the Discourse container image to configure the image but the Bitnami images do not include it. Bitnami images package the Discourse open-source code as it is and, as you can find in the link below, there's no `app.yml`:

- https://github.com/discourse/discourse/tree/main/config

**Comment by danieldietsch** [comment]
Ah ok, that makes sense. Do you per chance know if Discourse picks up these rate limit options from environment variables, or how I could configure them in the Bitnami container?

**Comment by juan131** [comment]
Honestly, I don't know how to configure that specific setting in Discourse. I recommend you to ask Discourse maintainers about alternatives to configure this.

**Comment by danieldietsch** [comment]
I will ask over there, perhaps they have a solution

**Comment by juan131** [comment]
Great!! Keep us updated in case you have new from them

**Comment by danieldietsch** [comment]
It seems like you can just set these options as environment variables and then discourse will pick them up. Ill have to test it, but thats what I took from https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612.
