### ISSUE TITLE
How to update plugins?

### ISSUE THREAD

**Issue by danieldietsch** [bitnami/bitnami-docker-discourse#214]
Hi everyone, 
I am trying to update plugins in the discourse container. 

I can install them with 
```
cd /opt/bitnami/discourse/
RAILS_ENV=production bundle exec rake plugin:install repo=plugin_git_url
RAILS_ENV=production bundle exec rake assets:precompile
```

But I did not find any way to update them. Is it enough to do a `git pull` for a plugin followed by a `RAILS_ENV=production bundle exec rake assets:precompile`?

**Comment by marcosbc** [comment]
Hi @danieldietsch, plugins are installed to `/opt/bitnami/discourse/plugins`. To update the plugin, navigate to the folder and run `git pull` like you mentioned, and then precompile assets (in case any new asset was included).

Note that afterwards you will need to restart the application, which in your case is probably simplest by restarting the container.

**Comment by danieldietsch** [comment]
Thanks, just wanted to check.
