### ISSUE TITLE
Could not download ruby-2.7.5

### ISSUE THREAD

**Issue by publishweb** [bitnami/bitnami-docker-discourse#216]
![image](https://user-images.githubusercontent.com/27599944/147327986-5600a57e-5691-4346-8311-2e33d3754e0e.png)
 
Without ruby-2.7.5,I Cannot compilation success.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by tommyhlw** [comment]
same here.

`:/#  cat tmp/passenger_native_support-1f4p8gx.log 
current user is: discourse
# mkdir -p /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.12/buildout/ruby/ruby-2.7.5-x86_64-linux
Encountered permission error, trying a different directory...
-------------------------------
# mkdir -p /home/discourse/.passenger/native_support/6.0.12/ruby-2.7.5-x86_64-linux
Encountered permission error, but no more directories to try. Giving up.
-------------------------------`

**Comment by yangjunjie52** [comment]
麻烦问一下，你这个问题解决了吗？

**Comment by aerott** [comment]
The Bot closed the thread but the problem remained.... -.-
