### ISSUE TITLE
SMTP Issue (Bad Sender)

### ISSUE THREAD

**Issue by JosephVasc** [bitnami/bitnami-docker-discourse#217]
Not sure if my setup is correct, Setting up discourse for a project and need to understand how the sender address is set. Does this image support postmark? Where am I able to setup a sender address? 

SMTP SETUP

DISCOURSE_SMTP_HOST: postmarkapp.com
DISCOURSE_SMTP_PORT: "25"
DISCOURSE_SMTP_USER: ***MASKED KEY****
DISCOURSE_SMTP_PASSWORD: ***MASKED KEY***
DISCOURSE_SMTP_PROTOCOL: tls

I've also downloaded the smtp tool to help troubleshoot my issue, receiving a badsender error (while smtp is connecting successfully). 

I've also tried setting the config file and rebooting the container (notification_email). 

Thanks

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
