### ISSUE TITLE
SSL cert / NGINX

### ISSUE THREAD

**Issue by JosephVasc** [bitnami/bitnami-docker-discourse#218]
Where can I find the cert values to include my ssl cert for setting up nginx

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
