### ISSUE TITLE
Request to use beta versions of discourse

### ISSUE THREAD

**Issue by bbroereES** [bitnami/bitnami-docker-discourse#219]
**Description**

Currently it does not seem that the beta versions of Discourse are available as a Docker image to use in the Bitnami Discourse package.
Discourse itself states (https://meta.discourse.org/t/2-7-12-security-release/212793):
_ Discourse strongly recommends that all sites follow the default tests-passed branch of Discourse. The “stable” branch is more focused on lack of change than lack of bugs - all releases, including those on tests-passed and beta are production ready._

**Steps to reproduce the issue:**

N/A

**Describe the results you received:**

Not able to use 2.8.0.beta10 of discourse

**Describe the results you expected:**

Being able to use 2.8.0.beta10 of discourse

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

We were triggered by some changes that have been pushed to a theme that fix certain issues we are experiencing. Upon request for these changes for Discourse version 2.7 they told us that, as per statement of Discourse, previous versions are focussed on lack of change rather than lack of bugs, hence they will not be implementing this.
Upon further research this seems to be the go-to way for development in/for Discourse.

**Comment by juan131** [comment]
Hi @bbroereES 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by maxpain** [comment]
Any updates?

**Comment by carrodher** [comment]
For now the release cadence is not going to change since we don't provide support for alpha, beta, release-candidate, etc versions

**Comment by bbroereES** [comment]
> For now the release cadence is not going to change since we don't provide support for alpha, beta, release-candidate, etc versions
I would like to ask you to reconsider this as Discourse itself states that '...all releases, including those on tests-passed and beta are production ready', hence these versions should not be considered regular alpha/beta/rc versions. 
Other parties, like plugin developers, assume you are on these versions as this is the recommended way to do. Because we can't right now, we are missing out on functionalities/bugfixes.
