### ISSUE TITLE
How to set up admin account on a open shift project environnement ? 

### ISSUE THREAD

**Issue by RodolpheGriset** [bitnami/bitnami-docker-discourse#220]
**Description**

Hi, I'm an engineer in optimisation so I don't know that much about installing dockers so my excuse if I'm not really precise. I installed your docker image on an open shift project and it works perfectly. The only problem is that I don't know how to setup admins account on it as I didn't installed it through a terminal. 

I tried to set the environment variable : DISCOURSE_DEVELOPER_EMAILS but it doesn't seems to change anything. 

Thanks for your help 

ps : I don't know if it's the right place to ask this kind of question but I havent found a proper forum dedicated to your docker

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
