### ISSUE TITLE
[Question] Empty response while the discourse server is running

### ISSUE THREAD

**Issue by animesh-sharama** [bitnami/bitnami-docker-discourse#221]
**Description**
I started the discourse server following the instruction - https://github.com/bitnami/bitnami-docker-discourse#how-to-use-this-image but received an Error(**ERR_EMPTY_RESPONSE** from chrome and **The connection was reset** from firefox) when connecting to localhost:8443 or localhost:8080

I checked the container and it seems to be up
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                                                      NAMES
7fe5e1303817   bitnami/discourse:latest    "/opt/bitnami/script…"   23 minutes ago   Up 23 minutes   0.0.0.0:8080->8080/tcp, 3000/tcp, 0.0.0.0:8443->8443/tcp   discourse
193bc180a5b1   bitnami/redis:latest        "/opt/bitnami/script…"   34 minutes ago   Up 34 minutes   6379/tcp                                                   redis
114a1b9d397f   bitnami/postgresql:latest   "/opt/bitnami/script…"   35 minutes ago   Up 35 minutes   5432/tcp                                                   postgresql
```

I was also able to create the admin user following the command inside the container ```RAILS_ENV=production bundle exec rake admin:create```

I also tried checking the log inside the container log/production.log file
```
Creating scope :open. Overwriting existing method Poll.open.
Creating scope :open. Overwriting existing method Poll.open.
Creating scope :open. Overwriting existing method Poll.open.
Started HEAD "/" for 127.0.0.1 at 2022-02-04 15:43:05 +0000
Processing by ListController#latest as HTML
  Rendered list/list.erb within layouts/crawler (Duration: 34.4ms | Allocations: 12258)
  Rendered layout layouts/crawler.html.erb (Duration: 142.7ms | Allocations: 34181)
Completed 200 OK in 465ms (Views: 145.8ms | ActiveRecord: 0.0ms | Allocations: 119053)
Creating scope :open. Overwriting existing method Poll.open.
```
but I don't see any new entries when I issue a http from browser/curl or postman. 

**Steps to reproduce the issue:**
start the container following the instruction- https://github.com/bitnami/bitnami-docker-discourse#how-to-use-this-image

**Describe the results you received:**

This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE 

**Describe the results you expected:**

Expected the server to be working and returning HTTP 200 status.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**
I have tried this process 8 times so far deleting and recreating the container and each time it was the same issue.

If anyone can point what I am doing wrong I would be really grateful.

**Comment by juan131** [comment]
Hi @animesh-sharama 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

**Comment by patrpok** [comment]
I encounter similar isuue. It might have something to do with error logged in **postgresql** or **discourse** container.

**Error logged in postgresql container**
This one is mentioned in [this thread](https://meta.discourse.org/t/pg-undefinedtable-error-relation-translation-overrides-does-not-exist/42599/2), but I couldn't find any workaround so far.
`
2022-02-07 19:41:46.518 GMT [161] ERROR:  relation "translation_overrides" does not exist at character 454,
2022-02-07 19:41:46.518 GMT [161] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),,
	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,,
	       c.collname, col_description(a.attrelid, a.attnum) AS comment,
	  FROM pg_attribute a,
	  LEFT JOIN pg_type t ON a.atttypid = t.oid,
	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum,
	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation,
	 WHERE a.attrelid = '"translation_overrides"'::regclass,
	   AND a.attnum > 0 AND NOT a.attisdropped,
	 ORDER BY a.attnum
`

**Error logged in discourse container**
This is just a warning and watching the timeline, postgresql error occurs first.

`App 765 output:  [passenger_native_support.so] trying to compile for the current user (discourse) and Ruby interpreter...,`
`App 765 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable),`
`App 765 output:      Warning: compilation didn't succeed. To learn why, read this file:,`
`App 765 output:      /tmp/passenger_native_support-1uplilt.log,`
`App 765 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...,`
`App 765 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable),`
`App 765 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 404 ,`
`App 765 output:      Trying next mirror...,`
`App 765 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 404 ,`
`App 765 output:      Trying next mirror...,`
`App 765 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden,`
`App 765 output:  [passenger_native_support.so] will not be used (can't compile or download) ,`
`App 765 output:   --> Passenger will still operate normally.,`


Mentioned `/tmp/passenger_native_support-1uplilt.log` file contains:

`# current user is: discourse`
`# mkdir -p /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.12/buildout/ruby/ruby-2.7.5-x86_64-linux`
`Encountered permission error, trying a different directory...`
`-------------------------------`
`# mkdir -p /home/discourse/.passenger/native_support/6.0.12/ruby-2.7.5-x86_64-linux`
`Encountered permission error, but no more directories to try. Giving up.`
`-------------------------------`
