### ISSUE TITLE
Binary for ARM64

### ISSUE THREAD

**Issue by talesam** [bitnami/bitnami-docker-discourse#223]
### Name and Version

bitnami-docker-discourse

### What is the problem this feature will solve?

My servers are on ARM64, and nowadays there are a lot of servers with ARM architecture growing, it would be interesting to have the binary.

### What is the feature you are proposing to solve the problem?

ARM64

### What alternatives have you considered?

I found the official Discourse, but the documentation is very bad for building a docker-compose

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
