### ISSUE TITLE
Ruby version 2.7.5 not working

### ISSUE THREAD

**Issue by ArtHoffmann** [bitnami/bitnami-docker-discourse#226]
### Name and Version

2.7.13-debian-10-r3

### What steps will reproduce the bug?

Hi, when i run docker compose up i get at the end of installing all libs etc. the following message in console:

### What do you see instead?

![image](https://user-images.githubusercontent.com/24555132/156642072-97e4a33a-8c5f-44f5-a2ad-abcd203dc995.png)

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by marcosbc** [comment]
Hi @ArtHoffmann, Discourse [2.8.1-debian-10-r0](https://github.com/bitnami/bitnami-docker-discourse/commit/e72541b481ff1d266766cbbcc72fade87a094c11) was just released with a fix for this issue.
