### ISSUE TITLE
Unable to update discourse instance with external database

### ISSUE THREAD

**Issue by tubia** [bitnami/bitnami-docker-discourse#227]
### Name and Version

bitnami/discourse:2.8.1

## Context

A docker-compose consisting of `sidekiq`, `discourse` and `redis`. A postgresql instance in the host machine available at `172.17.0.1:5432`

External volumes for the three services as following: `'/srv/discourse/discourse_data:/bitnami/discourse'`, `'/srv/discourse/redis_data:/bitnami/redis'` and `'/srv/discourse/sidekiq_data:/bitnami/discourse'`.

## Attempted task

Update the discourse docker container

## Steps to reproduce

1. `docker-compose down`
2. update the `docker-compose.yml` definition with the updated tags both for `discourse` and `sidekiq`: `bitnami/discourse:2.8.1`
3. `docker-compose pull`
4. `docker-compose up -d`

### What is the expected behavior?

A running, updated, instance of discourse.

### What do you see instead?

`docker-compose logs redis` returns:

```
mkdir: cannot create directory '/bitnami/redis/data': Permission denied
```

`docker-compose logs discourse` returns:

```
discourse  | discourse INFO  ==> Restoring persisted Discourse installation
discourse  | discourse INFO  ==> Trying to connect to the database server
discourse  | discourse INFO  ==> Running database migrations
```

both the three containers exit.

### Additional information

When downgrading back to `2.7.13` everything works again except for the redis container, which gives the same error.

**Comment by cdrx** [comment]
I get the same errors here, after an upgrade to 2.8.1. 

The sidekiq container, errors out with:

```
discourse 14:42:59.98 Welcome to the Bitnami discourse container
discourse 14:42:59.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse 14:42:59.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse 14:42:59.98 

/opt/bitnami/scripts/discourse/entrypoint.sh: line 31: exec: nami: not found
```

After downgrading to 2.7.13 the site does start up correctly.

**Comment by marcosbc** [comment]
Hi @tubia, could you show us the full error, including the one from the Discourse container? Note that there is a breaking change on a Discourse plugin that will force you to make some additional changes to upgrade it. For Helm charts we have prepared the following guide: https://docs.bitnami.com/kubernetes/apps/discourse/administration/upgrade/

As for your Redis error, it could be that you are using a really old version of Redis. If you provide the full docker-compose you were using, we may be able to help you. In the meantime refer to the [Notable changes](https://github.com/bitnami/bitnami-docker-redis/#notable-changes) section for the Redis container, where the changes are mentioned. In your case, it could be related to the changes mentioned in [`4.0.1-r1`](https://github.com/bitnami/bitnami-docker-redis/#401-r1).

@cdrx If you see that error, it probably means that you were using a really old version of the container image. Note that `nami` should not be present as of [`2.7.0-debian-10-r4`](https://github.com/bitnami/bitnami-docker-discourse/#270-debian-10-r4), meaning that `2.7.13` should not contain it either. Could you review if there is a `command` section in your docker-compose that refers to `nami`? If so please update it: https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml#L47
