### ISSUE TITLE
sidekiq is always connecting to localhost postgres

### ISSUE THREAD

**Issue by JoaoOxOc** [bitnami/bitnami-docker-discourse#229]
### Name and Version

bitnami/discourse:2.8.3

### What steps will reproduce the bug?

1. Set env variables for postgres database on the sidekiq
2. Try to run it: it will throw a message that it is trying to connect to a localhost:
```
[38;5;6mdiscourse [38;5;5m10:21:21.95 [0m[38;5;2mINFO [0m ==> ** Starting Sidekiq **
2022-05-04T10:21:32.393Z pid=1 tid=cd1 WARN: ActiveRecord::ConnectionNotEstablished: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2022-05-04T10:21:32.393Z pid=1 tid=cd1 WARN: /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
```

### What is the expected behavior?

Sidekiq should be able to connect to an external database server

### What do you see instead?

sidekiq only works with localhost databases

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by JoaoOxOc** [comment]
thank you @carrodher. Installed now using helm charts (https://bitnami.com/stack/discourse/helm), found that the correct env variables must be set: did it cloning the helm configurated env variables. It's now working with an external database
