### ISSUE TITLE
App install error in Docker swarm

### ISSUE THREAD

**Issue by activexJ** [bitnami/bitnami-docker-discourse#23]
**First run not creating DB data in postgres**

Hi When i start the app for the first time using docker stack deploy of the docker-compose file. All the containers are starting. But after some time the initial seed data is not getting created for the discourse

Docker version :17.5.0-ce
docker-compose v3

**Steps to reproduce the issue:**

1. Create the app folder in machine
2. Initiate the app using the command docker stack deploy -c docker-compose.yml adppname

**Describe the results you received:**

All the containers getting started. But in postgres logs i got the following errors
```
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet

ERROR:  extension "hstore" already exists
STATEMENT:  CREATE EXTENSION hstore;

ERROR:  relation "users" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"users"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
LOG:  incomplete startup packet
LOG:  incomplete startup packet
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
LOG:  incomplete startup packet
LOG:  incomplete startup packet
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
ERROR:  relation "scheduler_stats" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"scheduler_stats"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
and in discourse container the following error i am getting

postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Enabling PostgreSQL plugins for Discourse...

Error executing 'postInstallation': ERROR:  extension "hstore" already exists
```
And app is not accessible

**Version**

- Output of `docker version`:

```
Docker version 17.05.0-ce, build 89658be
```

- Output of `docker info`:

Dcoker running in swarm mode. 

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS private cloud

**Comment by bitnami-apps-team** [comment]
We believe the issue may be caused by existing volumes with persisted data when trying to initiate the application. Postgres is using an existing, already initialized database for Discourse but Discourse is trying to initialize it again for some reason. The error message is shown when Discourse tries to create the "hstore" extension when it has already been created previously.

Were there existing volumes when you tried to initiate the app or was it a fresh deployment?

**Comment by amrecio** [comment]
We believe the issue may be caused by existing volumes with persisted data when trying to initiate the application. Postgres is using an existing, already initialized database for Discourse but Discourse is trying to initialize it again for some reason. The error message is shown when Discourse tries to create the "hstore" extension when it has already been created previously.

Were there existing volumes when you tried to initiate the app or was it a fresh deployment?

**Comment by activexJ** [comment]
Hi During the first run without default data persisted in volumes. the hstore creation issue is comming. As a alternative I stopped discourse container when it get created and dropped all DB's in postgres. Then resumed the execution of the container and then it worked.

One more help is there any way to setup smtp without username  and password. As i setup my host to have default smtp without username and password.

**Comment by amrecio** [comment]
We don't support setting up SMTP without providing a username and password. As a workaround, you may start the application, configuring SMTP as explained [here](https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration) with a dummy username and password, and then change the configuration of Discourse while it's already running.

To do this, execute a shell in the container where Discourse is running and edit the `/opt/bitnami/discourse/conf/discourse.conf`, removing the username and password from the SMTP settings:

```
    smtp_user_name =
    smtp_password =
```

Save the file and restart Discourse by executing `nami restart discourse`. You can check the result by browsing http://yourhost/admin/email.

**Comment by activexJ** [comment]
Hi I changed the smtp username and password. For login do we have any options. its currently have login.

**Comment by amrecio** [comment]
Hi,

I'm not sure I understand your latest question? Do you want to be able to use Discourse without login credentials?

**Comment by activexJ** [comment]
Hi,

No in smtp config there is a setting 

smtp_authentication = login

For this if there is no username and password is there which option i have to give?
