### ISSUE TITLE
Could not connect to the database

### ISSUE THREAD

**Issue by Justman10000** [bitnami/bitnami-docker-discourse#231]
### Name and Version

bitnami/discourse

### What steps will reproduce the bug?

1. Pull images
2. Create container
3. Discourse not stating

### What is the expected behavior?

Discourse starting

### What do you see instead?

The error:

> Could not connect to the database

### Additional information

Redis and PostgreSQL are set up, and all data is correct

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by Justman10000** [comment]
> Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
> 
> If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

Why community? Shouldn't Bitnami support it?

**Comment by carrodher** [comment]
The Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues, just releasing new versions. Since it's an open source product and the code is available on GitHub, anyone can create and solve issues via PRs

**Comment by davidsneighbour** [comment]
I had the same issues and solved it by MANUALLY creating the local directories and chmod-ing them to 0777. There seems to be some interaction with other tools. For instance, the discourse-persistent-volume was owned by gitlab-runner which I have installed, but which is not connected to this project. Having all persistent volumes owned by your own user and setting them to 0777 will let docker write to that location.

Might not be the proper solution (for instance, what rights will files inside those volumes have), but I need it for development only, so I don't care too much about that detail.

**Comment by Justman10000** [comment]
> I had the same issues and solved it by MANUALLY creating the local directories and chmod-ing them to 0777. There seems to be some interaction with other tools. For instance, the discourse-persistent-volume was owned by gitlab-runner which I have installed, but which is not connected to this project. Having all persistent volumes owned by your own user and setting them to 0777 will let docker write to that location.
> 
> Might not be the proper solution (for instance, what rights will files inside those volumes have), but I need it for development only, so I don't care too much about that detail.

Which directories?

**Comment by Justman10000** [comment]
@davidsneighbour
