### ISSUE TITLE
Couldn't connect to external postgre DB - wrong DB name

### ISSUE THREAD

**Issue by krzysiekeaie** [bitnami/bitnami-docker-discourse#233]
### Name and Version

bitnami/discourse:7.2.3

### What steps will reproduce the bug?

1. Install external postgre DB
2. Install bitnami/discourse:7.2.3 helm chart on KUbernetes cluster with following configuration:
`postgresql:enabled: false`
`externalDatabase:host: x.x.x.x`
`externalDatabase:port: xxxx`
`externalDatabase:user: xxxx`
`externalDatabase:password: xxxxxx`
`externalDatabase:postgresUser: discourse-admin`
`externalDatabase:postgresPassword: xxxxxx`
`externalDatabase:database: my-discourse`
`externalDatabase:create: true`
`discourse:skipInstall: false`

### What is the expected behavior?

Discourse container should start and connect to external db which name is "my-discourse".

### What do you see instead?

Discourse container is trying to connect to "postgres" db name but correct name is "my-discourse".

From discourse container logs:
[38;5;6mdiscourse [38;5;5m09:19:06.14 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
psql: error: FATAL: no pg_hba.conf entry for host "10.155.25.41", user "discourse-admin", database "postgres", no encryption

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
