### ISSUE TITLE
Wiki Typo? 

### ISSUE THREAD

**Issue by smitch-git** [bitnami/bitnami-docker-discourse#235]
### Name and Version

 bitnami / bitnami-docker-discourse

### What is the problem this feature will solve?

Wiki volume mount for sidekiq shows discourse_data where the docker compose shows a conflicting sidekiq_data

### What is the feature you are proposing to solve the problem?

Please could you amend as its not clear which one to use 

### What alternatives have you considered?

n/a

**Comment by javsalgar** [comment]
Hi,

The docker-compose.yml should be the valid one. Would you like to submit a PR fixing the documentation?
