### ISSUE TITLE
Discourse stuck on db migration - kubernetes

### ISSUE THREAD

**Issue by therzv** [bitnami/bitnami-docker-discourse#237]
### Name and Version

bitnami/discourse:2.8.3-debian-10-r7

### What steps will reproduce the bug?

I deploy discourse using this doc: 
https://bitnami.com/stack/discourse/helm

everything running well, but i stuck on DB migration to the database.  

<img width="951" alt="Screen Shot 2022-06-26 at 20 31 32" src="https://user-images.githubusercontent.com/30797808/175816865-5dcf3494-8287-4914-8398-d5dcff1b46f4.png">

it always stuck as picture above, and then pod begin to restart.  no error were found. Redis and PostgreSQL is ready.

### What do you see instead?

```
discourse 13:37:06.29 
discourse 13:37:06.29 Welcome to the Bitnami discourse container
discourse 13:37:06.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse 13:37:06.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse 13:37:06.30 
discourse 13:37:06.31 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 13:37:06.32 INFO  ==> Trying to connect to the database server
discourse 13:37:06.37 INFO  ==> Creating database bitnami_application
discourse 13:37:06.53 INFO  ==> Creating Discourse configuration file
discourse 13:37:06.59 INFO  ==> Restoring persisted Discourse installation
discourse 13:37:06.71 INFO  ==> Trying to connect to the database server
discourse 13:37:06.74 INFO  ==> Running database migrations```
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
