### ISSUE TITLE
google health check fails

### ISSUE THREAD

**Issue by sheetal-c03** [bitnami/bitnami-docker-discourse#238]
### Name and Version

bitnami/discourse

### What steps will reproduce the bug?

I have deployed bitnami discourse on GKE. and creating health check for checking pod status. application is running on port 3000. but health check fails.

I have configured health check on port 3000 and path is /
my question is, on which port and path should I configure health check of discourse app?

### What do you see instead?

failed heath check status

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
