### ISSUE TITLE
using templates in app.yaml

### ISSUE THREAD

**Issue by dniasoff** [bitnami/bitnami-docker-discourse#241]
### Name and Version

discourse:2.8.4-debian-11-r0

### What steps will reproduce the bug?

Cannot see any option to configure templates in app.yaml

For example to set up cloudflare I would add

templates:
  - "templates/cloudflare.template.yml"

see https://meta.discourse.org/t/how-do-you-setup-cloudflare/32258/6

using discourse within kubernetes

### What do you see instead?

nowhere to configure templates in docker options

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
