### ISSUE TITLE
Support Azure Web App for Containers

### ISSUE THREAD

**Issue by kspearrin** [bitnami/bitnami-docker-discourse#30]
It would be nice if we could easily deploy an [Azure Web App for Containers](https://docs.microsoft.com/en-us/azure/app-service/containers/) using a Discourse image. Any idea if this will/can be supported? Looks like the current method requires the use of `docker-compose` which I guess isn't compatible.

**Comment by prydonius** [comment]
@kspearrin I haven't looked at Azure Web App for Containers, but it should be possible to create each container manually and connect them over the network in the same way that docker-compose does. Let me know if you were able to try that out, or if you have any issues doing this manually.
