### ISSUE TITLE
sidekiq  | Error executing 'postInstallation': Failed to connect to 127.0.0.1:3000

### ISSUE THREAD

**Issue by bialad** [bitnami/bitnami-docker-discourse#35]
**Description**

Discourse starts and works, but sidekiq fails

**Steps to reproduce the issue:**

1. docker-compose up
2. Wait for discourse successfully initialized
3. Wait for sidekiq error

**Describe the results you received:**

sidekiq_1     | Error executing 'postInstallation': Failed to connect to 127.0.0.1:3000 after 36 tries
bitnamidockerdiscourse_sidekiq_1 exited with code 1

**Describe the results you expected:**

Sidekiq to not give error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.0-ce-rc3
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   2357fb2
 Built:        Thu Sep 21 02:30:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce-rc3
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   2357fb2
 Built:        Thu Sep 21 02:36:52 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.09.0-ce-rc3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.88-boot2docker
Operating System: Boot2Docker 17.09.0-ce-rc3 (TCL 7.2); HEAD : 8c3082d - Thu Sep 21 16:27:29 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987MiB
Name: boot2docker
ID: SCVE:URJS:NXTA:VGO4:YLCB:ATKI:MFOO:3RTV:UD2X:YDLR:2V3Z:OH7V
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 84
 System Time: 2017-11-14T13:17:35.706652482Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running in boot2docker VM

**Comment by juan131** [comment]
I was able to reproduce the same issue! There are a couple of environment variables missing in the `docker-compose.yml`. Please add the env variables below under the environment section of the `sidekiq` service.

```
  - DISCOURSE_HOST=discourse
  - DISCOURSE_PORT=3000
```

Please find out the changes in this PR: https://github.com/bitnami/bitnami-docker-discourse/pull/36

Could you please confirm it fixes the issue?

**Comment by bialad** [comment]
That fixed the issue.

This it the first time I'm using discourse, but the sidekiq seems to be working. :)
