### ISSUE TITLE
able to send test email but not able to send invite to users

### ISSUE THREAD

**Issue by Navpreet2289** [bitnami/bitnami-docker-discourse#38]
version v1.8.11-dirty
able to send test email but not able to send invite to users

**Comment by javsalgar** [comment]
Hi, thanks for opening the case. Could you check the following?

  - Do the logs show any relevant information?
  - Are all the services running? (for example: sideqik)

**Comment by rene-gomez** [comment]
This problem is because example.com is hardcoded in /root/.nami/components/com.bitnami.discourse/helpers.js

How can modify this line?

best regars

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know @rene-gomez , I will forward this information. You can change the domain in `/opt/bitnami/discourse/discourse.conf`.

**Comment by rene-gomez** [comment]
@javsalgar This ersion not have discourse.conf file, onli have:

discourse.sublime-project

**Comment by javsalgar** [comment]
Sorry, I meant `/opt/bitnami/discourse/conf/discourse.conf`

**Comment by Raphty** [comment]
I had the same issue, and I fixed it together with the issue described in Issue #31.
So maybe try this.

**Comment by juan131** [comment]
Hi everyone,

I'm closing this issue as a duplicate of https://github.com/bitnami/bitnami-docker-discourse/issues/40
