### ISSUE TITLE
CleverCloud Host don't support docker-compose

### ISSUE THREAD

**Issue by TeoWneD** [bitnami/bitnami-docker-discourse#45]
Before explaining the bug i have few thing to precise:
When i started to try to make discourse's docker work, i was totally new to docker, now i have few basics.
I followed from close the insrtruction here: https://github.com/bitnami/bitnami-docker-discourse#run-the-application-manually

First i was trying to make it work on local host on my ubuntu 18.04 oracle virtual machine.
i started with the manual command, as i wanted to learn the most i can from that discourse installation.
But with the given manual command i never managed to make it work, so i asked help to some friends that are use to docker, to help me try it on localhost.  I managed to access discourse, by using the docker-compose up -d on the docker-compose.yml that is provided by the CURL command.
After trying it everything were perfect so i decided to host it on my company website, but here is the problem: our host service do not support docker-compose yet. So i have to go from the docker-compose.yml file command, to the not compose format, but with the same command, (because as i said it was the only way it worked for me on my environement )
I searched some documentation, and asked to my host support ( clever cloud ) how could i do.
They told me that i have to create 1 Dockerfile per container that the app need.

**Comment by andresbono** [comment]
Hi @TeoWneD, if you take a look at the docker-compose, you can see 4 services that are 4 different containers. These are the Dockerfiles:

- postgresql https://github.com/bitnami/bitnami-docker-postgresql/blob/master/9.6/debian-9/Dockerfile
- redis https://github.com/bitnami/bitnami-docker-redis/blob/master/4.0/debian-9/Dockerfile
- discourse and sidekiq: https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/Dockerfile

For each container, you will need to specify some environment variables, volumes...
You usually do this by running the commands specified in the guide that you followed. For your case, the commands will be:

```
docker network create discourse-tier
docker run -d --name postgresql --net=discourse-tier --volume $PWD/postgresql-persistence:/bitnami bitnami/postgresql:9.6
docker run -d --name redis --net=discourse-tier --env ALLOW_EMPTY_PASSWORD=yes --volume $PWD/redis-persistence:/bitnami bitnami/redis
docker run -d --name sidekiq --net=discourse-tier --env DISCOURSE_HOST=discourse --volume $PWD/sidekiq-persistence:/bitnami bitnami/discourse nami start --foreground discourse-sidekiq
docker run -d --name discourse -p 80:3000 --net=discourse-tier --env POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application --env POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse --env POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1 --volume $PWD/discourse-persistence:/bitnami bitnami/discourse
```
If you confirm that it works for you, we can try to improve our README.md.
Hope it helps,
-Andrés B.

**Comment by TeoWneD** [comment]
Thanks for your help, So i Downloaded the 3 repo with the dockerfile inside i puted the 3 in an other repo.
I pushed that repo on my clever cloud app ( a docker app linked a redis addon and a postgresql addon )
I ran all the command, and checked with sudo docker ps -a and sudo docker network ls  just in case.
Then i clever deployed ( host command to deploy the app ) 
In my log errors i had this :
![capturekjh](https://user-images.githubusercontent.com/15171682/43709378-f03ea888-996c-11e8-8d75-8bd9d3118f59.JPG)
i think that the error is that clever cloud don't recognize a 'mandatory dockerfile'
Thanks again for helping :)

**Comment by beltran-rubo** [comment]
Correct, it seems you need to specify the exact location of the Dockerfile and CleverCloud is not getting the file properly. 

I am not familiar with CleverCloud but maybe you can get a better answer in their support. I hope it helps.

**Comment by TeoWneD** [comment]
I started to reach them on their support but its unavailable today, i found this documentation, 
https://www.clever-cloud.com/doc/docker/docker/

Where we can find: 


Dockerfile contents

You can virtually put everything you want in your Dockerfile. The only mandatory (for us) instruction to put in it is:

CMD <command to run>

command to run: this is the command that starts your application. Your application must listen on port 8080. It can be easier for you to put a script in your docker image and call it with the CMD instruction.
I'll keep trying contact the support. i keep you all updated. :)

**Comment by beltran-rubo** [comment]
Great, thanks. Keep us in the loop.

**Comment by TeoWneD** [comment]
Hey, the support helped me, now i'm almost done :) i just have to set up the right port at the right place.
![capture](https://user-images.githubusercontent.com/15171682/43828962-2662d8c0-9afe-11e8-985f-b4e8cf397836.JPG)
Thats the error i got, and that is the terminal and host settings, in yellow the thing i think i may have to change, and tryed few, in blue the privacy protection.
![capture2](https://user-images.githubusercontent.com/15171682/43829176-9e97b07c-9afe-11e8-82bc-09aa25d28d1c.JPG)

**Comment by juan131** [comment]
It seems it's unable to connect to **PostgreSQL** and **Redis**. I guess it can be related with 2 possible reasons:

- You modified the env. variables of the Discourse Dockerfile but you did not modify the env. variables of **PostgreSQL** and **Redis** Dockerfiles. Therefore, they are using different ports.
- PostgreSQL and Redis containers are not using the same docker network (remember to use **--net=discourse-tier** when starting each of the containers).

**Comment by TeoWneD** [comment]
Hi I fixed it, it was the configration between my dockerfile and the clever cloud parameters ( environment variables ) but now i have a problem because in their back acces there is no root password or root username so i got refused, and i still have the nothing is listening on port 8080 error.

**Comment by juan131** [comment]
If you take a look to this [section](https://github.com/bitnami/bitnami-docker-discourse#environment-variables), you'll find out that there are several env. variables:

```
POSTGRESQL_ROOT_USER: Root user for the Postgresql database. Default: postgres
POSTGRESQL_ROOT_PASSWORD: Root password for Postgresql.
POSTGRESQL_HOST: Hostname for Postgresql server. Default: postgresql
POSTGRESQL_PORT_NUMBER: Port used by Postgresql server. Default: 5432
DISCOURSE_POSTGRESQL_USERNAME: Discourse application database user. bn_discourse
DISCOURSE_POSTGRESQL_PASSWORD: Discourse application database password. bitnami1
DISCOURSE_POSTGRESQL_NAME
```

The "root" access it's for a `psql` client that is run during Discourse initialisation by [Nami](https://github.com/bitnami/nami) so PostgreSQL database is "prepared" for Discourse. However, Discourse won't use those credentials once started to connect to PostgreSQL. Instead, it'll use the user **bn_discourse** which will only have access to the database created for Discourse.

**Comment by TeoWneD** [comment]
I'm sharing that with the support, i'm now trying to make it in localhost, i had 2 errors and found one answer:
The one about password i founded a stackoverflow on it. But the error about the port i still don't find it.

![kj](https://user-images.githubusercontent.com/15171682/43949031-babd9660-9c8c-11e8-8425-e7636a98cb16.JPG)

https://stackoverflow.com/questions/24917832/how-connect-postgres-to-localhost-server-using-pgadmin-on-ubuntu

**Comment by TeoWneD** [comment]
So i told the host about the root access, and they explained that they can't give me a root access because postgresql is creating others database, and the host won't be able to reach them.
So i have to set up myself the postgresql that will use my discourse.
what is the good way to do it ?

**Comment by juan131** [comment]
Hi @TeoWneD 

We don't support to initialise Discourse with existing databases yet. We already support this feature on other images such as WP, Drupal or Joomla! (see [WP section for instance](https://github.com/bitnami/bitnami-docker-wordpress#use-an-existing-database)) but we don't support it on Ruby apps yet.

Therefore, you can't create a PostgreSQL database so later on the Discourse container uses it. It's designed to create its own database.

I guess this is a blocking issue for you since CleverCloud doesn't allow you to do so... 

@beltran-rubo could we extend the possibility of using an existing databases on Ruby apps on the short term?

**Comment by TeoWneD** [comment]
I talked with my team, 3 solutions, the paying installation, but the datas are'nt on our side so we become dependant, at least in short term.
Or i try the ruby install as the docker install is only leading to new problems.
Or i try an other host, that support compose.
So i'll keep you in the loop, to make you acces that knowledge in order to improve readme if you want to.
But you have to know that i'm choosing an other solution :) for now i won't go on digital ocean even if this is a very recommanded support. I'll create a server on our second host (gandi)

**Comment by juan131** [comment]
> So i'll keep you in the loop, to make you access that knowledge in order to improve readme if you want to.

Great! Thanks! It's very important for us your feedback in order to improve our assets.

Please also know we offer Discourse as a single VM on several Cloud Providers:

https://bitnami.com/stack/discourse/cloud

Just in case you're interested on some of those platforms.

**Comment by TeoWneD** [comment]
Nice :) i don't think that i will need it. I just paid an other host that support docker compose, and i did what worked on my local vm machine, on the server, and it worked instantly. 
I'm actually setting up, the website ( admin/mail/etc ). 
Docker was'nt the solution for me on Clever Cloud as docker-compose was'nt usable, and that the host had too many specifications that disallow me to use discourse or docker as you thought it . A cloud server with gandi's service was !! :) 1 mounth on clever cloud, few hours on gandi :).

**Comment by juan131** [comment]
Great! I'm glad you were able to easily set it up on Gandi 😃

**Comment by TeoWneD** [comment]
Thx i'm glad i finnaly installed DISCOURSE :D

**Comment by TeoWneD** [comment]
Does it have to do something with those environment variables ? i saw them on a dockerfile, but they are absent from the docker-compose.yml that i curled.

DISCOURSE_DEVELOPER_EMAILS:
DISCOURSE_SMTP_ADDRESS:
DISCOURSE_SMTP_PORT: 25
DISCOURSE_SMTP_USER_NAME:
DISCOURSE_SMTP_PASSWORD:

**Comment by juan131** [comment]
Hi @TeoWneD 

Yes, in order to configure the SMTP settings on Discourse, you need to setup the env. variables: (SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD & SMTP_TLS). Everything is explained on [this section of the README.md](https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration).

**Comment by TeoWneD** [comment]
Ok thanks, i puted 
- SMTP_HOST=in-v3.mailjet.com
      - SMTP_PORT=25
      - SMTP_USER=027***************************** ( credential username given by mailjet )
      - SMTP_PASSWORD=d2f***************************** (credential password given by mailjet)
      - SMTP_TLS="true"

But the emails are'nt sent, in the emails logs i had :

![tresd](https://user-images.githubusercontent.com/15171682/44216721-df09b100-a175-11e8-8a2e-27868f4a98fa.JPG)

www.example.com rang the bell also the critical email user.

But when i tryed to fix it , i found nothing.

In the admin settings of discourse, there is no www.example.com, neither in the docker-compose.yml. 

The fact that emails are'nt configured come from what ? 

A misstake in docker-compose.yml, like an error on smtp_user smtp_password ?

Or maybe i have to add smtp_domain in docker-compose.yml ?

Or it come from the underground connections ( SPF/DKIM/DNS ) between mailjet and gandi (host)

**Comment by juan131** [comment]
The www.example.com can be fixed by setting the env. variable **DISCOURSE_HOSTNAME** (check https://github.com/bitnami/bitnami-docker-discourse#configuration)

For troubleshooting SMTP issues, we have an SMTP Checker: It will analyse your SMTP configuration in your application (currently supported apps: wordpress & redmine). It will show which SMTP configuration your application is using and whether the connection with the SMTP server is good and will also check the mail delivery. Execute these commands inside your container to download the tool:

```
wget https://github.com/bitnami-labs/healthcheck-tools/releases/download/2.0.0/smtp-checker-v2.0.0-linux-amd64
chmod +x smtp-checker-v2.0.0-linux-amd64
```

Since your application is not supported yet, please find out your SMTP settings and run the command:

```
./smtp-checker-v2.0.0-linux-amd64 -smtp_host YOUR_SMTP_HOST -smtp_port YOUR_SMTP_PORT -smtp_user YOUR_SMTP_USER -smtp_password YOUR_SMTP_PASS -mail_recipient YOUR_MAIL_ACCOUNT
```

> Please note that you need to replace the placeholders YOUR_SMTP_HOST, YOUR_SMTP_PORT, YOUR_SMTP_USER, YOUR_SMTP_PASS and YOUR_MAIL_ACCOUNT with the actual values you want to use.

> Please note that you need to replace the placeholder YOUR_MAIL_ACCOUNT with the actual value of your mail account.

Please show us the results of executing the commands.

Could you also run the command below and share the output?

```
 docker-compose exec discourse tail -n 20 /opt/bitnami/discourse/log/production.log
```

**Comment by TeoWneD** [comment]
Hi and thanks for the answers.
I added the environnement variable DISCOURSE_HOST in the docker-compose.yml, first time with an url, but i may have made a misstake so i have done it again with the ip this time. (which is given by host so no misstake )
For now its not working, here are the output you asked.

![qsqsc](https://user-images.githubusercontent.com/15171682/44262889-f3ed4f80-a21c-11e8-88c6-02d388659e44.JPG)

![sdf](https://user-images.githubusercontent.com/15171682/44262890-f485e600-a21c-11e8-92f0-987968d2e379.JPG)

The env var YOUR_MAIL_ACCOUNT has to be un docker-compose.yml right ? because i puted it in my docker-compose.yml and the same addresse is in my sender email in mailjet and in my discourse admin required settings as notification email. its correct right ?

**Comment by juan131** [comment]
Hi @TeoWneD 

On the one hand, it seems that when you run the SMTP checker tool you didn't quote the password and user and it didn't retrieve them properly. Please re-run it like shown below:

```
./smtp-checker-v2.0.0-linux-amd64 -smtp_host YOUR_SMTP_HOST -smtp_port YOUR_SMTP_PORT -smtp_user "YOUR_SMTP_USER" -smtp_password "YOUR_SMTP_PASS" -mail_recipient YOUR_MAIL_ACCOUNT
```

> The env var YOUR_MAIL_ACCOUNT has to be in docker-compose.yml right ? 

It's not necessary to set that env. variable. I guess you refer to **DISCOURSE_EMAIL** (check https://github.com/bitnami/bitnami-docker-discourse)

Could you run the command below and share the output?

```
docker-compose exec discourse cat /opt/bitnami/discourse/config/discourse.conf
```

**Comment by TeoWneD** [comment]
Hi sorry for delay, it was my copy paste from desktop to vm that was a litte buggy for some obscure reasons.
Here are the results of the commands:

![git](https://user-images.githubusercontent.com/15171682/44650577-43830680-a9e7-11e8-94e3-c34143d5b3e9.JPG)

**Comment by juan131** [comment]
According to the tests done by the SMTP check tool, there's no connectivity issues and Discourse should be able to send the mail using your SMTP credentials.

However, as you can check on the configuration file **/opt/bitnami/discourse/config/discourse.conf**, SMTP is not configured. You should have obtained sth like this:

```
$ docker-compose exec discourse cat /opt/bitnami/discourse/config/discourse.conf

  db_name = bitnami_application
  db_host = postgresql
  db_port = 5432
  db_password = bitnami1
  db_username = bn_discourse
  db_pool = 25

  hostname = www.example.com
  redis_port = 6379
  redis_host = redis
  redis_password =
  smtp_address = smtp.gmail.com
  smtp_port = 587
  smtp_domain = example.com
  smtp_user_name = your_email@gmail.com
  smtp_password =  your_password
  smtp_enable_start_tls = true
  smtp_authentication = login
```

Did you you setup the env. vars? Please note that the env. vars won't be used if you attach volumes with persist data from previous deployments. Therefore, you'd need to clean them in order to deploy Discourse with the STMP configuration.

**Comment by TeoWneD** [comment]
Yeah thanks you. I just had to delete the volumes and the restart it again, I can now recieve a test email, but i cannot recieve an invitationnal ( for admin or modo ) mail.

**Comment by juan131** [comment]
Hi @TeoWneD 

Just to ensure we're no the same page. Could you confirm you're under the scenario below?

 - You're able to send test mails and they're received on your inbox through the Admin Panel

![screen shot 2018-08-28 at 10 39 53](https://user-images.githubusercontent.com/6740773/44712127-61686e00-aab0-11e8-863a-97278575718d.png)


 - Then, you try to create a new user account:

![screen shot 2018-08-28 at 10 42 06](https://user-images.githubusercontent.com/6740773/44712145-6af1d600-aab0-11e8-8809-886db15bd727.png)

 - You received the following response:

![screen shot 2018-08-28 at 10 50 38](https://user-images.githubusercontent.com/6740773/44712186-8361f080-aab0-11e8-9a21-867528b1d2e3.png)


 - However, you never received the mail on your inbox.

**Comment by TeoWneD** [comment]
Yes you are 100 % correct !

**Comment by beltran-rubo** [comment]
Related to the confirmation email, note the IP is in the link and it is a temporary link. If you stopped/started the solution probably got another IP or the link is not valid. Could you confirm that is the case? The issue with the spam folder depends on the SMTP provider you are using and your email filter, it is not related to the application configuration.

We are checking the permissions issue with gravatars.

**Comment by TeoWneD** [comment]
Nope this ip is provided by my host. And stay static, i do have a dns that redirect it to forum.culibo.com. Now we can acces the forum via the ip and the url.
About spam folder it was just details that i thought could help you.
I'm also trying to configure the https, any possibilities the problems are linked ?

**Comment by TeoWneD** [comment]
Weird now that i create new account they recieve the mail ( with the broken link ) but after the creation i have a message saying:
"We canno't know if the account has been created, please check your cookies configurations." ???

**Comment by beltran-rubo** [comment]
This error usually happens when the link in the notification and the domain/hostname configured into the application are not the same. You probably need to deploy the solutions specifying the public IP address in the DISCOURSE_HOSTNAME env variable. Could you try that?
