### ISSUE TITLE
version 2.0.3 release does not have a correct URL, because the url is https://www.example.com/

### ISSUE THREAD

**Issue by rene-gomez** [bitnami/bitnami-docker-discourse#47]
**Description**

when signing a new user, the server send an email to confirm and activate the account, the server send an email with URL www.example.com 

**Steps to reproduce the issue:**

    [First Step]
    create a new account
    [Second Step]
    wait a email confirmation
    [and so on...]
    the confirmation arrives, with URL www.example.com

Additional information you deem important (e.g. issue happens only occasionally):

Version

    Output of docker version:

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

    Output of docker info:

Containers: 31
 Running: 30
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 208
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 9.722GiB
Name: docker
ID: 4B6I:L3ET:6WWL:MFHG:R6Q7:O7FL:4YYV:233Y:FJQY:M3U7:UR5Y:QAZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

    Output of docker-compose version (if applicable):

docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

DOCKER COMPOSE FILE:

cat /var/www/site/forum/docker-compose.yml
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - 'postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - DISCOURSE_EMAIL=example@gmail.com
      - DISCOURSE_HOSTNAME=forum.example.com
      - DISCOURSE_SITENAME=forum.example.com
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=forum.example.com
      - SMTP_USER=example@gmail.com
      - SMTP_PASSWORD=password
  sidekiq:
    image: 'bitnami/discourse'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

Result of sidekiq container configuration:
RESULT OF /opt/bitnami/discourse-sidekiq/config/sidekiq.yml

production:
  :concurrency: 5
  :queues:
    - [critical,4]
    - [default, 2]
    - [low]
root@fc2b351ebb1b:/#

**Comment by beltran-rubo** [comment]
Hi @rene-gomez 

This happen when the hostname is not defined in the configuration file. You will need to add the following parameter in the "discourse.conf" file running the following command in the 'discourse-sidekiq' container:

```
printf "hostname = www.your-site.com" >> /opt/bitnami/discourse-sidekiq/conf/discourse.conf
```
Then stop & start the container (you can use docker-compose stop) and try to create an account for a new user.

We will add this option as a ENV var to make this easy for users. Thanks for reporting it.

**Comment by rene-gomez** [comment]
hi @beltran-rubo when i touch the discourse.conf file the email activation doesn't works again, the systemg not send more emails.

so, what's next.

You can try this solution?

best regards

**Comment by beltran-rubo** [comment]
Yes, I already tested this solution and works. I got an email with the proper link. 
Please check the discourse.conf file is properly configured. Could you paste it?

**Comment by rene-gomez** [comment]
Hello @beltran-rubo  after some tests this is my results:

if only paste this line the conf file to be corrupt: printf "hostname = www.your-site.com" >> /opt/bitnami/discourse-sidekiq/conf/discourse.conf

cat /opt/bitnami/discourse-sidekiq/conf/discourse.conf
```

  db_name = bitnami_application
  db_host = postgresql
  db_port = 5432
  db_password = bitnami1
  db_username = bn_discourse
  db_pool = 25
  redis_port = 6379
  redis_host = redis
  redis_password =
  smtp_address = smtp.gmail.com
    smtp_port = 587
    smtp_domain = example.com
    smtp_user_name = example@gmail.com
    smtp_password =  password
    smtp_enable_start_tls = true
    smtp_authentication = loginhostname = forum.someway.com




```
