### ISSUE TITLE
Missing rsync binary for restoring backups

### ISSUE THREAD

**Issue by Kristaba** [bitnami/bitnami-docker-discourse#51]
**Description**

On a fresh instance of Discourse Bitnami image, I tested the backup/restore capabilities from command line (calling `/opt/bitnami/discourse/script/discourse` backup/restore manually).
For doing the backups, everything seems to work nicely.
However, when trying to restore a backup tarball, it seems that discourse call `rsync` for restoring user uploads.

Here is the important part of the `restore` command output (this occurs after all the database has been correctly restored) :
```
Disabling readonly mode...
Extracting uploads...
EXCEPTION: No such file or directory - rsync
/opt/bitnami/ruby/lib/ruby/2.4.0/open3.rb:199:in `spawn'
/opt/bitnami/ruby/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
/opt/bitnami/ruby/lib/ruby/2.4.0/open3.rb:95:in `popen3'
/opt/bitnami/ruby/lib/ruby/2.4.0/open3.rb:258:in `capture3'
/opt/bitnami/discourse/lib/discourse.rb:24:in `execute_command'
/opt/bitnami/discourse/lib/backup_restore/restorer.rb:428:in `block in extract_uploads'
/opt/bitnami/ruby/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
/opt/bitnami/ruby/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
/opt/bitnami/discourse/lib/backup_restore/restorer.rb:421:in `extract_uploads'
/opt/bitnami/discourse/lib/backup_restore/restorer.rb:94:in `run'
script/discourse:111:in `restore'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
script/discourse:273:in `<main>'
Trying to rollback...
Rolling back...
Notifying 'system' of the end of the restore...
Cleaning stuff up...
Removing tmp '/opt/bitnami/discourse/tmp/restores/default/2018-08-20-132140' directory...
Unpausing sidekiq...
Marking restore as finished...
Finished!
[FAILED]
```

**Steps to reproduce the issue:**

1. Make a backup (command line or from the web UI)
2. Restore it from command line (I expect the same result if restored from web UI, but not tested)

Restoration is aborted, database is rolled-back to the pre-restore state and the command ends up with a failure message.

**Version**
Using the docker image tag `2.0.3`.

**Proposed fix**
Maybe I missed something (rsync not in my PATH? argument to restore without rsync?).
Otherwise, I would simply recommend to add `rsync` to the installed packages in the Dockerfile.
This fixed the issue for me and backup/restore now work as expected on my modified image.

**Comment by juan131** [comment]
Hi @Kristaba 

I could reproduce the issue through the Admin Panel. Steps to reproduce:

- Enable restore on Site Settings: Admin -> Settings -> Backups -> allow restore
- Create a backup through Admin Panel: Admin -> Backups -> Backup
- Restore Discourse from the backup created: Admin -> Backups -> Restore

However, I did not find with `rsync` but `pg_dump` instead:

```
[2018-08-21 09:31:35] EXCEPTION: failed to execute:
pg_dump -s -x -O -f /opt/bitnami/discourse/db/structure.sql bitnami_application

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.
```

We faced a similar issue on Odoo image in the past (see https://github.com/bitnami/bitnami-docker-odoo/issues/42) and we finally included **pg_dump** and **pg_restore** binaries on the image. 

I'd open a task to include those binaries on Discourse image as well. Thanks so much for reporting this bug!

**Comment by rafariossaa** [comment]
Hi @Kristaba 

We just released a new revision of this docker image **2.0.3** which addresses this issue.

Please feel free to test it and close this issue if you considered it solved!

**Comment by Southclaws** [comment]
I'm running into this on the latest image (pulled right before posting this), `pg_dump` is present in the container's filesystem so I have no idea why the error is occurring.

```
[2018-09-10 20:37:24] Migrating the database...
[2018-09-10 20:37:25] EXCEPTION: failed to execute:
pg_dump -s -x -O -f /opt/bitnami/discourse/db/structure.sql discourse

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.
```

**Comment by rafariossaa** [comment]
Hi @Kristaba 
  Let me check it.

**Comment by Kristaba** [comment]
Hum... Indeed, I had a permission issue I think, probably with either the `db` directory or the `structure.sql` itself.
I don't have access to my server to check that right now, but I am pretty sure I just did a `chmod` to fix that temporarily, and forgot to report the issue here...

**Comment by rafariossaa** [comment]
Hi @Kristaba ,
  I have just tested it worked for me.
  Please, Could you check with a clean installation ? This way we can be sure that we both are testing the very same, sometimes this kind of things are tricky to debug.

Best regards
Rafael Rios

**Comment by Southclaws** [comment]
It was a clean installation, I've been dealing with another issue recently so I haven't been able to deploy properly yet. Each time, I delete the state that's loaded into `/bitnami` for both discourse and sidekiq and redeploy from scratch. The docker-compose file I'm using is posted on #53

**Comment by rafariossaa** [comment]
Hi,
  I don't see that the changes you introduce to the docker file would bring this problem, but just to double check, Can you try the following:
  - From docker delete all the containers, images and volumes related to this.
  - Then download and launch the bitnami's docker-compose file
    $ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-discourse/master/docker-compose.yml > docker-compose.yml
    $ docker-compose up -d
  - Tail the logs, 
    $ docker-compose logs -f
  - Wait until a message like this: "redis_1       | 1:M 12 Sep 08:04:50.017 * 10 changes in 300 seconds. Saving..." appears. This will take a while.
  - Then open the browser and go to http://localhost/
  - Login as user: user, password: bitnami123
  - Go to Menu -> Admin -> Settings -> Backups, and enable "Allow restore, which can replace ALL site data! Leave false unless you plan to restore a backup".
  - Now, go to Menu -> Admin -> Backups and launch a backup clicking on the blue Backup button. 
  - Copy and paste on a text editor all the log that appears, and save it.
  - If you go now to Menu -> Admin -> Backups you should see that a log like this "my-site-2018-09-12-081033-v20180521191418.tar.gz" appears in the listing.
  - Now click on the restore button, and it will restore the previous backup, please copy and paste the log on a text editor and save it.

 Thanks forehand
Rafael Rios
