### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by digitalkram** [bitnami/bitnami-docker-discourse#55]
**Description**

On a fresh install after adding the first user via invite link I modified the trust-level of the new user to "leader" and clicked the green checkmark to save it.

**Steps to reproduce the issue:**

1. Setup a fresh instance
2. invite user via mail
3. create user account via invite
4. raise trustlevel of new user to leader
5. click save

**Describe the results you received:**
Installation is foobar, all pages show:
```
nami    INFO  discourse successfully initialized
Starting discourse...
       	plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss:91
        on line 91 of plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss
>>       @include small-width {
   ---------------^

[ N 2018-09-21 22:45:48.6056 2857/T1 age/Wat/WatchdogMain.cpp:1297 ]: Starting Passenger watchdog...
[ N 2018-09-21 22:45:48.6476 2860/T1 age/Cor/CoreMain.cpp:1200 ]: Starting Passenger core...
[ N 2018-09-21 22:45:48.6479 2860/T1 age/Cor/CoreMain.cpp:250 ]: Passenger core running in multi-application mode.
[ N 2018-09-21 22:45:48.7193 2860/T1 age/Cor/CoreMain.cpp:935 ]: Passenger core online, PID 2860
[ N 2018-09-21 22:45:50.9340 2860/T5 age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
```

**Describe the results you expected:**

user is modified, discourse stays usable

**Additional information you deem important (e.g. issue happens only occasionally):**

fresh installation, no history

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.111-mainline-rev1
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.34GiB
Name: scw-9659e5
ID: XOTP:324Y:AGHR:SERI:WQDQ:NOGU:SSED:A75T:A2KZ:DCXJ:YCDN:CX3K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

virtual machine hosted by scaleway: Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.4.111-mainline-rev1 x86_64 )

**Comment by juan131** [comment]
Hi @digitalkram 

It doesn't look like a problem with the image but a plugins instead. It seems it's just a CSS error but the app is still usable.

Maybe you can contact Discourse Plugin developers and they can provide you more info about what's going on.. It seems to be related with the line below:

https://github.com/discourse/discourse/blob/master/plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss#L91

**Comment by digitalkram** [comment]
@juan131 thank you for your time. Actually this message was not just shown in the log but also on every page of the installation no matter what I navigated to. No plugins installed explicitly. Really just the steps to reproduce were done as in my original post. However the problem is resolved. As it was a fresh installation I cleaned everything including the persistence folders, fixed my docker-compose file to point to a specific version instead of the latest tag and started from scratch. All fine so far.
I suspect it might have been related to the fact that I did two attempts within two weeks to install it without cleaning the persistent folders on the host and did a image pull before the second try. Maybe the assets generated by the older version are not compatible with the new one.. But just guessing here.

**Comment by juan131** [comment]
Hi @digitalkram 

It's likely to find some issues when upgrading the application.. That's why it's a good practise to backup the data you have on your persisted directories so you can move back to the previous version in case you find any issue with CSS, database schemas or anything else.

Are you able to reproduce the issue with a "clean installation" using the latest version of Discourse?

**Comment by digitalkram** [comment]
As I wrote in my previous post I am not able to reproduce the problem with a clean installation,that's why I closed the issue now.

**Comment by juan131** [comment]
Hi @dgonzalezruiz 

Sorry I thought you did the clean installation with the previous version!

**Comment by juan131** [comment]
You're welcome @dgonzalezruiz !! 

Obviously my last message was for @digitalkram 😄
