### ISSUE TITLE
SMTP Domain?

### ISSUE THREAD

**Issue by bhardin** [bitnami/bitnami-docker-discourse#56]
I don't see in the readme anyway to set the `SMTP_DOMAIN`. Once the container is up, I look at email settings and it has example.com. Is this pulled from another setting I didn't overload?

**Comment by rafariossaa** [comment]
Hi @bhardin,
  Following our documentation that parameter is not set, https://github.com/bitnami/bitnami-docker-discourse . Could you try if you can send email without setting it explicitly ? I guess ruby mail gem get it from the sender email address.

Thanks forehand
Rafael Rios

**Comment by bhardin** [comment]
The email is sending, but being rejected due to SPF. I was thinking this had something to do with it.

**Comment by marcosbc** [comment]
@bhardin Could you check the contents of "production.log" in the Discourse Sidekiq container? You can find it at the following location:

    /opt/bitnami/discourse-sidekiq/log/production.log

Do you see any errors related to sending e-mails?
