### ISSUE TITLE
Bad performance after fresh install

### ISSUE THREAD

**Issue by Moskito99** [bitnami/bitnami-docker-discourse#59]
**Description**

Bad performance after fresh install.
Discourse is unable to download and compile rubyext-ruby-2.4.5-x86_64-linux.tar.gz.

**Steps to reproduce the issue:**

1. docker-compose up -d
2. click a link inside discourse
3. wait....

**Describe the results you received:**

Long wait after click on any link because discourse try to download an compile rubyext-ruby-2.4.5-x86_64-linux.tar.gz

**Describe the results you expected:**

Discourse should know the right place to download rubyext-ruby-2.4.5-x86_64-linux.tar.gz.
Or is the rubyext-ruby-2.4.5-x86_64-linux.tar.gz package not neccesary?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 61
 Running: 61
 Paused: 0
 Stopped: 0
Images: 369
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 984
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.55GiB
Name: zeus
ID: J7A3:RJVZ:K5G7:B7CT:WVKH:XH73:2XMH:WLDN:N5Z2:PPLD:32LI:26QT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
discourse_1    | 2018-11-07T07:03:16.614026242Z App 3227 output:  [passenger_native_support.so] trying to compile for the current user (discourse) and Ruby interpreter...
discourse_1    | 2018-11-07T07:03:16.614071165Z App 3227 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1    | 2018-11-07T07:03:16.617871436Z App 3227 output:      Warning: compilation didn't succeed. To learn why, read this file:
discourse_1    | 2018-11-07T07:03:16.617892990Z App 3227 output:      /tmp/passenger_native_support-1lsaftg.log
discourse_1    | 2018-11-07T07:03:16.617897823Z App 3227 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
discourse_1    | 2018-11-07T07:03:16.617901344Z App 3227 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1    | 2018-11-07T07:03:16.944442840Z App 3227 output:      Could not download https://github.com/phusion/passenger/releases/download/release-5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
discourse_1    | 2018-11-07T07:03:16.944483695Z App 3227 output:      Trying next mirror...
discourse_1    | 2018-11-07T07:03:17.068293163Z App 3227 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: The requested URL returned error: 404 
discourse_1    | 2018-11-07T07:03:17.068322718Z App 3227 output:      Trying next mirror...
discourse_1    | 2018-11-07T07:03:17.548396981Z App 3227 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
discourse_1    | 2018-11-07T07:03:17.548585362Z App 3227 output:  [passenger_native_support.so] will not be used (can't compile or download) 
discourse_1    | 2018-11-07T07:03:17.548597398Z App 3227 output:   --> Passenger will still operate normally.
```

**Comment by marcosbc** [comment]
Hi @Moskito99, what you are describing is a known issue. We're currently working on a fix for this, so the Passenger native support library is built before runtime, but it is not ready yet.

Note that what you are describing should only add a bit of lag in the first request, during Discourse startup. After that, it should work fine.

In the meantime, you can fix this on your side by installing build-essential ("apt-get install build-essential"), restart Discourse and it should work fine with no warnings.

**Comment by Moskito99** [comment]
Hi @marcosbc , it is not only for the first time. It appears every 2-3 times when you click a link...
You mean "apt-get install build-essential" in the discourse container?

I will try this later and let you know if this fixes the error.

**Comment by Moskito99** [comment]
So, it is faster, but the error messages are the same.

**Comment by marcosbc** [comment]
Hi @Moskito99, we are currently working on releasing a Discourse container without that warning. It will include the passenger_native_support.so library pre-compiled, in order not to affect runtime performance.

If you need to have this fixed in the current version, we can only suggest you look into the compilation log files (e.g. "/tmp/passenger_native_support-1lsaftg.log") to see if you are missing any dependency, or any other error occured.
In our case, we were able to fix it by installing the build-essential package and running "passenger-config build-native-support" command. If this command prints nothing, it means that it has already been built for your current Ruby version.
If this is the case and you're still having performance issues, your issue is likely unrelated to the passenger_native_support.so library.

**Comment by marcosbc** [comment]
Hi @Moskito99, we released new revisions for the Bitnami Discourse container which includes the Passenger native support library:

- 2.1.3-debian-9-r0 release 
- 2.1.3-ol-7-r0 release 

Let us know if you find any issues.

**Comment by Moskito99** [comment]
Hi @marcosbc , I tried the new image and the performance issue is gone!

Well done!

**Comment by hpoul** [comment]
I'm seeing the same issues in the latest discourse image 2.7.5-debian-10-r3 (655ac1f72ace858f4978a99e6bfecf1a298903b19870414a43d0326a58140e76)

```
App 965 output:  [passenger_native_support.so] trying to compile for the current user (discourse) and Ruby interpreter...
App 965 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 965 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 965 output:      /tmp/passenger_native_support-s7cj9q.log
App 965 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 965 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 965 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.9/rubyext-ruby-2.7.4-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 965 output:      Trying next mirror...
App 965 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.9/rubyext-ruby-2.7.4-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 965 output:      Trying next mirror...
App 965 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.9/rubyext-ruby-2.7.4-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 965 output:  [passenger_native_support.so] will not be used (can't compile or download) 
App 965 output:   --> Passenger will still operate normally.

```

is it just me, or did this reoccur?

**Comment by marcosbc** [comment]
Hi @hpoul, you are effectively right. The problem here is that Passenger builds the native support binary for a specific Ruby version, and the release process for updating Ruby in our Discourse container image happens separately.

So in this case, it was built for Ruby 2.7.3 but version 2.7.4 was released, so it failed. I'm re-starting the build process for the Discourse container image to have it released without the issue. It should be out throughout the weekend.

**Comment by Mist-Hunter** [comment]
Is this related to long polling? https://github.com/bitnami/bitnami-docker-discourse/issues/172#issuecomment-922673459
I'm getting the  PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY error [listed above](https://github.com/bitnami/bitnami-docker-discourse/issues/59#issuecomment-880945259) also. And when I turn off long polling it seems to stop, though I still seem to experience random lag. 

Thanks for your efforts on the this container. The container provided by the Discourse people seems like it supposed to be easy to use, but this container feels way better.

**Comment by ArtHoffmann** [comment]
Issue still exists with the new version...

**Comment by ArtHoffmann** [comment]
> Hi @hpoul, you are effectively right. The problem here is that Passenger builds the native support binary for a specific Ruby version, and the release process for updating Ruby in our Discourse container image happens separately.
> 
> So in this case, it was built for Ruby 2.7.3 but version 2.7.4 was released, so it failed. I'm re-starting the build process for the Discourse container image to have it released without the issue. It should be out throughout the weekend.

Can you rebuild the version 2.7.5?

**Comment by migruiz4** [comment]
Hi @ArtHoffmann,

We are currently working to release Discourse 2.8.1, and due to some limitations in our release process, we can not include the fix for this issue in the current version 2.7.13.

The first release of the bitnami/discourse:2.8.1 will include this fix for the Passenger version mismatch. Sorry for the inconvenience.

**Comment by ArtHoffmann** [comment]
Perfect - Thank you.

**Comment by ArtHoffmann** [comment]
> Hi @ArtHoffmann,
> 
> We are currently working to release Discourse 2.8.1, and due to some limitations in our release process, we can not include the fix for this issue in the current version 2.7.13.
> 
> The first release of the bitnami/discourse:2.8.1 will include this fix for the Passenger version mismatch. Sorry for the inconvenience.

When u think the new release will be available for us?

**Comment by ArtHoffmann** [comment]
Hi after the update i get the following error when i run docker compose up:

![image](https://user-images.githubusercontent.com/24555132/156849713-50945028-0be7-4343-8d6b-0bbd59cfa0fa.png)

**Comment by marcosbc** [comment]
@ArtHoffmann That is because of a breaking change in Discourse's plugins. And since those are persisted across different runs, the upgrade is failing.

We added some info about this issue to the upgrade notes for the Helm chart here: https://docs.bitnami.com/kubernetes/apps/discourse/administration/upgrade/#upgrading-instructions

In your case, you would need to remove (or update manually) the `lazy-yt` plugin which can be found in the following path:

```
/bitnami/discourse/plugins/lazy-yt
```

**Comment by ArtHoffmann** [comment]
I did - still broken :(

![image](https://user-images.githubusercontent.com/24555132/156855861-f3a17424-95f0-4319-8535-347124471c51.png)

what i did wrong?

**Comment by marcosbc** [comment]
Hi @ArtHoffmann, I'm afraid that we don't know what is happening to your installation. We encourage you to check Discourse logs in case anything is printed. Note that we perform automated tests to verify that upgrade works between different versions of the chart.

In addition, note that accessing the site at `/discourse` is not supported by us, nor officially by Discourse, as well as accessing in a port different than 80/443. We recommend to change to the default HTTP/HTTPS port (80/443) and to the `/` path, this may resolve your issues.
