### ISSUE TITLE
Kubernetes install - Sidekiq issue

### ISSUE THREAD

**Issue by Sikwan** [bitnami/bitnami-docker-discourse#62]
**Description**

As I am trying to deploy Discourse inside my Kubernetes environment (GCP), I find it extremely difficult to have everything working.
I see there used to be a recommended Kubernetes file but it was removed, so I did the implementation myself. 
I always block on the same issue though, everything is working fine except Sidekiq that will always throw the same error:

`nami    ERROR com.bitnami.discourse-sidekiq is not fully installed. You cannot execute commands`

**Steps to reproduce the issue:**

1. Deploy discourse to K8S (Kompose can be used, but I did it myself)
2. Replace all env variables that have default values by their values in the k8s environement
3. Inspect discourse-sidekiq logs

**Describe the results you received:**

Sidekiq will never boot, I even tried to create it 15minutes after Discourse was up and running just in case (I can access the Discourse UI through the specified port, so Sidekiq should have access)

**Describe the results you expected:**

I was expecting Sidekiq to work properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

bitnami/discourse:2.1.3

- Output of `docker version`:

```
N/A
```

- Output of `docker info`:

```
N/A
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

GKE

**Comment by tompizmor** [comment]
> As I am trying to deploy Discourse inside my Kubernetes environment (GCP), I find it extremely difficult to have everything working.

You are right! Discourse is an application with several services and components and it can be tricky to deploy to Kubernetes. We would like to create a helm chart when we have some time in order to deploy Discourse to kubernetes easier.

Have you checked the [How to deploy to Kubernetes section?](https://github.com/bitnami/bitnami-docker-discourse#how-to-deploy-discourse-in-kubernetes) in the README? 
We added that section recently along with a test.yaml file that should include all the necessary resources.

**Comment by Sikwan** [comment]
Hello,

Thanks for the feedback. Unfortunately when I opened the issue, the section was in the Readme but the file was not in the repo ;)

Checking it now, will come back ASAP!

**Comment by Sikwan** [comment]
It does work well now, though the image has been updated so I am not sure if my changed file was the fix.

Just for archive sake, I did not specify the REDIS_PORT for Sidekiq (using the default value), so the only change I got from the test.yaml was to hard set that value to its default!

It it helps anybody ;)
