### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by reilly3000** [bitnami/bitnami-docker-discourse#67]
**Description**

I am attempting to install the plugin located at 
https://github.com/discourse/discourse-openid-connect
Following these instructions:
https://docs.bitnami.com/oci/apps/discourse/configuration/install-plugins/

**Steps to reproduce the issue:**
1. Install the following images on AWS:
bitnami-discourse-2.1.3-1-r50-linux-ubuntu-16.04-x86_64-hvm-ebs-mp-d2b04609-5717-4a58-b4aa-30a5ece497fe-ami-0379e2096b4d471c4.4 (ami-02313943fe0ffe444)
2. cd /opt/bitnami/apps/discourse/htdocs 
3. RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-openid-connect --trace

**Describe the results you received:**
rake aborted!
NameError: uninitialized constant Auth::ManagedAuthenticator
/opt/bitnami/apps/discourse/htdocs/plugins/discourse-openid-connect/plugin.rb:9:in `activate!'
/opt/bitnami/apps/discourse/htdocs/lib/plugin/instance.rb:437:in `instance_eval'
/opt/bitnami/apps/discourse/htdocs/lib/plugin/instance.rb:437:in `activate!'
lib/discourse.rb:164:in `block in activate_plugins!'
lib/discourse.rb:161:in `each'
lib/discourse.rb:161:in `activate_plugins!'
/opt/bitnami/apps/discourse/htdocs/config/application.rb:224:in `<class:Application>'
/opt/bitnami/apps/discourse/htdocs/config/application.rb:39:in `<module:Discourse>'
/opt/bitnami/apps/discourse/htdocs/config/application.rb:38:in `<top (required)>'
/opt/bitnami/apps/discourse/htdocs/Rakefile:5:in `require'
/opt/bitnami/apps/discourse/htdocs/Rakefile:5:in `<top (required)>'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:82:in `block in run'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/opt/bitnami/apps/discourse/htdocs/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'

**Describe the results you expected:**

I expected to be able to then run precompile and then use the plugin.
**Additional information you deem important (e.g. issue happens only occasionally):**
I was unable to install other plugins as well, including the example akismet plugin

**Comment by tompizmor** [comment]
Hello @reilly3000,

Per your issue description, it looks like you are using the Amazon AMI and not the Bitnami docker image. The issues in this repository are meant to be only docker image related so I would report your issue in the [Bitnami community forum](https://community.bitnami.com/) instead.

**Comment by polarathene** [comment]
@tompizmor The docs seem to be out of date as the /opt path is no longer used? Seems to be `/bitnami/discourse` now?

**Comment by polarathene** [comment]
@tompizmor The docs seem to be out of date as the /opt path is no longer valid? Seems to omit the `apps` dir and no `htdocs` now? So `/opt/bitnami/discourse/`

**Comment by tompizmor** [comment]
Hi @polarathene,

Can you point me to the docs you are following? Please note that virtual machines and cloud images have a different folder structure than containers.

**Comment by polarathene** [comment]
@tompizmor [Same docs link](https://docs.bitnami.com/oci/apps/discourse/configuration/install-plugins/) as in the original issue of this thread:

> *cd /opt/bitnami/apps/discourse/htdocs*
> *RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL*
> *RAILS_ENV=production bundle exec rake assets:precompile*

I was successful by bringing up a shell in the container and running those commands with the `/opt/bitnami/discourse` path.Presumably it should be done by extending the image with a RUN command?

> Please note that virtual machines and cloud images have a different folder structure than containers.

Ah, well that makes sense. I came across those docs linked via google results, this issue and one on meta.discourse.org I think.

This project README and the what looks like identical one on [DockerHub](https://hub.docker.com/r/bitnami/discourse/), don't seem to cover how to install plugins?

**Comment by tompizmor** [comment]
Yes, the main change between containers and single-vm is the directory where Discourse is installed. In containers is `/opt/bitnami/discourse` and in single-vms `/opt/bitnami/apps/discourse/htdocs`

> This project README and the what looks like identical one on DockerHub, don't seem to cover how to install plugins?

Yes, the README is exactly the same. You can try the same commands documented for single-vms but just updating the paths.
