### ISSUE TITLE
Extraneous "domain" setting.

### ISSUE THREAD

**Issue by MicahZoltu** [bitnami/bitnami-docker-discourse#75]
Per discussion over in [meta.discourse](https://meta.discourse.org/t/what-sets-the-domain-in-the-email-settings/109784) it appears that the Bitnami Discourse package is setting a configuration variable called `smtp_domain` which is unused by Discourse.  There have been at least a couple issues on this in the past where people have been confused by the presence of this variable (#56 & #31) so it seems like the bitnami Discourse package should be fixed and this removed.

**Comment by javsalgar** [comment]
Hi,

According to the thread, it does not say that this parameter is unused. The Discourse official container makes use of an `app.yml` file that configures the container. In the Bitnami Discourse container you need to configure it using environment vars as explained here: https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration

Note that, if you already have initialized volumes in the application, then setting these variables will not work. Instead, you would need to edit the discourse.conf file.

**Comment by MicahZoltu** [comment]
Yeah, unfortunately the Discourse maintainers seem to be kind of dicks on their whole "if you didn't install the official way we refuse to talk to you" thing.  However, in the course of that conversation I got the impression that that setting is not used as the maintainers (before they found out I didn't do the official install and stopped helping me) did not recognize it or think that it should be present, and it isn't present in supported installs.

My suspicion (though hard to confirm when they refuse to talk to me) is that anything that ends up in the discourse.conf file will be presented in that UI, even if Discourse doesn't know anything about it.  In this case, `smtp_domain` is not used by Discourse anywhere, as evidenced by the fact that even though it is set to `example.com` everything functions correctly, yet it is presented in the UI because it is present in the configuration file.

----

Separate from all of that, `smtp_domain` is _not_ configurable by bitnami environment variables.  It is not present in the configuration documentation you linked, it is not present in the ENV list of the Dockerfile, and it is not present in any of the setup files added to the image.

**Comment by javsalgar** [comment]
Hi,

I see. Then it makes sense removing the value from discourse.conf. We will consider this in future releases of the container. Thank you very much for reporting :)

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a revision that removes that domain setting from the containers. If you find any issues, do not hesitate to reopen this ticket. Thanks for reporting :)
