### ISSUE TITLE
Don't load postgres extensions if they're already present

### ISSUE THREAD

**Issue by adarnimrod** [bitnami/bitnami-docker-discourse#78]
Discourse init loads Postgres extensions (`hstore` and `pg_trgm`). It fails if the extensions were already loaded. A small change from `CREATE EXTENSION` to `CREATE EXTENSION IF NOT EXISTS` would make the init scripts continue in that case. I encountered this recently when I had issues setting up a Discourse service and I constantly had `psql` running just to remove the extensions so I could remove these extensions and the container could continue with its init.

**Comment by javsalgar** [comment]
Hi, 

Thanks for letting us know. We will take a look at the issue. I will provide more details as soon as I have more information.

**Comment by javsalgar** [comment]
Here it is: https://github.com/bitnami/bitnami-docker-discourse/commit/0a69c9708de7500b236cdb8c3e5c739237ebd8a8

Please, do not hesitate to reopen the ticket if the issue persists.
