### ISSUE TITLE
Starting from scratch . . 

### ISSUE THREAD

**Issue by philiprhoades** [bitnami/bitnami-docker-discourse#79]
I had been using a Bitnami Discourse (version 1.9.7) container for a while on Fedora Linux 28/29 when I had a catastrophic head disk crash at the end of last year.  It has taken me a while to get more mission-critical stuff going and to now finally get back to trying to resurrect the Discourse setup.  My recollection for the previous setup was that there was only one container used ie there were no separate containers for postgres and redis etc.

Anyway, I am following the instructions in the README.md and things go OK till this:

~~~~
# docker run -d -p 80:3000 --name sidekiq --net=discourse-tier    bitnami/discourse nami start --foreground discourse-sidekiq
~~~~

yields:

~~~~
/usr/bin/docker-current: Error response from daemon: Conflict. The container name "/sidekiq" is already in use by container 87543eb07a440478b4e2e42e89cc710d91b8e59e67900d779de28f7c8873841a. You have to remove (or rename) that container to be able to reuse that name..
See '/usr/bin/docker-current run --help'.
~~~~

which is correct - nginx is already looking at port 80.  In the previous nginx conf for discourse I had:

~~~~
upstream prf {
  server 172.17.0.6:80;
}

server {
  listen      80;
  server_name forum.philiprhoades.org ;
  return      301 https://$server_name$request_uri;
}

server {
  listen 443;
  server_name forum.philiprhoades.org ;

  location / {
    proxy_pass http://prf; # match the name of upstream directive which is defined above
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
~~~~

How do I do something similar again?

Thanks,

Phil.

**Comment by javsalgar** [comment]
Hi,

It seems that you have another container named sidekiq running. Could you make sure that you do not have another container with the same name running?  This should help

```
docker ps -a
```
