### ISSUE TITLE
Memory Adjustment in Containers

### ISSUE THREAD

**Issue by tecnologiaterabyte** [bitnami/bitnami-docker-discourse#81]
**Description**

**Steps to reproduce the issue:**

1. [First Step]

Installation Discourse v2.2.2-dirty

**Additional information you deem important (e.g. issue happens only occasionally):**

It is possible to adjust the memory of the containers

**Version**

- Output of `docker version`: 

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.5.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.779GiB
Name: server.cjtterabyte.com
ID: QFFE:C7BB:F6P7:L5BM:FE2C:JSLP:SIQM:HPWG:PSHW:TRL2:ARIV:HQHD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by javsalgar** [comment]
Hi,

Could you elaborate more on your use case and what the problem you are experiencing is?

**Comment by tecnologiaterabyte** [comment]
I have a high consumption of RAM, I have a 4GB RAM vps and sidekut this consig 2.5GB, passenger 1.2GB

**Comment by tompizmor** [comment]
Hi @tecnologiaterabyte,

Depending if you are using docker-compose v3 or docker-compose v2 file reference you will need to indicate in one way or another.

- For docker-compose v3 [check this](https://docs.docker.com/compose/compose-file/#resources)
- For docker-compose v2 [check this](https://docs.docker.com/compose/compose-file/compose-file-v2/). Look for `mem_limit`

Also, take into account that Discourse application has [minimum requirements](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md#hardware-requirements) so you should take that into account.
