### ISSUE TITLE
Unable to configure SMTP without username / password (eg mail relay)

### ISSUE THREAD

**Issue by Stretch96** [bitnami/bitnami-docker-discourse#86]
**Description**

In Discourse, a valid configuration (`discourse.conf`) for SMTP settings is:

```
smtp_address = my-relay-mail-server.example.com
smtp_port = 25
smtp_enable_start_tls = true
smtp_authentication = none
smtp_domain = example.com
```

However, when launching the container, if `SMTP_USER` or `SMTP_PASSWORD` are not set, the following error is shown and the container dies:

```
Error executing 'postInstallation': You should specify username, password, host and port for SMTP configuration
```

Also, there does not appear to be a way to set `smtp_authentication` to `none`.
We have tried both `SMTP_AUTHENTICATION` and `DISCOURSE_SMTP_AUTHENTICATION`
This is the same for `smtp_domain`

To fix the issue, we need to set the `SMTP_USER` and `SMTP_PASSWORD`, then manually configure the `discourse.conf`

**Steps to reproduce the issue:**

Set docker env to:

```
SMTP_HOST=my-relay-mail-server.example.com
SMTP_PORT=25

DISCOURSE_SMTP_DOMAIN=example.com
SMTP_DOMAIN=example.com

DISCOURSE_SMTP_AUTHENTICATION=none
SMTP_AUTHENTICATION=none
```

Run `docker-compose up`

**Describe the results you received:**

```
sidekiq_1     | Error executing 'postInstallation': You should specify username, password, host and port for SMTP configuration
```

**Describe the results you expected:**

It would generate the config:

```
smtp_address = my-relay-mail-server.example.com
smtp_port = 25
smtp_enable_start_tls = true
smtp_authentication = none
smtp_domain = example.com
```

**Comment by andresbono** [comment]
Hi @Stretch96, thanks for reporting this issue. We will improve the way the container handles the SMTP settings and we will update the README to clarify the options available.

Thanks for the feedback!

**Comment by beltran-rubo** [comment]
Hi @Stretch96, we just released a new Discourse version that allows you to configure "SMTP_AUTH" to 'none' (it is 'login' by default). We also removed the error if the user/pass is empty so it would be possible to use your configuration.

Please post if you continue finding issues.

**Comment by Stretch96** [comment]
Awesome thanks @beltran-rubo 👍 

We'll give it a go and get back if there's any further issues 😬
