### ISSUE TITLE
Unable to set S3 settings via environment variables

### ISSUE THREAD

**Issue by Stretch96** [bitnami/bitnami-docker-discourse#87]
**Description**

We are trying to set the S3 settings via environment variables, but these are not set in `discourse.conf`

We have tried both `DISCOURSE_` and without:

```
DISCOURSE_S3_BUCKET=my-bucket
DISCOURSE_S3_REGION=eu-west-2
DISCOURSE_S3_USE_IAM_PROFILE=true
DISCOURSE_S3_CDN_URL=https://my-bucket.s3.eu-west-2.amazonaws.com
```

The settings also do not appear in the admin console

**Steps to reproduce the issue:**

Set docker env to:

```
DISCOURSE_S3_BUCKET=my-bucket
DISCOURSE_S3_REGION=eu-west-2
DISCOURSE_S3_USE_IAM_PROFILE=true
DISCOURSE_S3_CDN_URL=https://my-bucket.s3.eu-west-2.amazonaws.com
```

**Describe the results you received:**

No S3 configuration

**Describe the results you expected:**

S3 to be configured for uploads

**Comment by andresbono** [comment]
Hi @Stretch96,

Those options are not available for this container. You can check the full list of environment variables in the following places:
- https://github.com/bitnami/bitnami-docker-discourse#environment-variables
- https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/rootfs/discourse-inputs.json

You will need to modify the discourse configuration file to set the values for those settings. Let us know if you need more information on how to do it.

**Comment by Stretch96** [comment]
Hi @andresbono,

We were hoping to be able to automate the deployment as much as possible, so being able to set them as environment variables would be the best option for this IMO

I was trying to dig into where in the code `discourse.conf` is generated, but got a bit lost after the `nami` script

If you could point me to where the code for that is (if that bit is open source), I'd be happy to open a PR for this 👍

**Comment by andresbono** [comment]
Hi @Stretch96,

> We were hoping to be able to automate the deployment as much as possible, so being able to set them as environment variables would be the best option for this IMO

We will check if we can include those environment variables to ease the configuration of s3 options. It may take some time to have this feature included in the container.

> I was trying to dig into where in the code `discourse.conf` is generated, but got a bit lost after the `nami` script

You can find all the installation logic in the following two files:

```
/root/.nami/components/com.bitnami.discourse/main.js
/root/.nami/components/com.bitnami.discourse/helpers.js
```

> If you could point me to where the code for that is (if that bit is open source), I'd be happy to open a PR for this 👍

The code is open-source but it is not hosted on a public code repository like GitHub.

**Comment by andresbono** [comment]
To automate your deployment I'd recommend you to mount your own configuration file or even overwrite the container entry-point to add some extra configuration steps.

**Comment by andresbono** [comment]
Hi @Stretch96, were you able to setup the Discourse container?

**Comment by Stretch96** [comment]
Hi @andresbono,

We haven't yet looked further into getting S3 working

But we have managed to get Discourse running on a HA infrastructure 👍 (Currently using volume mounts to EFS rather than S3)

**Comment by andresbono** [comment]
Sounds nice! Are you still interested on defining S3 options through environment variables? What we would recommend for the general use case is to mount a custom configuration file if users need more specific configuration to do.

Are you ok with your new infrastructure using EFS?

**Comment by Stretch96** [comment]
Yep, ideally all environment variables that are available on `discourse/discourse` would be the same on `bitnami/discourse`

The reason we went with `bitnami/discourse` was that it we were about to create our own Dockerfile/image (because it appears discourse are focusing on making it as easy as possible for someone to launch it on a single instance), but found Bitnami have already done it 😬 

But then found the environment variables aren't the same 😞 

It works okay with EFS, we just mounted `/bitnami` and `/opt/bitnami/discourse/public/assets` so that they are shared across all containers. Only issue was when we realised the `discourse-sidekiq` container also placed files in the uploads ... so they were split between `/bitnami/discourse` and `/bitnami/discourse-sidekiq`. A symlink for the uploads dir solved that problem though.

**Comment by andresbono** [comment]
Thanks @Stretch96, it makes sense. We will update this issue to let you know about any change we do for the discourse container.

**Comment by girkantas** [comment]
I'm just wondering how it would be possible to add additional overrides (for example for max_reqs_per_ip_per_10_seconds). I tried to mount just configuration file, but this doesn't work:

```
        volumes:
            - type: bind
              source: ./docker/discourse-config/discourse.conf
              target: /opt/bitnami/discourse/conf/discourse.conf
            - type: volume
              source: discourse_data
              target: /bitnami
```

**Comment by andresbono** [comment]
Hi @girkantas, what is the error that you get? Did you mount the file on the first run of the container?

**Comment by girkantas** [comment]
The error is:
`Error executing 'postInstallation': Files to substitute resolved to an empty list`

Not sure what do you mean by saying if I mount it on first run, I just add it to my docker-compose file and I'm expecting that it will use that configuration file.

**Comment by andresbono** [comment]
@girkantas, I opened #125 for your issue. Let's keep the conversation there as it seems a different issue.

**Comment by noplanman** [comment]
I'm interested in the S3 environment variables too, is there any progress or alternative solution to this?

**Comment by juan131** [comment]
Please let's continue the conversation in the issue @andresbono opened about overriding the configuration file settings.

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

The new images should include a fix for these issues by using the following environment variable:

- `DISCOURSE_EXTRA_CONF_CONTENT`: Extra configuration to append to the `discourse.conf` configuration file. No defaults.

**Comment by luizjr** [comment]
Hello! As this image is used as the basis for the helm chart, I think you should be concerned about these variables, as Kubernetes's intention is to make the application highly available.

Using S3 can leave us without the requirement to have persistent volume.

There are examples of variables here:
https://meta.discourse.org/t/using-object-storage-for-uploads-s3-clones/148916

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
