### ISSUE TITLE
Installing Discourse into a Fedora Podman container? 

### ISSUE THREAD

**Issue by philiprhoades** [bitnami/bitnami-docker-discourse#89]
**Suggestion**

Podman has some advantages compared to docker containers - does Binami have any interest in developing this version of Discourse? - it would be MUCH more attractive to Fedora / RH / CentOS etc.

Thanks,
Phil.

**Comment by andresbono** [comment]
Hi @philiprhoades, we haven't checked that alternative but it is good to know your interests on it. However, there are no plans for supporting Podman in the short/mid term.

 I will share your message with the appropriate team so they are aware.

Thanks for the suggestion!

**Comment by philiprhoades** [comment]
@andresbono ,

Thanks for the reply - is that something I could get involved in?  I mean if I was prepared to start the exercise myself, could I get some support from the existing devs?

**Comment by andresbono** [comment]
We can give you some advice or guidelines if you find issues when building things on your own.

But note that it would be very limited as we don't have experience with Podman.
