### ISSUE TITLE
Running multiple discourse containers in a single server

### ISSUE THREAD

**Issue by mertmetin** [bitnami/bitnami-docker-discourse#93]
Hello,
I have been using a bitnami's discourse container — and bunch of others such as redis, postgresql and sidekiq as well  with no problem. Everything was working just absolutely fine.

However, I ran a weird issue after I set up another discourse container. The second discourse container seems okay at first. However, things get weird when I change the site settings for example. The same settings also apply to other discourse instance. Weird right?

Also, when I logout from one instance, I also log out from the other instance automatically.
How is that possible? What am I doing possibly wrong?

**Comment by miguelaeh** [comment]
Hi @mertmetin ,
I guess you deploy them on local using docker-compose. If that is the case probably you use the same volumes for the two instances. Could you check that?
