### ISSUE TITLE
https certificate for bitnami docker-discourse

### ISSUE THREAD

**Issue by pcellix** [bitnami/bitnami-docker-discourse#96]
Hello

I have no encountered an official guide for attaching tls certificate to the bitnami docker discourse
Is there such guide? If no please tell how to do it :) 

Thank you :-)

Have a Great Day! :)

**Comment by javsalgar** [comment]
Hi,

I think that, in order to make HTTPS work, you would need to use a reverse proxy solution in front of the container. In Kubernetes, this is done using Ingress rules for example.
