### ISSUE TITLE
Inconsistent documentation about (config) persistence

### ISSUE THREAD

**Issue by dhaavi** [bitnami/bitnami-docker-discourse#98]
I am getting warnings about persistent configuration:
```
WARN  ==> A persisted configuration file 'discourse.conf' was found inside '/bitnami/discourse/conf'.  This feature is not supported anymore. Please mount the configuration file at '/opt/bitnami/discourse/conf' instead.
WARN  ==> A persisted configuration file 'database.yml' was found inside '/bitnami/discourse/conf'.  This feature is not supported anymore. Please mount the configuration file at '/opt/bitnami/discourse/conf' instead.
```

But the README clearly states that `/bitnami` is the correct location:
```
  discourse:
    volumes:
      - '/path/to/discourse-persistence:/bitnami'
```

See here:
https://github.com/bitnami/bitnami-docker-discourse/blob/master/README.md#mount-persistent-folders-in-the-host-using-docker-compose

**Comment by alemorcuq** [comment]
Hi, @dhaavi.

The configuration files `discourse.conf` and `database.yml` are not persisted anymore. You should mount them to `/opt/bitnami/discourse/conf` as shown in the warning.

We will update the README to reflect how to mount configuration files.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi, @dhaavi.

We have updated our README to reflect this. Thank you very much.

Regards,
Alejandro
